### ISSUE TITLE
打开python文件时，一直有个滚动条

### ISSUE THREAD

**Issue by penn201500** [seagle0128/.emacs.d#101]
操作系统：macos 10.13
版本：emacs 26.2
配置文件：当前最新.emacs.d版本
问题描述：打开python文件时，一直有个滚动条； pyenv-mode-set 切换python版本之后，滚动条还存在。
问题：
1. 如何屏蔽掉该显示条显示？
2. 因为已有pyenv版本信息，如何屏蔽python版本的显示？ 如截图中的 Python 2.7.15 和 Python 3.7.3

![image](https://user-images.githubusercontent.com/16840448/62760144-dceedf80-bab5-11e9-89c0-66a4d7b26c8e.png)

![image](https://user-images.githubusercontent.com/16840448/62760230-13c4f580-bab6-11e9-8a2b-9755a3f66b6a.png)

**Comment by penn201500** [comment]
可能有影响的配置：

**Comment by seagle0128** [comment]
> 如何屏蔽掉该显示条显示？
这是python lang server 在分析项目，分析完了会消失。如果有问题，可以到 `lsp-mode` 相关项目提问。

> 因为已有pyenv版本信息，如何屏蔽python版本的显示？ 如截图中的 Python 2.7.15 和 Python 3.7.3
`(setq doom-modeline-env-version nil)`。

请先认真阅读 README 再提问，谢谢！
