### ISSUE TITLE
Can't run eshell on Centaur Emacs

### ISSUE THREAD

**Issue by crazyraven** [seagle0128/.emacs.d#104]
Hi!
I've enjoyed Centaur emacs and fresh installed Centaur emacs yesterday with netease mirror on my second laptop(elpa repository has networking problem but netease is working)
After finished install, I restarted emacs and tried to run eshell, but it's not working. --debug-init has no error messages, but I've found below error message on minibuffer.
  
> Symbol’s value as variable is void: eshell-preoutput-filter-functions

OS: debian 10

if you need more information please let me know.

thank you!

**Comment by seagle0128** [comment]
1. Which version of Emacs?
1. Run `M-x toggle-debug-on-error` and `eshell` after restarting.

**Comment by crazyraven** [comment]
1. emacs-26
2. 
Debugger entered--Lisp error: (void-variable eshell-preoutput-filter-functions)
  (member (quote xterm-color-filter) eshell-preoutput-filter-functions)
  (if (member (quote xterm-color-filter) eshell-preoutput-filter-functions) eshell-preoutput-filter-functions (setq eshell-preoutput-filter-functions (cons (quote xterm-color-filter) eshell-preoutput-filter-functions)))
  (closure (t) nil (add-hook (quote eshell-before-prompt-hook) (function (lambda nil (setq xterm-color-preserve-properties t)))) (if (member (quote xterm-color-filter) eshell-preoutput-filter-functions) eshell-preoutput-filter-functions (setq eshell-preoutput-filter-functions (cons (quote xterm-color-filter) eshell-preoutput-filter-functions))) (setq eshell-output-filter-functions (remove (quote eshell-handle-ansi-color) eshell-output-filter-functions)))()
  eval-after-load-helper("/usr/share/emacs/26.2/lisp/eshell/eshell.elc")
  run-hook-with-args(eval-after-load-helper "/usr/share/emacs/26.2/lisp/eshell/eshell.elc")
  do-after-load-evaluation("/usr/share/emacs/26.2/lisp/eshell/eshell.elc")
  require(eshell)
  byte-code("\300\301!\210\302\303!\210\302\304!\210\305\306\307\310\311\312\313\303&\007\210\314\315\307\316#\210\317\320\321\322\323DD\324\325\326\313\306&\007\210\317\327\321\322\330DD\331\325\332\333\311\334E\335\336\337\335\340\341\306!\"\342\"\"\343#\313\306&\007\207" [provide esh-module require eshell esh-util custom-declare-group eshell-module nil "The `eshell-module' group is for Eshell extension modules, which\nprovide optional behavior which the user can enable or disable by\ncustomizing the variable `eshell-modules-list'." :tag "Extension modules" :group load "esh-groups" nomessage custom-declare-variable eshell-module-unload-hook funcall function #f(compiled-function () #<bytecode 0x2129381>) "A hook run when `eshell-module' is unloaded." :type hook eshell-modules-list #f(compiled-function () #<bytecode 0x209e695>) "A list of optional add-on modules to be loaded by Eshell.\nChanges will only take effect in future Eshell buffers." append set "Supported modules" mapcar #f(compiled-function (modname) #<bytecode 0x209e6a1>) sort symbol-name eshell-subgroups string-lessp ((repeat :inline t :tag "Other modules" symbol))] 14)
  require(esh-module)
  byte-code("\300\301!\210\302\303!\210\302\304!\210\302\305!\210\302\306!\210\302\307!\210\310\311\312\313\314\315\316\317&\007\210\320\321\322\323\324DD\325\326\327\316\311&\007\210\320\330\322\323\331DD\332\326\327\316\311&\007\210\320\333\322\323\334DD\335\326\327\316\311&\007\210\320\336\322\323\337DD\340\341\342\326\327\316\311&\011\210\320\343\322\323\344DD\345\326\346\316\311&\007\210\320\347\322\323\350DD\351\326\327\316\311&\007\210\320\352\322\323\353DD\354\326\346\316\311&\007\210\320\355\322\323\356DD\357\326\327\316\311&\007\210\320\360\322\323\361DD\362\326\363\316\311&\007\210\320\364\322\323\365DD\366\326\367\316\311&\007\210\320\370\322\323\371DD\372\326\346\316\311&\007\210\320\373\322\323\374DD\375\326\376\316\311&\007\210\320\377\322\323\201@\0\ DD\201A\0\326\327\316\311&\007\210\320\201B\0\322\323\201C\0\ DD\201D\0\326\327\316\311&\007\210\320\201E\0\322\323\201F\0\ DD\201G\0\326\201H\0\316\311&\007\210\320\201I\0\322\323\201J\0\ DD\201K\0\326\201L\0\316\311&\007\210\201M\0\201N\0\201O\0\312#\210\201P\0\211\203i\001\211@\201N\0\001N\203b\001\201O\0\001N\204b\001\201Q\0\201O\0\002\201N\0\004N#\210\001A\266\202\202>\001\210\201R\0\201N\0\201O\0\201S\0#\210\320\201O\0\322\323\201T\0\ DD\201U\0\326\346\316\311&\007\207" [provide esh-mode require esh-util esh-module esh-cmd esh-io esh-var custom-declare-group eshell-mode nil "This module contains code for handling input from the user." :tag "User interface" :group eshell custom-declare-variable eshell-mode-unload-hook funcall function #f(compiled-function () #<bytecode 0xe95859>) "A hook that gets run when `eshell-mode' is unloaded." :type hook eshell-mode-hook #f(compiled-function () #<bytecode 0xe82481>) "A hook that gets run when `eshell-mode' is entered." eshell-first-time-mode-hook #f(compiled-function () #<bytecode 0x4bbb61>) "A hook that gets run the first time `eshell-mode' is entered.\nThat is to say, the first time during an Emacs session." eshell-exit-hook #f(compiled-function () #<bytecode 0x47b7e5>) "A hook that is run whenever `eshell' is exited.\nThis hook is only run if exiting actually kills the buffer." :version "24.1" eshell-kill-on-exit #f(compiled-function () #<bytecode 0x400f61>) "If non-nil, kill the Eshell buffer on the `exit' command.\nOtherwise, the buffer will simply be buried." boolean eshell-input-filter-functions #f(compiled-function () #<bytecode 0x28fae81>) "Functions to call before input is processed.\nThe input is contained in the region from `eshell-last-input-start' to\n`eshell-last-input-end'." eshell-send-direct-to-subprocesses #f(compiled-function () #<bytecode 0x28fae8d>) "If t, send any input immediately to a subprocess." eshell-expand-input-functions #f(compiled-function () #<bytecode 0x274aba1>) "Functions to call before input is parsed.\nEach function is passed two arguments, which bounds the region of the\ncurrent input text." eshell-scroll-to-bottom-on-input #f(compiled-function () #<bytecode 0x274abad>) ...] 10)
  require(esh-mode)
  byte-code("\300\301!\210\300\302!\210\303\304\305\306\307\310\311\312\313\314&\011\207" [require esh-util esh-mode custom-declare-group eshell nil "Command shell implemented entirely in Emacs Lisp.\nIt invokes no external processes beyond those requested by the\nuser, and is intended to be a functional replacement for command\nshells such as bash, zsh, rc, 4dos." :link (info-link "(eshell)Top") :version "21.1" :group applications] 10)
  #<subr autoload-do-load>((autoload "eshell" 1070409 t nil) eshell nil)
  apply(#<subr autoload-do-load> ((autoload "eshell" 1070409 t nil) eshell))
  autoload-do-load((autoload "eshell" 1070409 t nil) eshell)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1d32ff>)(eshell record nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1d32ff>) eshell record)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1d32ff>) (eshell record))
  command-execute(eshell record)
  counsel-M-x-action("eshell")
  ivy-call()
  #f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table, supplied for `minibuffer-completion-table'.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nPRESELECT, when non-nil, determines which one of the candidates\nmatching INITIAL-INPUT to select initially.  An integer stands\nfor the position of the desired candidate in the collection,\ncounting from zero.  Otherwise, use the first occurrence of\nPRESELECT in the collection.  Comparison is first done with\n`equal'.  If that fails, and when applicable, match PRESELECT as\na regular expression.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is re-displayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes the candidate, which is a string, as its only argument.\n\nMULTI-ACTION, when non-nil, is called instead of ACTION when\nthere are marked candidates. It takes the list of candidates as\nits only argument. When it's nil, ACTION is called on each marked\ncandidate.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x260ae81>)("M-x " ("toggle-debug-on-error" "gomoku" "eshell" "lsp-mode" "viet-encode-viqr-region" "ansi-term" "replace-string" "eshell-new" "shell" "artist-mode" "highlight-indent-guides-mode" "linum-mode" "line-number-mode" "indent-region" "picture-mode" "org-plot/gnuplot" "xterm-color-test" "org-display-inline-images" "scroll-bar-mode" "ps-spool-buffer" "menu-bar-mode" "org-latex-export-to-latex" "cd" "5x5" "amx" "arp" "dbx" "dig" "dlv" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "deer" "diff" "dirs" "esup" "ffap" ...) :predicate nil :require-match t :history counsel-M-x-history :action counsel-M-x-action :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  apply(#f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table, supplied for `minibuffer-completion-table'.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nPRESELECT, when non-nil, determines which one of the candidates\nmatching INITIAL-INPUT to select initially.  An integer stands\nfor the position of the desired candidate in the collection,\ncounting from zero.  Otherwise, use the first occurrence of\nPRESELECT in the collection.  Comparison is first done with\n`equal'.  If that fails, and when applicable, match PRESELECT as\na regular expression.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is re-displayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes the candidate, which is a string, as its only argument.\n\nMULTI-ACTION, when non-nil, is called instead of ACTION when\nthere are marked candidates. It takes the list of candidates as\nits only argument. When it's nil, ACTION is called on each marked\ncandidate.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x260ae81>) ("M-x " ("toggle-debug-on-error" "gomoku" "eshell" "lsp-mode" "viet-encode-viqr-region" "ansi-term" "replace-string" "eshell-new" "shell" "artist-mode" "highlight-indent-guides-mode" "linum-mode" "line-number-mode" "indent-region" "picture-mode" "org-plot/gnuplot" "xterm-color-test" "org-display-inline-images" "scroll-bar-mode" "ps-spool-buffer" "menu-bar-mode" "org-latex-export-to-latex" "cd" "5x5" "amx" "arp" "dbx" "dig" "dlv" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "deer" "diff" "dirs" "esup" "ffap" ...) :predicate nil :require-match t :history counsel-M-x-history :action counsel-M-x-action :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x))
  ivy-read("M-x " ("toggle-debug-on-error" "gomoku" "eshell" "lsp-mode" "viet-encode-viqr-region" "ansi-term" "replace-string" "eshell-new" "shell" "artist-mode" "highlight-indent-guides-mode" "linum-mode" "line-number-mode" "indent-region" "picture-mode" "org-plot/gnuplot" "xterm-color-test" "org-display-inline-images" "scroll-bar-mode" "ps-spool-buffer" "menu-bar-mode" "org-latex-export-to-latex" "cd" "5x5" "amx" "arp" "dbx" "dig" "dlv" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "deer" "diff" "dirs" "esup" "ffap" ...) :predicate nil :require-match t :history counsel-M-x-history :action counsel-M-x-action :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1d32ff>)(counsel-M-x nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1d32ff>) counsel-M-x)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1d32ff>) counsel-M-x)
  command-execute(counsel-M-x)

Thank you!
