### ISSUE TITLE
Emacs gets stuck on opening any python file

### ISSUE THREAD

**Issue by CruiseDevice** [seagle0128/.emacs.d#106]
Emacs gets stuck on opening any python file. On opening a python file, the file does not load but the editor stars downloading some stuff. And after few minutes it throws an runtime error. Checked this with HTML and JS file, it works fine. Up until now i have only tested this with HTML, JS and Python file. Emacs version i have installed on my system is `25.3.2`

**Comment by seagle0128** [comment]
I believe it's a connection issue. [lsp-python-ms](https://github.com/emacs-lsp/lsp-python-ms) couldn't be downloaded. Please run `M-x lsp-python-ms-setup` to check the network. If it still doesn't work, you can build it yourself.
