### ISSUE TITLE
Emacs 出现卡死

### ISSUE THREAD

**Issue by awerdx520** [seagle0128/.emacs.d#107]
问题描述： 当我创建两个 frame 时，并且在一个frame 中打开三个以上的文件时，在另一个frame 中打开 org 文件，展开大纲是emacs卡死，debug 无任何错误。有时候需要等待1-2分钟恢复正常。org 文档的大小没有100行。并且只在 light theme 下发生。还有任何时候打开org 文件都比较吗不管大小，
展开大纲卡一下后恢复。
![DeepinScreenshot_select-area_20190822143128](https://user-images.githubusercontent.com/15448027/63491988-1f1f1480-c4eb-11e9-8011-481ced3aa579.png)
![DeepinScreenshot_select-area_20190822143659](https://user-images.githubusercontent.com/15448027/63492042-32ca7b00-c4eb-11e9-9b16-0c4b6f123da8.png)
更改过配置文件，但是没有修改过 treemacs 和 org 的配置文件，添加了其他的init file。

**Comment by seagle0128** [comment]
请提供 profiler 报告，具体见
https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html

**Comment by awerdx520** [comment]
1. version： emacs 26.2， org mode version 9.1.9（release_9.1.9-65-g5e4542)
   os： Linux  4.19.66-1-MANJARO
2. 有个人配置，没有删除原有配置，只是添加了包，邮件等的设置，放在`/lisp`下单独的文件中，在 init.el 加载。
3. profiler报告
[profiler1.txt](https://github.com/seagle0128/.emacs.d/files/3534186/profiler1.txt)
[profiler2.txt](https://github.com/seagle0128/.emacs.d/files/3534187/profiler2.txt)

**Comment by seagle0128** [comment]
通过分析 profiler report，发现`org-fancy-priorities`占用大量 CPU。

解决方法：
1. 禁用`org-fancy-priorities-mode`。
1. 重新设置`org-fancy-priorities-list`。你可以先升级 Centaur (`centaur-update`)试试，最新版本中已经修改过。

猜测跟你使用的字体有关，对于 Unicode 字符识别出现了问题。

**Comment by awerdx520** [comment]
谢谢，问题已经解决，打开org文件无任何问题。
