### ISSUE TITLE
打开gnus，MacOS下全屏的emacs会分布到多个桌面上

### ISSUE THREAD

**Issue by zwz** [seagle0128/.emacs.d#108]
如下截图所示（MacOS调度中心界面的上半部分桌面全屏的截图）
![屏幕快照 2019-08-24 下午9 01 02](https://user-images.githubusercontent.com/897156/63637844-f0a06580-c6b3-11e9-89a3-64e667eb5d13.png)

emacs出现在三个桌面上
第一个emacs鼠标停留上方，不会出现Mac的菜单栏
第二个和第三个emacs，全屏黑色，但是鼠标停留上方可以叫出Mac的菜单栏。随便敲点文字`xxx`，回到第一个emacs上可以看到minibuffer中有这些文字：`xxx is undefined`

另外，叫出的Mac菜单栏下退出全屏（以及最小化）等按钮也没有了

**Comment by seagle0128** [comment]
请使用 issue template 提交问题，没有基本的必须的信息无法有效的定位。

另外，Centaur 并没有提高gnus 配置，请先确认个人的配置是否有问题。我的测试中，Centaur 并没有这个问题。

**Comment by zwz** [comment]
我的.gnus.el中只有9行，设置了用户名邮箱，以及新闻组而已，大体如下
```
(setq user-full-name "****")
(setq user-mail-address "****")
(setq gnus-select-method '(nnml ""))
(setq gnus-secondary-select-methods '(
                                      (nntp "news.gmane.org")
                                      (nnimap "163"
                                              (nnimap-address "imap.163.com")
                                              (nnimap-server-port 993)
                                              (nnimap-stream ssl))))
```

`ns-use-native-fullscreen`的值是`nil`

另外，我没有在centaur上添加任何自己的配置。

我的emacs版本：
GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-28

我的macos：10.14.5

**Comment by seagle0128** [comment]
不好意思，我仍然不知道如何重现这个问题，除非你能提供更详细的信息。

**Comment by zwz** [comment]
嗯，我发现也不是每次打开gnus就能重现
我会留意，希望能找出规律

**Comment by zwz** [comment]
@seagle0128 
我想我是找到问题所在了
这回我没有打开gnus（所以和gnus无关，或许我应该修改一下标题了）
启动emacs后，我就开始在写网页，然后跳出一个补齐框的时候，停顿了一下
然后我就发现emacs占用了2个桌面，之前说的问题就出现了

另外，这个补齐框似乎高度很有限的样子
![屏幕快照 2019-08-28 下午4 46 55](https://user-images.githubusercontent.com/897156/63840503-c0a6da00-c9b3-11e9-83ef-55310da6540b.png)

**Comment by seagle0128** [comment]
使用最新的 Centaur 版本并更新所有包，没有这个问题。请再试试。

**Comment by zwz** [comment]
你在尝试之前，有没有先进入全屏模式呢？

我也是最新的版本（或许有一些包可能有一周老了）

**Comment by seagle0128** [comment]
肯定是全屏模式啦。
这个问题是 Emacs 本身的 issue，只有 macOS  全屏模式下使用 child frame才会出现。`(setq ns-use-native-fullscreen nil)`就是为了规避这个问题，按道理是不会弹出黑框才对。

**Comment by zwz** [comment]
那就有点奇怪了，我很容易重现了
1. 打开emacs，进入全屏
2. 打开一个js/html文件
3. 输入一些文字（自动促发补齐）
这时候屏幕可能会一闪（卡顿一下的感觉），弹出补齐框
这时候就会发现emacs占据两个桌面

**Comment by seagle0128** [comment]
我找到办法在本地重现该问题了。似乎`ns-use-native-fullscreen`不起作用了，这是 emacs 本身的 bug。

有个解决办法，在`custom.el`中加入：
```elisp
(with-eval-after-load 'company
  (add-hook 'company-mode-hook
            (lambda () (company-box-mode -1))))
(with-eval-after-load 'flycheck
  (add-hook 'flycheck-mode-hook
            (lambda () (flycheck-posframe-mode -1))))
```

**Comment by seagle0128** [comment]
我已经找到修复的办法，必须用`toggle-frame-fullscreen`，用鼠标点击窗口上的绿色圆点是不起作用的。

**Comment by zwz** [comment]
我刚更新了一下
点击窗口绿色圆点全屏，还是会出现这个问题
你的意思是，必须使用`toggle-frame-fullscreen`，是吗

**Comment by seagle0128** [comment]
是的，上面说的很清楚了，这个是emacs本身的bug。
