### ISSUE TITLE
How to disable package 

### ISSUE THREAD

**Issue by chengyi** [seagle0128/.emacs.d#109]
How to disable a package (e.g. flyspell) without changing the code. Thank you!

**Comment by seagle0128** [comment]
1. Don't install `aspell`.
1. Add this in `custom-post.el`.
```elisp
    (add-hook 'text-mode-hook
              (lambda (flyspell-mode -1)))
    (add-hook 'outline-mode-hook
              (lambda (flyspell-mode -1)))
```

**Comment by chengyi** [comment]
@seagle0128 thanks. keep it simple and stupid.
