### ISSUE TITLE
python mode auto-complete error in current version 

### ISSUE THREAD

**Issue by GeneKao** [seagle0128/.emacs.d#11]
Hi, thanks for sharing such a nice setting for emacs. I found out that python autocomplete is no longer working in the current version recently. Any idea how can I fix this? Please see my screenshot below. 

If I use 3.0 release version, autocomplete works just fine, without those messages. 

By the way, I have tried it and got this error on Mac, Ubuntu and Cygwin. 

<img width="571" alt="issue" src="https://user-images.githubusercontent.com/1162842/34643038-a8766392-f31d-11e7-815c-a236e79b507a.png">

**Comment by GeneKao** [comment]
Solution was provided [here](https://github.com/seagle0128/.emacs.d/issues/15).

**Comment by seagle0128** [comment]
Already fixed in b715e3ebb7d7f61a4ef20dfd0d4dd673c4bf0e0a. 
Thanks for your reporting!
