### ISSUE TITLE
Too slow in general

### ISSUE THREAD

**Issue by arianitu** [seagle0128/.emacs.d#112]
If you have a relatively large JavaScript file, and enable `js-mode` on Emacs 27 for example, it's reaaally slow.

I tried to find what the source of the slowness was, but there were way too many minor mode. I reversed to my own custom setup since this has a lot of performance issues.

**Comment by seagle0128** [comment]
Please do profiling in your env to find out the bottleneck.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html

BTW: I am using `js2-mode` for javascript files.

**Comment by seagle0128** [comment]
Any update?

**Comment by seagle0128** [comment]
Close due to inactivity.
