### ISSUE TITLE
主题设置问题

### ISSUE THREAD

**Issue by awerdx520** [seagle0128/.emacs.d#114]
当我打开 treemacs时，不能高亮当前行。需要重新载入theme。还有设置高亮当前行时也要重新载入。
![deepin-screen-recorder_Select area_20190915224026](https://user-images.githubusercontent.com/15448027/64923186-1ed41980-d80a-11e9-872a-3d720de2f135.gif)
![deepin-screen-recorder_emacs_20190915224140](https://user-images.githubusercontent.com/15448027/64923187-20054680-d80a-11e9-8115-6617ffc636b8.gif)

**Comment by seagle0128** [comment]
本地无法重现这个问题。请按照模板提供更详细的信息，并确认个人配置没有影响。谢谢！

**Comment by seagle0128** [comment]
Close due to inactivity.
