### ISSUE TITLE
Update init-custom.el #115 pr问题

### ISSUE THREAD

**Issue by wow-yorick** [seagle0128/.emacs.d#117]
通过emacs界面菜单设置的变量默认写在custom.el文件中  而不是custom-post.el中 那请问下可以改变下默认保存的文件吗？也就可以解决我遇到的问题了

**Comment by seagle0128** [comment]
可以设置`custom-file`，但是并不能解决你的问题。你应该放到 `custom-post.el`，或者使用`eval-after-load`来加载。并且，不应该使用界面来进行设置。
