### ISSUE TITLE
Broken Icons on Windows

### ISSUE THREAD

**Issue by davidpgil** [seagle0128/.emacs.d#121]
I used scoop (https://scoop.sh/) to intall Emacs on Windows and then I installed Centaur-Emacs's "emacs.d". I notice that I cannot get the icons to display under Windows. I tried manually installing the fonts as was stated. Do you have any idea why my icons are broken? I am installing this on a non-admin account at work. Could that be an issue?

Here is what I am seeing:
![image](https://user-images.githubusercontent.com/41744832/66772411-a99c4880-ee8a-11e9-96f8-30dae1691f08.png)

**UPDATE**
Although icons are still not showing correctly, some icons show now that I added these lines:
```
(set-language-environment "UTF-8")
(set-default-coding-systems 'utf-8)
```
![image](https://user-images.githubusercontent.com/41744832/66844518-68fd0780-ef3c-11e9-946b-28f4b516cd28.png)

Any ideas how I can fix this?

**Comment by seagle0128** [comment]
Did you run `M-x all-the-icons-install-fonts`?

**Comment by davidpgil** [comment]
Yes, I have run that command and have manually installed the fonts that were downloaded which includes "all-the-icons.ttf". At my job, I am allowed to install fonts without admin priviledges. I think this is normally not allowed in Windows though. I was probably given special access to be able to do this because I install fonts often due to the nature of my work. 

Now I think the issue may be that Centaur Emacs requires admin in order to use/execute the fonts that are installed. Do you have any ideas for a workaround?

**Comment by seagle0128** [comment]
I don't think Centaur Emacs changes the font behaviors of vanilla Emacs. Please check if `all-the-icons` are displayed in Emacs (From menu, Options-> Set default Font...). And don't add any other personal customizations about fonts.

**Comment by seagle0128** [comment]
I have no idea :(

I am not using `scoop` and Windows. But it was working well on Windows 7 and 10, with GNU Emacs which I downloaded from the official website.

**Comment by davidpgil** [comment]
I downloaded the Windows version of Emacs 26.3 from the [official site](https://www.gnu.org/software/emacs/download.html) just now and ran it and I still encounter the same issue, where some icons are still broken.

**Comment by seagle0128** [comment]
Try `M-x all-the-icons-insert-octicon`, and check `mark-github` and `tools` icons.

**Comment by davidpgil** [comment]
I see this is intended to insert an icon manually. They still don't show up and appear broken.

**Comment by seagle0128** [comment]
Did you install octicon font correctly?

**Comment by shanyouli** [comment]
Maybe you should install the [symbola](http://users.teilar.gr/~g1951d/) font, because it may be that your current default font does not contain the required glyph, and Emacs does not find the glyph you really need when searching for this character in other fonts.
For more details, please read [Emacs-fonts-and-fontsets](https://idiocy.org/emacs-fonts-and-fontsets.html)
PS：I used to use the glyph problem before, and I clearly installed the font correctly, but I can't display the glyph correctly. Then I installed the  [symbola](http://users.teilar.gr/~g1951d/)  font to solve it.

**Comment by seagle0128** [comment]
Thanks for the information, @shanyouli !

**Comment by davidpgil** [comment]
@shanyouli thank you! thats fixed it for me!
![image](https://user-images.githubusercontent.com/41744832/67009988-d5057a00-f0ba-11e9-88f3-192dc3eb4c3f.png)
However, if "Symbola" is required for icons to not be broken on Windows 10, I think it would be a good idea to change the font requirements for Windows users to match a free software license. [Here](http://users.teilar.gr/~g1951d/License.pdf) is the license for Symbola.

**Comment by rkalyankumar** [comment]
Head to https://github.com/domtronn/all-the-icons.el/tree/master/fonts and download all the ttf font files and right click each of the files downloaded and choose install for all users & restart your emacs.

**Comment by seagle0128** [comment]
Now using `M-x centaur-install-fonts` will install the necessary fonts automatically.
