### ISSUE TITLE
Prolog interactive mode not displaying correctly

### ISSUE THREAD

**Issue by sggutier** [seagle0128/.emacs.d#122]
As the title says, when running prolog interactive the format is not displayed correctly.  Works fine on vanilla emacs.

I think it might be somewhat related to ansi escape codes and identation.  (`[32m%` is an ansi escape code, afaik).

![Screenshot_20191016_131141](https://user-images.githubusercontent.com/5473302/66946625-f3b23500-f016-11e9-9eb8-fbc653d0be64.png)

**Comment by seagle0128** [comment]
I am not using prolog, so please test with this snippet in your env.

```elisp
(add-hook 'comint-preoutput-filter-functions 'xterm-color-filter nil t)
```

**Comment by sggutier** [comment]
Thanks a lot! 

This (mostly) fixed it.  I also needed to disable global indent on the prolog inferior buffer. 

The actual lines I added were:
``` elisp
(add-hook 'prolog-inferior-mode-hook
          (lambda ()
            (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter nil t)))
(add-to-list 'aggressive-indent-excluded-modes 'prolog-inferior-mode)
```
