### ISSUE TITLE
[求助]请教怎么显示lsp的菜单

### ISSUE THREAD

**Issue by wow-yorick** [seagle0128/.emacs.d#126]
![image](https://user-images.githubusercontent.com/3367220/68462571-c5a3c780-0247-11ea-99e6-79ca8c4b8585.png)
以前lsp菜单中有显示的 请问下怎么开启

**Comment by seagle0128** [comment]
现在在右键菜单。请先咨询`lsp-mode`开发者。新的提交在此：

https://github.com/emacs-lsp/lsp-mode/commit/caed5dcbffa0aac4332b187a9897bced5949babb

![image](https://user-images.githubusercontent.com/140797/68466931-48308500-0250-11ea-8fd3-f20061086725.png)
