### ISSUE TITLE
ubuntu 下打开文件需要点击两次

### ISSUE THREAD

**Issue by wow-yorick** [seagle0128/.emacs.d#128]
![2019-11-10 11-39-45屏幕截图](https://user-images.githubusercontent.com/3367220/68538425-1255e280-03af-11ea-9d63-e29cd83a001b.png)
第一次点击文件会提示 apply: Selecting deleted buffer

**Comment by seagle0128** [comment]
我这里没有问题，包括 macOS 和 Ubuntu 都测试过了。你先检查下你的个人配置，看看`emacs -Q`能不能重现。

**Comment by wow-yorick** [comment]
我这还是有这个问题 请问下有啥办法可以知道我当前操作运行的是哪个方法或命令呀？ 这样我就可以追踪到具体的实现了

**Comment by seagle0128** [comment]
`C-h k`

**Comment by wow-yorick** [comment]
![2019-11-15 23-53-39屏幕截图](https://user-images.githubusercontent.com/3367220/68956548-43953f00-0803-11ea-953a-22bd1d3da24b.png)
init-vcs.el 文件中注释掉 56-58行 就好了 我emacs 版本 26.2  系统ubuntu   不晓得啥原因
`;; (when emacs/>=25.2p
;;   (use-package magit-todos
;;     :hook (emacs-startup . magit-todos-mode)))
`

**Comment by seagle0128** [comment]
`C-h k` 鼠标点击文件到底是什么操作？

**Comment by wow-yorick** [comment]
(dired-find-file)
我是键盘 RET 回车键操作的

**Comment by seagle0128** [comment]
你到底是鼠标还是键盘操作的？标题不是点击两次吗？
请把问题描述清楚，提供必要的详细信息，否则无法解决。谢谢。

**Comment by wow-yorick** [comment]
我是用键盘选中文件后 要按两次回车才能进入文件

**Comment by seagle0128** [comment]
本地测试没有这个问题。请按照模板提供详细重现信息。
