### ISSUE TITLE
状态栏如图这个不完整的拐角怎么搞掉？

### ISSUE THREAD

**Issue by flyingns** [seagle0128/.emacs.d#13]
![screen shot 2018-01-12 at 09 06 45](https://user-images.githubusercontent.com/16456728/34855061-9d48a2f0-f778-11e7-9332-d487af9bc56c.png)

Mac OS 10.13

spacemacs 里powerline-scale 默认 1.1 也有这个拐角，设置成 1.3 可以去掉。

你的这个配置好像没看到哪里可以定制？

**Comment by seagle0128** [comment]
这个跟字体有关， 你可以在`custom.el`中加上你的额外配置。请参考https://github.com/seagle0128/.emacs.d#customization

**Comment by seagle0128** [comment]
看起来目前没有问题了，close。如果有问题请重新提交issue。
