### ISSUE TITLE
New gopls basic configuration for lsp-mode

### ISSUE THREAD

**Issue by rif** [seagle0128/.emacs.d#130]
Hey @seagle0128,

Thank you for the excellent configuration, I use it as my main setup for a few months now, great job!

There are some updates on the basig golang gopls configuration for lsp-mode:
https://github.com/golang/tools/blob/master/gopls/doc/emacs.md

Please have a look, maybe you find something useful there.

Cheers,
rif

**Comment by seagle0128** [comment]
Thank you for the information, @rif .

The basic configurations have been merged into `lsp-go`. I am one of the maintainers of `lsp-mode`. I will add other necessary configurations into `Centaur Emacs`.

**Comment by rif** [comment]
Great, we are in good hands :)
