### ISSUE TITLE
indentation line disapeared in YAML mode

### ISSUE THREAD

**Issue by crazyraven** [seagle0128/.emacs.d#132]
Hi 
I use centaur emacs for editing yaml file with highlight-indent-guides-mode.
but if popup menu(which is showed up box that I input same word) showed, indentation line being disappeared immediately. 
I also tested with lisp mode, indentation line was not disappeared even if popup box showed up.

my OS is debian 10 and emacs version is 26.
if you need more info, please let me know.

Thank you

**Comment by seagle0128** [comment]
That's as designed for better performance. Actually `highlight-indent-guides-mode` is disabled by default in recent changes. It's laggy while editing the large files.

**Comment by crazyraven** [comment]
well noted.
thank you.
