### ISSUE TITLE
请问ansi-term不支持中文吗？

### ISSUE THREAD

**Issue by Wjinlei** [seagle0128/.emacs.d#136]
1.当我按f9打开终端时，中文显示 ？ 号，请问是不支持中文吗？
2.打开时默认在下面打开，能从右边打开吗？ 如何设置呢？

谢谢，Centaur Emacs 真的很好用

**Comment by seagle0128** [comment]
1. `<f9>`默认使用`vterm`，没有找到会使用`ansi-term`。两者都支持中文，只要环境变量设置正确。不知道你是使用的是什么操作系统，猜测是某个 Linux 发行版？检查下系统变量 LANG 是否是 UTF-8 或者 GBK。
1. 想要后边打开，直接输入`M-x vterm`或者`M-x ansi-term`。或者重新绑定到<f9>.

**Comment by seagle0128** [comment]
@Wjinlei 更新个新方法

> 2.打开时默认在下面打开，能从右边打开吗？ 如何设置呢？
```elisp
 (setq shell-pop-window-position "right")
```

**Comment by Wjinlei** [comment]
好的，谢谢，测试有效
