### ISSUE TITLE
How to Disable "git-grep(1)" Popup Browser Tab

### ISSUE THREAD

**Issue by davidpgil** [seagle0128/.emacs.d#137]
Whenever I start Centaur Emacs I get a browser tab popup that points to the man page for "git-grep(1)". How do I stop this from happening?

**Comment by seagle0128** [comment]
Duplicated with #84 .

I suppose you are using Windows, right? It seems the `magit` issue. Try this snippet in your configurations.

```elisp
(with-eval-after-load 'magit
  (magit-auto-revert-mode -1))
```

**Comment by davidpgil** [comment]
I put those lines in my 'custom-post.el' and i still see it. Here is the file that pops up: 'file:///C:/Users/username/scoop/apps/git/2.24.0.windows.2/mingw64/share/doc/git-doc/git-grep.html'

**Comment by seagle0128** [comment]
Put the snippet in `custom.el`, or disable/comment `magit` to try.

If it's due to `magit`, please file an issue there. I am not working on Windows.

**Comment by seagle0128** [comment]
Update: it should be related to `magit` and `Git for Windows`.

**Comment by seagle0128** [comment]
Update: I found the root cause. It's due to `magit-todos`. Please refer to https://github.com/alphapapa/magit-todos/issues/43.

**Comment by davidpgil** [comment]
Confirmed fixed. Thank you.

**Comment by alphapapa** [comment]
@seagle0128 FYI this has been fixed in https://github.com/alphapapa/magit-todos/commit/c64bcbe2be6de692d12d6c5c2bd122c85c8cb26b.  The test in https://github.com/seagle0128/.emacs.d/commit/c1391de93af023e8c079ccc0c0f0cb1cd43a231d that uses `nice` should now be unnecessary (I don't know why it worked, haha).

**Comment by seagle0128** [comment]
@alphapapa Thank you for the update!

**Comment by davidpgil** [comment]
I centaur-update supposed to update magit-todos.el? I had to edit the line manually.

**Comment by seagle0128** [comment]
@davidpgil 

> Is `centaur-update` supposed to update `magit-todos.el`?

Yes. It will update the configurations and packages. You should wait for a while if you have not updated for a long time. I believe it works.
