### ISSUE TITLE
When I open an HTML file: "No LSP server for web-mode (check *lsp-log*)"

### ISSUE THREAD

**Issue by davidpgil** [seagle0128/.emacs.d#138]
I'm using Windows 10 with Centaur Emacs. Why is this happening?

**Comment by seagle0128** [comment]
The reason is: "No LSP server for web-mode (check *lsp-log*)".

You should read https://github.com/emacs-lsp/lsp-mode and install the language servers you want.

**Comment by davidpgil** [comment]
Thanks. I wasn't aware of this. Emacs newbie here :)

Trying to get into it.
