### ISSUE TITLE
一启动就卡死

### ISSUE THREAD

**Issue by masterwrw** [seagle0128/.emacs.d#14]
环境：Manjaro Linux 17.1.0，8G内存，开虚拟机不卡。
clone 下来后，创建了 custom.el 到 .emacs.d 目录下，注释了my-proxy 那一行。
启动 emacs，下载包的过程中，卡死了，鼠标都动不了，只能强制按电源键关机。
重启后再试还是卡死，再重启在终端下 emacs -nw --debug-init，还是卡死。
实在想不通，怎么会卡死呢？？？

**Comment by seagle0128** [comment]
看起来是下载包的过程中hung住了。试试在`custom.el`中打开以下配置：
```elisp
(setq my-package-archives 'emacs-china)   ; melpa, emacs-china or tsinghua
```

**Comment by masterwrw** [comment]
开始就是打开了 emacs-china 的，刚刚把 custom.el 删除后，启动自动下载包，漫长的等待后终于下完了没卡死。
*Warnings* buffer 显示：
Error (use-package): Failed to install tide: Args out of range: #<killed buffer>, 12343297, 13212370  
*Compile-Log* 显示：
Warning (bytecomp): the function ‘cygwin-convert-file-name-from-windows’ is not known to be defined.                                
Warning (bytecomp): macro ‘swift-mode:with-temp-comment-buffer’ defined too late  
不知道是不是因为 tide 包的原因导致原先的卡死。

**Comment by seagle0128** [comment]
应该是网络问题导致下载package hung住了，一般容易发生在第一次启动或者升级包的过程中。下次遇到可以试试换个源，或者直接删除`~/.emacs.d/elpa`重新启动。
