### ISSUE TITLE
markdown不支持多行代码块

### ISSUE THREAD

**Issue by Wjinlei** [seagle0128/.emacs.d#141]
您好，我在编辑markdown文件的时候，用
``` shell
多行代码
多行代码
``` 
然后C-c C-c p 预览时，发现不支持多行代码块，且没有换行，请问是什么原因呢，系统是mac10.14.6
已经brew install markdown 了。

**Comment by Wjinlei** [comment]
\``` shell
多行代码
多行代码
\```

**Comment by seagle0128** [comment]
`C-c C-c g`: 使用[grip-mode](https://github.com/seagle0128/grip-mode).

**Comment by Wjinlei** [comment]
@seagle0128 按导出该如何导出呢？

**Comment by seagle0128** [comment]
导出：`C-c C-c e`，但是 markdown 对 github 格式渲染支持并不佳。还是建议用 grip 预览，再另存。

**Comment by Wjinlei** [comment]
哦哦哦，好的，明白了
