### ISSUE TITLE
counsel-grep-base-command custom

### ISSUE THREAD

**Issue by Iorest** [seagle0128/.emacs.d#145]
Why not set counsel-grep-base-command to    "rg -S --no-heading --line-number --color never %s %s",I think this is better,because some error happens when set it "rg -S --no-heading --line-number --color never '%s' %s".

**Comment by seagle0128** [comment]
What kind of errors?

**Comment by Iorest** [comment]
when I search “<body>”, it returns “error code 2”.While  "rg -S --no-heading --line-number --color never %s %s" does not.

**Comment by seagle0128** [comment]
What about using `\"\"`?

**Comment by Iorest** [comment]
It does not work for me.
