### ISSUE TITLE
python mode has wrong syntax missure

### ISSUE THREAD

**Issue by c0001** [seagle0128/.emacs.d#15]
> :init (cl-pushnew '(company-backend-with-yas 'company-anaconda) company-backends)))))

This line has the excessive quote symbol,and must be:
> :init (cl-pushnew (company-backend-with-yas 'company-anaconda) company-backends)))))

**Comment by GeneKao** [comment]
@c0001 thanks a lot, that just solves my [previously posted issue](https://github.com/seagle0128/.emacs.d/issues/11)!

**Comment by seagle0128** [comment]
Already fixed in b715e3ebb7d7f61a4ef20dfd0d4dd673c4bf0e0a. 
Thanks for your reporting!
