### ISSUE TITLE
在Windows下如果打开一个不是project的文件，将会出错

### ISSUE THREAD

**Issue by e190** [seagle0128/.emacs.d#150]
![图片](https://user-images.githubusercontent.com/39932163/72588100-2af3f300-3932-11ea-84ed-09f2a33a141b.png)
![图片](https://user-images.githubusercontent.com/39932163/72588300-cbe2ae00-3932-11ea-9457-872267d94069.png)

**Comment by seagle0128** [comment]
请打开toggle-debug-on-error，然后可以看到backtrace，并粘贴到这里。

**Comment by e190** [comment]
![图片](https://user-images.githubusercontent.com/39932163/72609228-60fb9c00-395f-11ea-9a10-fa3c818a3d93.png)

**Comment by seagle0128** [comment]
Can you check `all-the-icons` is installed and loaded correctly?

**Comment by e190** [comment]
![图片](https://user-images.githubusercontent.com/39932163/72658017-2852d580-39e6-11ea-87ba-26f240013e0d.png)

**Comment by seagle0128** [comment]
It's a bug of `all-the-icons`. Please file an issue there.

**Comment by seagle0128** [comment]
Close due to https://github.com/domtronn/all-the-icons.el/issues/184.

**Comment by seagle0128** [comment]
See https://github.com/domtronn/all-the-icons.el/pull/197#issuecomment-625221688

**Comment by seagle0128** [comment]
Close it due to https://github.com/domtronn/all-the-icons.el/pull/209.
