### ISSUE TITLE
[bug] undo-fu Not found

### ISSUE THREAD

**Issue by johncming** [seagle0128/.emacs.d#152]
Error (use-package): Failed to install undo-fu: https://melpa.org/packages/undo-fu-20200103.1445.el: Not found

GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.6.0) of 2019-08-31

**Comment by johncming** [comment]
@seagle0128 

after pull newest master branch.

**Comment by seagle0128** [comment]
`package-refresh-contents`.
