### ISSUE TITLE
Get one option for user to toggle whether starting serve-mode or not.

### ISSUE THREAD

**Issue by LEXUGE** [seagle0128/.emacs.d#153]
I want to use systemd to manage emacs server.
However, it seems centaur will automatically start a server when it is started.
It works with problem when I am using systemd, but it doesn't when it's on itself.
I wish there could be an option for user to toggle whether start server by default or not.

**Comment by seagle0128** [comment]
Use `(setq centaur-server nil)` in `custom.el`.

**Comment by LEXUGE** [comment]
Thanks
