### ISSUE TITLE
Under the daemon mode, some icons are not loaded.

### ISSUE THREAD

**Issue by LEXUGE** [seagle0128/.emacs.d#154]
Due to an issue that is described [here](https://emacs-china.org/t/topic/6610). it would not load icons properly under daemon mode.
![photo_2020-01-31_18-01-26](https://user-images.githubusercontent.com/13804737/73536980-34b54480-4462-11ea-95ce-2e1133fa5a9a.jpg)
Right one is loaded under systemd daemon and its modeline is not drawn properly.

**Comment by seagle0128** [comment]
Please file an issue in [emacs-dashboard](https://github.com/emacs-dashboard/emacs-dashboard).

**Comment by LEXUGE** [comment]
I have reported it to emacs-dashboard
https://github.com/emacs-dashboard/emacs-dashboard/issues/210

**Comment by seagle0128** [comment]
@LEXUGE Sorry. Please close that issue. I am investigating.

**Comment by LEXUGE** [comment]
> @LEXUGE Sorry. Please close that issue. I am investigating.

I have closed it.

**Comment by seagle0128** [comment]
After the investigation, I would like suggest to use GUI with `server-mode` instead of `daemon`. For `daemon`, terminal mode is better.

**Comment by LEXUGE** [comment]
> After the investigation, I would like suggest to use GUI with `server-mode` instead of `daemon`. For `daemon`, terminal mode is better.

Which means I could just use the default config without any change? since I think it is integrated into the centaur.

**Comment by seagle0128** [comment]
Of course you can fork and change. But my suggestion is add your own configurations to `custom.el` and `custom-post.el`.

**Comment by LEXUGE** [comment]
I mean is the `server-mode` enabled by default?

**Comment by seagle0128** [comment]
It's enabled by default. The option is `centaur-server`. Please read REAME.

**Comment by LEXUGE** [comment]
I see, it was proposed by me.
Anyway, thanks for your help and time!

**Comment by seagle0128** [comment]
Welcome!

**Comment by zabbal** [comment]
> After the investigation, I would like suggest to use GUI with `server-mode` instead of `daemon` for better experience. For `daemon`, terminal mode is better.

Could you please share some technical details? What's in daemon-mode causes that while server-mode is unaffected?

**Comment by seagle0128** [comment]
@zabbal In `daemon-mode`, `display-graphic-p` returns nil, while non-nil in `server-mode`.

**Comment by zabbal** [comment]
Thanks! I wonder how spacemacs managed to work around that.
