### ISSUE TITLE
Config seems slow

### ISSUE THREAD

**Issue by atanasj** [seagle0128/.emacs.d#158]
Not sure what is is, but it seems to bog down after a while, I've tried to debug and I use `helm` for my bibtex manager, although it sucks `CPU`, it is feels similar when using a leaner bibtex manager e.g., `ebib`.

Any thoughts?

**Comment by seagle0128** [comment]
You can do profiling to find out the bottle neck. Refer to https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html.

**Comment by atanasj** [comment]
Done. `helm` uses a lot more, but still feels bogged with `ebib`. `helm` is much easier to use for what I need. Any thoughts on tweaks to improve performance?

<img width="1271" alt="ebib-bib" src="https://user-images.githubusercontent.com/27214625/74540438-e476d000-4f93-11ea-82fb-ae62fd0812b0.png">
<img width="1279" alt="helm-bib" src="https://user-images.githubusercontent.com/27214625/74540448-e93b8400-4f93-11ea-9828-a0ae14690de5.png">

**Comment by seagle0128** [comment]
Sorry. I don't use `helm` due to the performance issue. I cannot help on it, I think.

**Comment by atanasj** [comment]
Thanks for your help. Do you have a config you could recommend?

**Comment by seagle0128** [comment]
Sorry. I have no recommendation for helm.

**Comment by atanasj** [comment]
Sorry, what I meant was a good configuration that maybe you use. Doesn't have to be helm, preferable that it isn't as it just adds extra dependencies.

**Comment by seagle0128** [comment]
I am using and developing Centaur Emacs, nothing else.

**Comment by atanasj** [comment]
Thanks for that. I know this issue is closed, but I found this advise about changes to config to support `helm` [here](https://emacs.stackexchange.com/questions/19705/how-to-better-debug-emacs-cpu-management).

I was wondering if there was a way to change the below code via my `custom-post.org` file (as I don't want to mess with the standard config?

```emacs-lisp
;; Speed up startup
(defvar centaur-gc-cons-threshold (if (display-graphic-p) 8000000 800000)
  "The default value to use for `gc-cons-threshold'. If you experience freezing,
decrease this. If you experience stuttering, increase this.")
```
I experimented with larger values and this seemed to work. I'm not sure if was just psychological, as I noticed your config below should manage this behaviour anyway: 

```emacs-lisp
;; Avoid GCs while using `ivy'/`counsel'/`swiper' and `helm', etc.
;; @see http://bling.github.io/blog/2016/01/18/why-are-you-changing-gc-cons-threshold/
(defun my-minibuffer-setup-hook ()
  (setq gc-cons-threshold centaur-gc-cons-upper-limit))
```

Thanks again for all your help and excellent emacs config!

**Comment by seagle0128** [comment]
Of course, just use`(setq centaur-gc-cons-threshold xxxx)`.
