### ISSUE TITLE
Inconsistent  ui when using xref-find-references in go-mode

### ISSUE THREAD

**Issue by johncming** [seagle0128/.emacs.d#159]
1. use keymapping M-?

![image](https://user-images.githubusercontent.com/11719334/74582777-1cfdc480-4ffb-11ea-94ed-0f39585d6c79.png)

2. use M-x to call xref-find-references directly 

![image](https://user-images.githubusercontent.com/11719334/74582790-4880af00-4ffb-11ea-8d81-0db9eed26aa1.png)

The situations is not consistent in go-mode. How to use the second situation in go-mode. 

I have tried the command in elisp-mode wihch result is the second situation.

Thanks.

**Comment by seagle0128** [comment]
`(define-key lsp-ui-mode-map [remap xref-find-references] nil)`.

**Comment by seagle0128** [comment]
I updated the default keybindings. Just update to the latest version.

**Comment by johncming** [comment]
> I updated the default keybindings. I believe it has better experience.
> 
> ![image](https://user-images.githubusercontent.com/140797/74587295-c2c92780-502b-11ea-9b9b-e8fc1fc4e607.png)

Thanks for your help.  But the sequence of the result of xref is undefined. It's better to use text context sequence.

**Comment by seagle0128** [comment]
The candidates sorting is by designed. `(ivy-prescient-mode -1)` can disable it.
