### ISSUE TITLE
如何关闭auto format

### ISSUE THREAD

**Issue by jkunlin** [seagle0128/.emacs.d#161]
您好，我在编辑c++文件的时候，会不停地format，请问如何禁用这个特性。
另外，c++文件输入`{`回车后，缩进是8个空格，请问可以在哪里设置呢？

**Comment by seagle0128** [comment]
It's a compatibility issue between `ccls` and `aggressive-indent`. (https://github.com/MaskRay/emacs-ccls/issues/30)
