### ISSUE TITLE
can't set c-basic-offset

### ISSUE THREAD

**Issue by jkunlin** [seagle0128/.emacs.d#164]
` (setq c-basic-offset 2)` in custom-post.el doesn't work.

**Comment by seagle0128** [comment]
`c-basic-offset` is a buffer-local variable.

```elisp
(add-hook 'c-mode-common-hook (lamda () (setq c-basic-offset 2)))
```

**Comment by jkunlin** [comment]
`(add-hook 'c-mode-common-hook (lambda () (setq c-basic-offset 2)))` doesn't work as well.

**Comment by seagle0128** [comment]
I just provide an example there. You should tweak in your config.

```elisp
(with-eval-after-load 'cc-mode
  (setq c-mode-common-hook nil)
  (add-hook 'c-mode-common-hook (lamda () (setq c-basic-offset 2))))
```
