### ISSUE TITLE
counsel-rg exact match

### ISSUE THREAD

**Issue by johncming** [seagle0128/.emacs.d#166]
The default behavior of counsel-rg is fuzzy matching, how to enable exact match which may be better default behavior when reading code.

Thanks.

**Comment by seagle0128** [comment]
The default behavior is non-fuzzy. Press `C-o M` to change the match methods.

**Comment by johncming** [comment]
> The default behavior is non-fuzzy. Press `C-o M` to change the match methods.

The command is not worked.

**Comment by seagle0128** [comment]
`C-o` is the default shortcut for `hydra-ivy/body`. I believe it's working.
