### ISSUE TITLE
Indent of .go files are getting weird, not respect gofmt

### ISSUE THREAD

**Issue by on99** [seagle0128/.emacs.d#167]

**Comment by seagle0128** [comment]
How weird?
Check your `gopls` configurations.

https://github.com/dominikh/go-mode.el#gopls-integration
https://github.com/golang/tools/blob/master/gopls/README.md

**Comment by on99** [comment]
ahha, my gopls configuration is default setting. If I remember correctly, the indentation was changed after I updated centaur the day before yesterday.

<img width="945" alt="Screenshot 2020-02-21 at 12 21 40" src="https://user-images.githubusercontent.com/13196393/75004156-2b3d5c00-54a5-11ea-9648-f6e6fcd37a29.png">

**Comment by seagle0128** [comment]
It seems `tab-width` is incorrect. I am investigating.

**Comment by seagle0128** [comment]
@on99 Which version of Emacs are you using?

**Comment by seagle0128** [comment]
It's an issue of `all-the-icons-ivy-rich`. Already fixed in https://github.com/seagle0128/all-the-icons-ivy-rich/commit/0d59f9791b50e5b498b7f4255b75511c53e21025.

**Comment by on99** [comment]
Fix confirmed, thank you!
