### ISSUE TITLE
switch cursor

### ISSUE THREAD

**Issue by johncming** [seagle0128/.emacs.d#168]
![image](https://user-images.githubusercontent.com/11719334/75000295-e9a6b400-5498-11ea-9a02-fc05f5fd6087.png)

Is there a way to switch cursor between the two highlight positions?

Thanks

**Comment by seagle0128** [comment]
Waht do you mean exactly?

**Comment by johncming** [comment]
> Waht do you mean exactly?

When I move the cursor to `func`, the return statement `return b.String()` is highlight too. The behaviors is a useful way to navigate code. How to move the cursor on `func` to `return b.String()`

**Comment by seagle0128** [comment]
Are you using `Centaur`? How do you highlight the different words with the same color? I have no idea.

**Comment by johncming** [comment]
> Are you using `Centaur`? How do you highlight the different words with the same color? I have no idea.

I use the terminal with `xrvt`. It may be a mistake in this setting.

Another question: how to exchange cursor with the same highlight word.

**Comment by seagle0128** [comment]
If you highlight the words with `M-i`, you can use `M-n` and `M-p` the move the cursor. Refer to https://github.com/wolray/symbol-overlay for details.
