### ISSUE TITLE
doom-mode-line in Centaur emacs failed to change face when emacs-zoom-window is triggered

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#169]
@seagle0128 
I have been using emacs-zoom-window with doom-mode-line before moving to centaur emacs.
Usually when we zoom a window , the mode line _changes its color to green_ stating that user is in a zoomed window. This does not happen with Centaur emacs , Is there any configuration need to make this work

Link to emacs-zoom-window - https://github.com/syohex/emacs-zoom-window

code the is resposible to change the face
```elisp
(defcustom zoom-window-mode-line-color "green"
  "Color of mode-line when zoom-window is enabled"
  :type 'string)

;; This called in zoom-window function
(set-face-background 'mode-line zoom-window-mode-line-color curframe)
```

mode-line changes color fine if i execute 
`(set-face-background 'mode-line "blue")`
It is just not changing face when zoom-window is used

My zoom window config - 
```elisp
(use-package zoom-window
  :bind ("C-x C-z" . zoom-window-zoom)
  :config
  (custom-set-variables
   '(zoom-window-mode-line-color "blue")
   '(zoom-window-use-persp t))
  (zoom-window-setup))
```

**Comment by CsBigDataHub** [comment]
It is working I have fixed it. Thanks

**Comment by seagle0128** [comment]
`zoom-window` is incompatible with `solaire-mode`. Try this:

```elisp
(defvar-local my-solaire-mode solaire-mode)
(advice-add #'zoom-window-zoom :before (lambda () (solaire-mode -1)))
(advice-add #'zoom-window--restore-mode-line-face :after
            (lambda () (solaire-mode my-solaire-mode)))
```
