### ISSUE TITLE
init-dired.el cause the dired-mode not working properly 

### ISSUE THREAD

**Issue by GeneKao** [seagle0128/.emacs.d#17]
Hi, I encountered a problem whenever I use C-x C-f or C-x d to list a directory; I got an empty page. 
I got a message like `insert-directory: Listing directory failed but 'access-file' worked`
After I disable https://github.com/seagle0128/.emacs.d/blob/55b07da55415b48ee75cde67a3f99dd80f3bb491/init.el#L89 everything back to normal. I guess something must wrong with /lisp/init-dired.el

Any clue how to fix this? thanks a lot! 
p.s. This problem only happens on Mac, not on Linux.

**Comment by seagle0128** [comment]
@GeneKao Thanks for reporting. Which version of Emacs are you using? I cannot recreate the issue with GNU Emacs 25.3 and 26.0.91.

**Comment by seagle0128** [comment]
Already fixed. Please check.
The recommendation is using GNU `ls` as `gls' from `coreutils' on macOS, for better experience :-)

**Comment by GeneKao** [comment]
@seagle0128 I just also test it on my mac, and it works perfectly. Thanks a lot!

**Comment by seagle0128** [comment]
Welcome.
