### ISSUE TITLE
Package ivy-yasnippet does not display template when selected

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#171]
Hi @seagle0128 

I am using [ivy-yasnippet](https://github.com/mkcms/ivy-yasnippet) and I have used it before migrating to centaur emcas as well. 

The issue here is , when used with centaur config the snippets are NOT dynamically displayed in the active buffer as shown in the gif.

![ivy-gif](https://raw.githubusercontent.com/mkcms/ivy-yasnippet/master/demo.gif)

**Comment by seagle0128** [comment]
That's by designed. `ivy-yasnippet--preview` will affect the `doom-modeline`, so disable it.

**Comment by seagle0128** [comment]
The issue is addressed. You MUST update the configurations and `doom-modeline` package to the latest.

**Comment by CsBigDataHub** [comment]
@seagle0128 , Thanks. Works perfectly .
