### ISSUE TITLE
Theme feature request

### ISSUE THREAD

**Issue by rif** [seagle0128/.emacs.d#176]
Hey @seagle0128,

Thanks again for your awesome configuration, it's the only one that I was happy to switch to after 10+ of keeping my own :)

I love the new "auto" option for the themes. How about having a "random" one too? It would select a random theme at every start. It's just to keep boredom away, what do you think?

P.S. Even crazier would be to have a numeric value to change the theme every x minutes but I guess this is too extreme. Sometimes when I find myself staring at the screen I change theme just to give me an extra boost.

**Comment by seagle0128** [comment]
It's an interesting feature although I don't use. Will commit later.

>P.S. Even crazier would be to have a numeric value to change the theme every x minutes but I guess this is too extreme. Sometimes when I find myself staring at the screen I change theme just to give me an extra boost.

A new function `centaur-load-random-theme` is introduced, and you can use it like below.

```elisp
(setq rand-theme-timer (run-with-timer 0 3600 #'centaur-load-random-theme))
```

Also, you can change theme manually with `centaur-load-random-theme` any time.

**Comment by rif** [comment]
That is perfect, thank you very much!
