### ISSUE TITLE
go文件中lsp不起作用

### ISSUE THREAD

**Issue by 404cn** [seagle0128/.emacs.d#177]
今天在更新centaur 和 package之后打开go文件就没有补全了。

手动 m-x lsp 后提示
![DeepinScreenshot_select-area_20200303170628](https://user-images.githubusercontent.com/24653356/75759981-68410280-5d71-11ea-9952-80920d68e3c2.png)

这是 lsp-log 
![DeepinScreenshot_emacs_20200303170947](https://user-images.githubusercontent.com/24653356/75760197-d4bc0180-5d71-11ea-8eab-fd5fa95ec9d0.png)

重启 gopls 
![DeepinScreenshot_select-area_20200303171458](https://user-images.githubusercontent.com/24653356/75760654-93782180-5d72-11ea-9cfe-d69936d37175.png)

**Comment by seagle0128** [comment]
What happened? Has the issue been addressed?

**Comment by 404cn** [comment]
-.- , I dont't know, I just update centaur and packages.

I delete my GOPATH and reinstall go and all tools. And it fixed.

**Comment by seagle0128** [comment]
Okay. Good luck!
