### ISSUE TITLE
[Feature request] use-package no-littering

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#178]
Hi @seagle0128 ,

Checking if you are interested in using [no-littering](https://github.com/emacscollective/no-littering) package to keep .emacs.d directory clean.

Here is a sample configuration from my previous configuration

```emacs-lisp
(use-package no-littering               ; Keep .emacs.d clean
  :config (progn
            (require 'recentf)
            (add-to-list 'recentf-exclude no-littering-etc-directory)
            (add-to-list 'recentf-exclude no-littering-var-directory)
            (setq create-lockfiles nil
                  delete-old-versions t
                  kept-new-versions 6
                  kept-old-versions 2
                  version-control t)))
```

**Comment by seagle0128** [comment]
The big problem is no migration functionality. I don't think it will bring big benifit.

**Comment by seagle0128** [comment]
Thanks anyway! I am closing for now, but I will continue tracking it.
