### ISSUE TITLE
关于多窗口C-x o不能跳转的问题

### ISSUE THREAD

**Issue by zgj224** [seagle0128/.emacs.d#18]
最近在用Centaur Emacs的配置，发现一个问题，当我开三个1，2，3窗口，2和3开的是同一文件，这时候执行C-x o跳转其他窗口，这时候会停留在原来的窗口，跳转的失败！请抽个时间解决下吧。

**Comment by seagle0128** [comment]
按照你的描述我在本地进行了测试，没有发现问题。请看下图：

![emacs](https://user-images.githubusercontent.com/140797/37558048-e2eb85a4-2a48-11e8-9f49-fc8da81817a7.gif)
