### ISSUE TITLE
upgrade cause 'Args out of range: #[nil nil display-table nil nil ...], 12'

### ISSUE THREAD

**Issue by penn201500** [seagle0128/.emacs.d#180]
reproduce：
1. execute centaur-update
2. start emacs

![image](https://user-images.githubusercontent.com/16840448/75943958-6b530480-5ed1-11ea-9c4f-4ed9bd1e95f2.png)

env info:
Mac 10.14
emacs 26.3
.emacs.d commit id: 4601edf

**Comment by seagle0128** [comment]
Can you turn on `toggle-debug-on-error` to get the backtrace?

**Comment by penn201500** [comment]
tks！ no error msg. So, i delete .emacs.d and git clone again.  It's OK now

**Comment by seagle0128** [comment]
Great!
