### ISSUE TITLE
magit forge enhancement

### ISSUE THREAD

**Issue by atanasj** [seagle0128/.emacs.d#181]
I have copied the below `forge` config into the `init-vcs.el` based on https://github.com/magit/forge/issues/140. I think it very much enhances the forge experiences when interacting with issues. 

```emacs-lisp
  ;; Access Git forges from Magit
  ;; config from https://github.com/magit/forge/issues/140
  (when (executable-find "cc")
    (use-package forge
      :demand
      :config
      (setq forge-topic-list-columns
            '(("#" 4 t (:right-align t) number nil)
              ("Title" 35 t nil title  nil)
              ("Milestone" 9 t nil milestone nil)
              ("State" 6 t nil state nil)
              ("Updated" 10 t nill updated nil)
              ))))
```

I couldn't figure out a way to add it from my `custom-post.org` file using `with-eval-after-load` method, as it always failed, or the `add-to-list` would add the additional items at the beginning of the tabulated list and just didn't work right, so it went into the `init-vcs.el`, where seems to work pretty good.

Is there a way for me to add it properly, or would you consider adding this to your repo? I would do a `PR`, but don't really know how that works or what to do (but happy to learn / try if you think it useful). See screenshot for changes that this `forge` config implements: 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27214625/75981649-0af7ad80-5f39-11ea-9a26-70fac152eeeb.png">

**Comment by seagle0128** [comment]
Just put this to `custom.el` or `custom-post.el`, without `with-eval-after-load`.

```elisp
(setq forge-topic-list-columns
            '(("#" 4 t (:right-align t) number nil)
              ("Title" 35 t nil title  nil)
              ("Milestone" 9 t nil milestone nil)
              ("State" 6 t nil state nil)
              ("Updated" 10 t nill updated nil)
              ))
```

**Comment by seagle0128** [comment]
I enhanced the configuration of `forge` in Centaur, but the format is a little bit different.

**Comment by atanasj** [comment]
Great, I'll check it out. I tried to add `labels` in there too, but could get it to work because I think the `label` value is a list.

**Comment by atanasj** [comment]
Works great, thanks.

**Comment by seagle0128** [comment]
@atanasj I think it's better inquiry to `forge` community. Did you try this? Just put it to `custom-post.el`

```elisp
(with-eval-after-load 'forge
  (setq forge-topic-list-columns
      '(("#" 5 t (:right-align t) number nil)
        ("Title" 60 t nil title  nil)
        ("State" 6 t nil state nil)
        ("Marks" 8 t nil marks nil)
        ("Labels" 8 t nil labels nil)
        ("Assignees" 10 t nil assignees nil)
        ("Updated" 10 t nill updated nil)))
)
```

**Comment by atanasj** [comment]
Yes I did. However those other values produce an error message that populates each cell of the tabulated list. I think you're right, I'll chase it up on the `forge` repo. Thanks again.
