### ISSUE TITLE
How do I add my own keywords to the TODO highlights in magit status buffer?

### ISSUE THREAD

**Issue by atanasj** [seagle0128/.emacs.d#183]
I have some keywords that I've added to `hl-todo` and would like them to come up in the `magit-status` buffer with `magit-todo`. 

Also, sometimes even a standard work e.g., `TODO` isn't being shown (see screenshot). I don't think this is related to the file being an `.Rmd` format… Can you please give me some advice about how to configure this? 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27214625/76031359-aade2700-5f8b-11ea-90e3-4fc85cc261ad.png">

**Comment by seagle0128** [comment]
Check if `hl-todo-include-modes` and `hl-todo-exclude-modes` are what you need.

**Comment by seagle0128** [comment]
Closing it due to the inactivity.
