### ISSUE TITLE
funcall-interactively: Symbol’s value as variable is void: cua--rectangle

### ISSUE THREAD

**Issue by ettomatic** [seagle0128/.emacs.d#184]
Hi,

After updating Centaur and packages when deleting I'm getting this message
```
funcall-interactively: Symbol’s value as variable is void: cua--rectangle
```
Tried disabling my custom-post.el but still seeing the issue.

Any suggestion of what could cause this? Thanks

**Comment by seagle0128** [comment]
This issue is caused by `aggressive-delete`. See https://github.com/nflath/hungry-delete/pull/36.

**Comment by seagle0128** [comment]
Another workaround is `(setq cua--rectangle nil)`.  Just put it in custom.el.

**Comment by seagle0128** [comment]
Close it since the upstream has fixed this issue.
