### ISSUE TITLE
=> becomes small arrow when editing js

### ISSUE THREAD

**Issue by acdoussan** [seagle0128/.emacs.d#185]
Hi there

When editing javascript, an arrow functions arrow turns into a really small almost invisible arrow after the cursor moves past it. I've tried playing around with fonts and stuff to stop this to no avail. How do I disable this?

[What I want](https://i.gyazo.com/b004a21e6643ce25743eef30c305fe54.png)

[What I see when I move my cursor](https://i.gyazo.com/18d1eabb50d1d6f97dce8578a7dd6cf9.png)

**Comment by seagle0128** [comment]
Disable `prettify-symbols-mode` in `js-mode` or `(setq centaur-prettify-symbols-alist nil)`.

**Comment by acdoussan** [comment]
I tried uncommenting `(setq centaur-prettify-symbols-alist nil)`, removing the value from `prettify-symbols-alist`, and disabling `global-prettify-symbols-mode` and `prettify-symbols-mode`, none of which made a difference. Any ideas as to why that might be?

As a side question, I really like the file browser [this](https://user-images.githubusercontent.com/140797/56474931-8bddc000-64b3-11e9-93d8-0204c3752790.png) picture from the readme, would you mind sharing what that is? Does that come by default? Is there a list of installed packages somewhere? Might stem some of these questions. I'm moving from spacemacs and don't think I can go back now, this config is pretty sweet!

**Comment by seagle0128** [comment]
I believe it does work. Please check the value of `prettify-symbols-alist` and `centaur-prettify-symbols-alist` in the buffer.

The file browser is `treemacs` which is default in Centaur (`<f8>`).
