### ISSUE TITLE
How to disable the pinned parenthesis after moving

### ISSUE THREAD

**Issue by jkunlin** [seagle0128/.emacs.d#186]
When the cursor is on one side of the parenthesis, another side of the parenthesis (out of the screen)  appears and pinned on the screen. 
This is a nice feature, but it does not disappear when I move the cursor away from the parenthesis. In this case, the pinned parenthesis is annoyed since it covers the source code.

**Comment by seagle0128** [comment]
`(advice-remove #'show-paren-function #'show-paren-off-screen)`

**Comment by jkunlin** [comment]
After disabling the evil mode, I found that the showing of the matching line is triggered by the position `after` the parenthesis. That is said,  if the cursor is on the parenthesis, the matching line will not show.

**Comment by seagle0128** [comment]
Right. I am not using `evil`, so perhaps it's not compatible with it. You can improve it yourself.
