### ISSUE TITLE
When I press C-v, the page will skip a few lines

### ISSUE THREAD

**Issue by morole** [seagle0128/.emacs.d#188]
When I press C-v, the page will skip a few lines,
The binding is pager-page-down, and the shortcut key (global-set-key (kbd "C-v") 'scroll-up-command) is modified at the end of init.el, which has no effect

**Comment by seagle0128** [comment]
```elisp
(global-unset-key [remap scroll-up-command])
(global-unset-key [remap scroll-down-command])
```

**Comment by morole** [comment]
Thank you!
