### ISSUE TITLE
在magit-status界面，执行c-c提交比较大型项目时，执行很长时间才打开输入提交内容的界面

### ISSUE THREAD

**Issue by cxb811201** [seagle0128/.emacs.d#189]
如题

使用doom-emacs时，相同项目，相同操作，很快就打开提示输出提交内容的界面

**Comment by cxb811201** [comment]
这个是执行magit-todo引起的

**Comment by seagle0128** [comment]
你安装ripgrep了吗？

**Comment by cxb811201** [comment]
安装了，magit-todos默认使用就是ripgrep

**Comment by seagle0128** [comment]
建议你做个 profiling，如果确定配置正确仍然很慢，可以给`magit-todos`提个 issue。本地可以暂时禁止`magit-todos-mode`.
