### ISSUE TITLE
M-3 不能解绑定问题

### ISSUE THREAD

**Issue by zgj224** [seagle0128/.emacs.d#19]
想把M-3解绑用作别的键
(global-set-key (kbd "\M-3") nil)  
(global-unset-key (kbd "\M-3")) 
(global-set-key (kbd "M-3") 'grep-find) 
这样操作后无效，报错：No window numbered 3
这是为什么吗？

**Comment by seagle0128** [comment]
Try 
```elisp
(window-numbering-mode -1)
(global-set-key (kbd "M-3") 'grep-find)
```
