### ISSUE TITLE
在编辑scala文件时，在代码中最后列输入空格时，会自动把这个空格删除

### ISSUE THREAD

**Issue by cxb811201** [seagle0128/.emacs.d#191]
如：先输入def后空格，这时会将我输入的空格删除
在编辑emacs-lisp或go时不存在这个问题

![Screen-Recording-2020-03-25-at-00 35 56 (1) (1)](https://user-images.githubusercontent.com/2104470/77455632-0f76fe00-6e35-11ea-9c49-6918d9085542.gif)

**Comment by seagle0128** [comment]
Please test.
