### ISSUE TITLE
在使用use-package的:load-path加载emacs-rime时，无法激活，只能通过require方法

### ISSUE THREAD

**Issue by cxb811201** [seagle0128/.emacs.d#192]
无效配置如下
(use-package rime
  :load-path "site-lisp/emacs-rime"
  :custom
  (rime-librime-root "~/.emacs.d/librime/dist")
  (default-input-method "rime"))

有效配置如下：
(eval-and-compile
  (setq rime-librime-root "~/.emacs.d/librime/dist"
        rime-show-candidate 'posframe
        default-input-method "rime"))

(eval-when-compile
  (require 'rime))

以上配置都是放在custom-post.el中

**Comment by seagle0128** [comment]
```elisp
(use-package rime
:demand
:load-path "site-lisp/emacs-rime"
:custom
  (rime-librime-root "~/.emacs.d/librime/dist")
  (default-input-method "rime"))
```
