### ISSUE TITLE
icon error:Unable to find icon with name ‘chevron-:v-adjust’ in icon set ‘octicon’

### ISSUE THREAD

**Issue by eitazhou** [seagle0128/.emacs.d#193]
I use mac ,and I run the command `M-x all-the-icons-install-fonts` manually.after that I restart emacs ,all are ok ,include the dashboard. but when I start open file `C-x C-f`，ivy seems load error:

> Error in post-command-hook (ivy--queue-exhibit): (error "Unable to find icon with name ‘chevron-:v-adjust’ in icon set ‘octicon’")

and the ivy can't work well , include fuzzy search. when I disable centaur-icon , all iis ok .of course, just can't load icon.

**Comment by seagle0128** [comment]
Did you upgrade `all-the-icons` and `all-the-icons-ivy-rich` to the latest version? Please check it.

**Comment by on99** [comment]
I encounter the same issue here after I just upgrade everything by hitting `U`

**Comment by on99** [comment]
```
ivy-rich is a dependency package.

     Status: Installed in ‘ivy-rich-20200322.1326/’ (unsigned).
    Version: 20200322.1326
     Commit: 596874d1469667f896b83731914d7d4456025553
    Summary: More friendly display transformer for ivy.
   Requires: emacs-24.5, ivy-0.8.0
Required by: all-the-icons-ivy-rich-20200324.550
   Keywords: ivy 
Other versions: 20200322.1326 (melpa).

[back]
```

```
all-the-icons is a dependency package.

     Status: Installed in ‘all-the-icons-20200326.208/’ (unsigned).
    Version: 20200326.208
    Summary: A library for inserting Developer icons
   Requires: emacs-24.3, memoize-1.0.1
Required by: doom-modeline-20200322.636, all-the-icons-ivy-rich-20200324.550, all-the-icons-ibuffer-20200319.1625, all-the-icons-dired-20200317.2133
   Homepage: https://github.com/domtronn/all-the-icons.el
   Keywords: convenient lisp 
Other versions: 20200326.208 (melpa).

[back]
```

Both of the packages you mentioned are the latest version.

**Comment by eitazhou** [comment]
M-x centaur-update-all  and restart , same error.  ‘all-the-icons-ivy-rich-20200324.550' ,I think it is the latest version

**Comment by on99** [comment]
I've tried to capture some error log by `toggle-debug-on-error`, however, there is nothing useful in the Message.

```
Debug on Error enabled globally
Error in post-command-hook (ivy--queue-exhibit): (error "Unable to find icon with name ‘chevron-:v-adjust’ in icon set ‘octicon’")
```

**Comment by seagle0128** [comment]
According to the error message, it seems you loaded the old version of `all-the-icons`. In recent changes, `all-the-icons-icon-for-dir` was changed, and `all-the-icons-icon-for-dir-with-chevron` was added. Please confirm you are loading the latest `all-the-icons`.

**Comment by eitazhou** [comment]
sorry, deleting 4 packages about all-the-icon then restart , same error.  even M-x all-the-icons-install-fonts manually can't work

**Comment by seagle0128** [comment]
Can you evaluate this snippet in your env?

```elisp
(toggle-debug-on-error)
(all-the-icons-icon-for-dir "~/" :v-adjust 0.0)
```

**Comment by eitazhou** [comment]
Debugger entered--Lisp error: (error "Unable to find icon with name ‘chevron-:v-adjust’ in icon set ‘octicon’")
  signal(error ("Unable to find icon with name ‘chevron-:v-adjust’ in icon set ‘octicon’"))
  error("Unable to find icon with name `chevron-:v-adjust' in icon set `octicon'")
  all-the-icons-octicon("chevron-:v-adjust" :height 0.8 :v-adjust -0.1)
  (if chevron (all-the-icons-octicon (format "chevron-%s" chevron) :height 0.8 :v-adjust -0.1) "")
  (let* ((matcher (all-the-icons-match-to-alist (file-name-base (directory-file-name dir)) all-the-icons-dir-icon-alist)) (path (expand-file-name dir)) (chevron (if chevron (all-the-icons-octicon (format "chevron-%s" chevron) :height 0.8 :v-adjust -0.1) "")) (padding (or padding "\011")) (icon (cond ((file-symlink-p path) (all-the-icons-octicon "file-symlink-directory" :height 1.0 :v-adjust 0.0)) ((all-the-icons-dir-is-submodule path) (all-the-icons-octicon "file-submodule" :height 1.0 :v-adjust 0.0)) ((file-exists-p (format "%s/.git" path)) (format "%s" (all-the-icons-octicon "repo" :height 1.1 :v-adjust 0.0))) (t (apply (car matcher) (list (car ...) :v-adjust 0.0)))))) (format "%s%s%s%s%s" padding chevron padding icon padding))
  my-all-the-icons-icon-for-dir("~/" :v-adjust 0.0)
  apply(my-all-the-icons-icon-for-dir ("~/" :v-adjust 0.0))
  all-the-icons-icon-for-dir("~/" :v-adjust 0.0)
  eval((all-the-icons-icon-for-dir "~/" :v-adjust 0.0))
  eshell-exec-lisp(eshell-print eshell-error (all-the-icons-icon-for-dir "~/" :v-adjust 0.0) nil t)
  eshell-lisp-command((all-the-icons-icon-for-dir "~/" :v-adjust 0.0))
  eval((eshell-lisp-command (quote (all-the-icons-icon-for-dir "~/" :v-adjust 0.0))))
  eshell-do-eval((eshell-lisp-command (quote (all-the-icons-icon-for-dir "~/" :v-adjust 0.0))) nil)
  eshell-do-eval((prog1 (eshell-lisp-command (quote (all-the-icons-icon-for-dir "~/" :v-adjust 0.0))) (run-hooks (quote eshell-this-command-hook))) nil)
  (condition-case err (eshell-do-eval (quote (prog1 (eshell-lisp-command (quote (all-the-icons-icon-for-dir "~/" :v-adjust 0.0))) (run-hooks (quote eshell-this-command-hook)))) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (error-message-string err)) (eshell-close-handles 1)))
  eval((condition-case err (eshell-do-eval (quote (prog1 (eshell-lisp-command (quote (all-the-icons-icon-for-dir "~/" :v-adjust 0.0))) (run-hooks (quote eshell-this-command-hook)))) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (error-message-string err)) (eshell-close-handles 1))))
  eshell-do-eval((condition-case err (eshell-do-eval (quote (prog1 (eshell-lisp-command (quote (all-the-icons-icon-for-dir "~/" :v-adjust 0.0))) (run-hooks (quote eshell-this-command-hook)))) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (error-message-string err)) (eshell-close-handles 1))) nil)
  (let ((eshell-this-command-hook (quote (ignore)))) (eshell-do-eval (quote (condition-case err (eshell-do-eval (quote (prog1 (eshell-lisp-command ...) (run-hooks ...))) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (error-message-string err)) (eshell-close-handles 1)))) nil))
  eval((let ((eshell-this-command-hook (quote (ignore)))) (eshell-do-eval (quote (condition-case err (eshell-do-eval (quote (prog1 ... ...)) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (error-message-string err)) (eshell-close-handles 1)))) nil)))
  eshell-do-eval((let ((eshell-this-command-hook (quote (ignore)))) (eshell-do-eval (quote (condition-case err (eshell-do-eval (quote (prog1 ... ...)) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (error-message-string err)) (eshell-close-handles 1)))) nil)) nil)
  eshell-do-eval((progn (let ((eshell-this-command-hook (quote (ignore)))) (eshell-do-eval (quote (condition-case err (eshell-do-eval (quote ...) nil) ((debug error) (run-hooks ...) (eshell-errorn ...) (eshell-close-handles 1)))) nil))) nil)
  (catch (quote top-level) (eshell-do-eval (quote (progn (let ((eshell-this-command-hook (quote ...))) (eshell-do-eval (quote (condition-case err ... ...)) nil)))) nil))
  eval((catch (quote top-level) (eshell-do-eval (quote (progn (let ((eshell-this-command-hook ...)) (eshell-do-eval (quote ...) nil)))) nil)))
  eshell-do-eval((catch (quote top-level) (eshell-do-eval (quote (progn (let ((eshell-this-command-hook ...)) (eshell-do-eval (quote ...) nil)))) nil)) nil)
  eshell-do-eval((progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote (progn (let (...) (eshell-do-eval ... nil)))) nil)) (run-hooks (quote eshell-post-command-hook))) nil)
  (let ((eshell-current-handles (quote [nil (t . 1) (t . 1)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote (progn ...)) nil)) (run-hooks (quote eshell-post-command-hook)))) nil))
  eval((let ((eshell-current-handles (quote [nil (t . 1) (t . 1)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote ...) nil)) (run-hooks (quote eshell-post-command-hook)))) nil)))
  eshell-do-eval((let ((eshell-current-handles (quote [nil (t . 1) (t . 1)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote ...) nil)) (run-hooks (quote eshell-post-command-hook)))) nil)))
  eshell-resume-eval()
  eshell-eval-command((let ((eshell-current-handles (quote [nil (t . 1) (t . 1)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote ...) nil)) (run-hooks (quote eshell-post-command-hook)))) nil)) "(all-the-icons-icon-for-dir \"~/\" :v-adjust 0.0)")
  eshell-send-input(nil)
  funcall-interactively(eshell-send-input nil)
  call-interactively(eshell-send-input nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x400ae66f>)(eshell-send-input nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x400ae66f>) eshell-send-input)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x400ae66f>) eshell-send-input)
  command-execute(eshell-send-input)

**Comment by seagle0128** [comment]
Did you update the configurations? The latest version is 973e90254763ddb6cffe2ec47bbe5bd64280815a.

There is no `my-all-the-icons-icon-for-dir` now.

**Comment by eitazhou** [comment]
THX! It works after `git pull` .  M-x centaur-update-all  is not enough ?

**Comment by seagle0128** [comment]
Basically `centaur-update-all` is enough since it also calls `git pull`. But git commands may fail, so you need to check the messages.

**Comment by eitazhou** [comment]
That is. I changed sth. in  lisp/init-ui.el , so `git pull` can't work util I commit my change by `git add`.   THX anyway :-)
