### ISSUE TITLE
Use eglot-ensure for starting eglot in org-edit-special buffers

### ISSUE THREAD

**Issue by tviti** [seagle0128/.emacs.d#194]
I think it would be more appropriate to use `eglot-ensure` here to activate eglot in the `org-edit-special` buffer, since the `eglot` command really wants to be called interactively, and actually requires a few positional arguments if called non-interactively (i.e. the usage here is incorrect and throws an error if eglot is not already running).

https://github.com/seagle0128/.emacs.d/blob/973e90254763ddb6cffe2ec47bbe5bd64280815a/lisp/init-lsp.el#L406

**Comment by seagle0128** [comment]
I am not using `eglot`. Would you please create a PR?

**Comment by seagle0128** [comment]
Please test.

**Comment by tviti** [comment]
I haven't tried the referenced commit, but have been using the following w/ pyls for the past few days with reasonable results:

https://github.com/tviti/.emacs.d/commit/06ddb8a44cb62924c3524285bc0d49b102ae5731

I've made a few other changes here, one of which is switching to `eglot-ensure`. Completion works, but flymake and rename do not (these problems might be beyond the scope of this issue ticket though).

**Comment by seagle0128** [comment]
flymake is disabled by default. You need to enable it manually. I am using flycheck. Regarding the renaming, it should be supported on server side.

**Comment by tviti** [comment]
Sorry, I should have specified that I'm not actually using Centaur, and that the linked commit is just me taking that macro and adapting it to my own config (where I do use flymake).

Renaming is indeed supported in pyls, but the language server throws an error when trying to do the rename. Like I said, I haven't tried with other backends, so idk yet if this is just a problem w/ pyls.

I'm curious: Does flycheck+lsp-mode work for you?

**Comment by seagle0128** [comment]
I am not using pyls. Check lsp-python-ms. Flychekc+ lsp-mode works well for me.
