### ISSUE TITLE
Warning (emacs): Replace (require ’lsp) with (require ’lsp-mode)

### ISSUE THREAD

**Issue by on99** [seagle0128/.emacs.d#195]
After upgrade by hitting `U` in dashboard, the warning message window pops out every time I open emacs, not sure what is wrong.

I almost do not customize anything, but using centaur defaults.

**Comment by seagle0128** [comment]
That's a warning from `lsp-mode`. To remove it, all downstream packages should be updated. You should file issues for them (e.g. ccls, dap-mode, etc.) and/or wait for fixes. We can do nothing here, just ignore it.

**Comment by on99** [comment]
Thanks for your reply, so I'd just wait.
