### ISSUE TITLE
dim doom-mode-line when emacs is not in focus or un-used

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#196]
I have used doom-mode-line before using centaur configuration.
Usually I have 2 monitors with emacs on one monitor and browser on the other. 
I used to use [dimmer package](https://github.com/gonewest818/dimmer.el) earlier which use to dim emacs including mode-line when I am not using it.

```emacs-lisp
(use-package dimmer
  :custom
  (dimmer-fraction 0.2)
  :init
  (dimmer-mode t))
```
And this is working for centaur configuration too. 
I wanted to check if is there a configuration to dim doom-mode-line when emacs is not in focus or us-used?

**Comment by seagle0128** [comment]
I don't understand completely. the `doom-modeline` is only active in the current window, others are inactive. That's what you want? Or you should file a feature request to `dimmer`.

**Comment by CsBigDataHub** [comment]
Sure will do that..Thanks
