### ISSUE TITLE
doom modeline seems not work && how to set go project when use eglot

### ISSUE THREAD

**Issue by 404cn** [seagle0128/.emacs.d#197]
# Doom modeline

look likes this.

<img width="1439" alt="Screen Shot 2020-03-29 at 9 15 38 AM" src="https://user-images.githubusercontent.com/24653356/77837646-150a7600-719e-11ea-9f59-653dffe2fb9a.png">

Try to centaur-update-all but it did not work.

# eglot

I try to switch lsp client to eglot but when I open go file.

>  [eglot] Server reports (type=2): You are neither in a module nor in your GOPATH.

I already set go mod in my project.(lsp-mode works fine, but it's really slow).

**Comment by seagle0128** [comment]
Please enable toggle-debug-on-error, and provide backtraces.

**Comment by 404cn** [comment]
When open go file.

<img width="1439" alt="Screen Shot 2020-03-29 at 9 15 38 AM" src="https://user-images.githubusercontent.com/24653356/77844618-9f70cb00-71da-11ea-8171-d956620e456f.png">

**Comment by seagle0128** [comment]
1. doom-modeline: Please make sure all configurations and packages are updated to the latest. See https://github.com/seagle0128/doom-modeline/issues/321.
1. eglot: According to the logs, it's an issue of `eglot`. Please file an issue there.

**Comment by seagle0128** [comment]
Updated: You may encounter this issue: https://github.com/jethrokuan/org-roam/issues/367. Also update the configurations to address.
