### ISSUE TITLE
Org mode 中的可显示区域只有前 80 列

### ISSUE THREAD

**Issue by cycoe** [seagle0128/.emacs.d#198]
<img src="https://s1.ax1x.com/2020/04/02/GY1pMF.png" alt="GY1pMF.png" border="0" />

如截图中所示，在 org-mode 中的可显示区域只有前 80 列。超过 80 列宽度的内容要么显示不出来（如截图），要么会被折行

**Comment by seagle0128** [comment]
`virtual-auto-fill-mode`的效果。我调整下吧。
