### ISSUE TITLE
Copy with multiple cursors not working as Intended

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#199]
Lets says you have a text like below

```
hfjhsfdi: hdsfkhfklsdjf
hkhhkkkkk: nfsakhklfsdhh
khsdfkhkfhds: sdfhkjhsdfkh
```
you want to copy every thing upto **:** at a time using multiple-cursors.

- added cursors at the beginning of each line , C-spc, M-f , M-w , return ,C-x r y(in new buffer) (This from https://emacs.stackexchange.com/a/10882)

**result with centaur emacs** -

```
hfjhsfdi
hfjhsfdi: hdsfkhfklsdjf
hkhhkkkkk: nfsakhklfsdhh
khsdfkhkfhds: sdfhkjhsdfkh
hfjhsfdi: hdsfkhfklsdjf
hkhhkkkkk: nfsakhklfsdhh
khsdfkhkfhds: sdfhkjhsdfkh
```

**Intended result** -

```
hfjhsfdi
hkhhkkkkk
khsdfkhkfhds
```

_**I tried it with my old configuration and it works as intended.**_

**Comment by CsBigDataHub** [comment]
@seagle0128 ,

Looks like [smart-region](https://github.com/uk-ar/smart-region) package is the culprit here. I removed it and everything worked as intended.  

I will let you close this issue . so that you can have a work-around or remove the package.

**Comment by seagle0128** [comment]
I think it's as designed by `smart-region`.
