### ISSUE TITLE
Cannot bind server socket: Address already in use 

### ISSUE THREAD

**Issue by zgj224** [seagle0128/.emacs.d#20]
Cannot bind server socket: Address already in use

**Comment by seagle0128** [comment]
I can guess the circumstances: Emacs has already been started. 

Only one copy of Emacs should be started necessarily, then you could use `emacsclient` to open the files quickly. Please check.

**Comment by GeneKao** [comment]
@zgj224 In mac, you can also simply type cmd+n to open new emacs windows.

**Comment by seagle0128** [comment]
Thanks, @GeneKao . It's another option indeed.
