### ISSUE TITLE
Whitespace is trimmed in Markdown mode

### ISSUE THREAD

**Issue by KarthikNayak** [seagle0128/.emacs.d#207]
In markdown it is essential to keep whitespaces at the end of a line. 
But it seems like we're trimming EOL whitespaces even in markdown mode.

**Comment by seagle0128** [comment]
Try: `(remove-hook 'markdown-mode-hook #'enable-trailing-whitespace)`.

**Comment by KarthikNayak** [comment]
Yup this works, shouldn't we add this to the `init-markdown.el`

**Comment by seagle0128** [comment]
I don't understand why the redundant whitespaces at the end is essential for markdown.

**Comment by KarthikNayak** [comment]
Ah, that's because new line is defined by two space characters in Markdown. 
https://www.markdownguide.org/basic-syntax#line-break-best-practices

**Comment by seagle0128** [comment]
>You can use two or more spaces (referred to as “trailing whitespace”) for line breaks in nearly every Markdown application, but it’s **controversial**. It’s hard to see trailing whitespace in an editor, and many people accidentally or intentionally put two spaces after every sentence.

So it’s **controversial**, right?

**Comment by KarthikNayak** [comment]
Yes, you're right. Let's close this!
