### ISSUE TITLE
Is it possible to use the all-the-icons company-mode in other languages and modes

### ISSUE THREAD

**Issue by atanasj** [seagle0128/.emacs.d#208]
I was wondering if your config in `init-company.el` for `company-box-icons-all-the-icons` could be used for other modes? I was hoping it could make `company-mode` for `ess-mode` more fancy. Similar to what the `lsp-mode` config does but without the performance hit.

I.e., this:

![image](https://user-images.githubusercontent.com/27214625/80483703-ded93580-8999-11ea-8bcb-76666e75e411.png)

To this:

![image](https://user-images.githubusercontent.com/27214625/80483818-0d571080-899a-11ea-8c2f-8a83a8a5570f.png)

As per here:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/27214625/80483568-a6d1f280-8999-11ea-9800-277656ba14a1.png">

**Comment by seagle0128** [comment]
If you are using lsp for ess, it should work. Otherwise you need to customize `company-box` yourself. See `my-company-box-icons--elisp`.
