### ISSUE TITLE
disable ivy-prescient-mode when using ebib

### ISSUE THREAD

**Issue by atanasj** [seagle0128/.emacs.d#210]
How can I disable ` ivy-prescient-mode` when using `ebib`. The fuzzy search makes it hard to efficiently search my bib file. When I disable `ivy...`, references options appear more as one would expect. I'm wondering whether the `ivy-prescient-non-fuzzy` function would work, and if it did, not quite sure how to add it... Could you please help?

**Comment by seagle0128** [comment]
See `ivy-re-builders-alist`.

**Comment by atanasj** [comment]
Yes, I saw that but was not too sure how to use it to disable this feature. Could you please tell me how I can I add it to my `custom-post.org` file?

**Comment by seagle0128** [comment]
Just like this:

```elisp
(with-eval-after-load 'ivy-prescient
    (add-to-list 'ivy-re-builders-alist '(ebib . ivy-prescient-non-fuzzy)))
```

or 

```elisp
(setq ivy-re-builders-alist '((t . ivy-prescient-non-funzzy)))
```

or `C-o M` in ivy minibuffer.
