### ISSUE TITLE
The quick start procedure is a bit too invasive

### ISSUE THREAD

**Issue by dgutov** [seagle0128/.emacs.d#212]
I just installed this to try out and see the "enhanced default experience".

The UI is pretty spiffy (I'll take a note to maybe recommend it to people to try out), but the quick start procedure raised an eyebrow. The font installation could use a prompt (`all-the-icons-install-fonts` does prompt by default, unless called with non-nil argument). The sudo password prompt (by `pdf-tools`) wasn't great either.

**Comment by seagle0128** [comment]
which OS and version of Emacs?

**Comment by dgutov** [comment]
GNU/Linux and 27 pretest.

**Comment by seagle0128** [comment]
1. Install fonts: calling `(all-the-icons-install-fonts t)` to install fonts without prompts.
https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-ui.el#L240

1. Install pdf-tools: Calling `(pdf-tools-install t nil t nil)` to avoid prompts. Not sure `sudo` is required by makefiles of `pdf-tools`.
https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-reader.el#L49

Could you please give me advices or suggestion?

**Comment by dgutov** [comment]
1. What about removing the `t` argument?

2. What happens if you don't call it? Does trying to use any of its features result in installation instructions? If so, that seems like it should be enough.

**Comment by seagle0128** [comment]
1. The default configurations depend on `all-the-icons` to display icons on UI. I think it's better to install fonts automatically, without any prompts, especially for new users.
1. Better solution is building pdfinfo if needed. (while opening pdf files)
