### ISSUE TITLE
magit-todos

### ISSUE THREAD

**Issue by atanasj** [seagle0128/.emacs.d#214]
I am experiencing some problematic performance e.g., high cpu, freezing, etc. I think it is related to `magit-todos` as when I disable things seem to be better. 

How do I disable `magit-todos` at login without running `M-x`? 

I've tried:

```elisp
(with-eval-after-load 'magit-todos
    (magit-todos-mode -1))
```
But that doesn't work. What am I doing wrong?

**EDIT**

Actually, disabling `org-roam-mode` seems to help to… Not sure what that's related to…

**Comment by seagle0128** [comment]
Try 
```elisp
(with-eval-after-load 'magit
  (magit-todos-mode -1))
```

**Comment by atanasj** [comment]
Thanks for that, however (although this is a new issue) I think `savehist-mode` may be a culprit in my excessive cpu usage too (see this spacemacs [issue](https://github.com/syl20bnr/spacemacs/issues/9409)). How can I set `savehist-mode` to not autoload?

**Comment by seagle0128** [comment]
Disable `savehist-mode` or set `savehist-additional-variables`.
