### ISSUE TITLE
[Info] Which mode is responsible for imports as shown in the screenshot

### ISSUE THREAD

**Issue by KarthikNayak** [seagle0128/.emacs.d#215]
Which mode/function is responsible for the import suggestion shown in blue in the screenshot?

![2020-05-12-15:56:18_1920x1080_scrot](https://user-images.githubusercontent.com/1786334/81767617-7be9b180-94f6-11ea-8008-a9d5802bf2c3.png)

**Comment by seagle0128** [comment]
Check `lsp-ui` settings in `init-lsp.el`.

**Comment by KarthikNayak** [comment]
Do you think we should add a shortcut for `lsp-ui-sideline-show-code-actions`?

**Comment by seagle0128** [comment]
It's useful to some people in some cases. You can disabled it by yourself if you don't need it.

**Comment by KarthikNayak** [comment]
I'm not talking about disabling it, I'm talking about adding a keyboard shortcut.

**Comment by seagle0128** [comment]
Oh, sorry for the misunderstanding! It's a good idea. Let me think about it.

**Comment by seagle0128** [comment]
Add the action to the lsp-ui-hydra `M-<f6>`.

**Comment by seagle0128** [comment]
Also bind M-RET to lsp-ui-sideline-apply-code-actions.
