### ISSUE TITLE
Lisp nesting exceeds ‘max-lisp-eval-depth’

### ISSUE THREAD

**Issue by zwz** [seagle0128/.emacs.d#216]
Just checked out the latest version.
No config in custom.el.
The *message* buffer says: 
```
Loading ~/.emacs.d/custom.el (source)...done
Set package archives to ‘melpa’
Loading theme ‘doom-one’
Lisp nesting exceeds ‘max-lisp-eval-depth’
```

**Comment by seagle0128** [comment]
More information needed.
Please provide the details as the template. Also use `emacs --debug-init`.

**Comment by zwz** [comment]
With `emacs --debug-init`, it reports in the console
```
2020-05-14 16:06:14.068 Emacs-x86_64-10_10[3652:64278] Failed to initialize color list unarchiver: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: non-keyed archive cannot be decoded by NSKeyedUnarchiver" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: non-keyed archive cannot be decoded by NSKeyedUnarchiver}
```

**Comment by zwz** [comment]
I also tried it on another computer running archlinux (Emacs 26.3).
It reports `max-lisp-eval-depth`, too, but nothing in the console.
While some time ago, there was no such issue.
I guess it was introduced in by some recent commits.

**Comment by zwz** [comment]
I find the issue starts at
```
commit ac851af978615f286e51a57f29eabcdfc3dfcc21
Author: Vincent Zhang <seagle0128@gmail.com>
Date:   Tue May 5 18:16:23 2020 +0800

    Refactor.
```

**Comment by seagle0128** [comment]
The backtrace seems the issue of emacs itself. No idea.

**Comment by zwz** [comment]
Well, the backtrace is from Emacs on macos.
But it has nothing to do with the issue, because after I `git checkout 5cc962576c3cc5c6ab8fed163d8207aa6577879d`(the commit before refactor), the backtrace remains, but the issue is gone.

That is why I think the issue comes from
```
commit ac851af978615f286e51a57f29eabcdfc3dfcc21
Author: Vincent Zhang <seagle0128@gmail.com>
Date:   Tue May 5 18:16:23 2020 +0800

    Refactor.
```
However, it is weird if you cannot reproduce it.

**Comment by seagle0128** [comment]
I couldn't reproduce it. I can do nothing if you don't provide more details.

**Comment by zwz** [comment]
The issue goes away after I removed the whole `.emacs.d` and re-cloned it.
