### ISSUE TITLE
unable to automatically installing js language server

### ISSUE THREAD

**Issue by phisu** [seagle0128/.emacs.d#217]
i just installed the latest centauer emacs.d. when i open a js file, i get the message:

Unable to find installed server supporting this file. The following servers could be installed automatically: 
ts-ls
jsts-ls

i choose jsts-ls and i get the following error message:

Error running timer: (wrong-type-argument plistp ivy-completing-read)

what is wrong? what can i do to install the js language server?

**Comment by seagle0128** [comment]
Please update your ivy package to the latest.

See https://github.com/abo-abo/swiper/issues/2568
