### ISSUE TITLE
如何正常使用 Org-roam？

### ISSUE THREAD

**Issue by yibie** [seagle0128/.emacs.d#219]
每次 M-x org-roam，只是显示了一个侧边栏的窗口。

效果远远不如官网所演示的，一个窗口显示笔记文件和标题（调用deft），一个窗口显示backlink，一个窗口是编辑区。

请问 seagle0128 你自己使用的时候是怎么样的呢？

**Comment by seagle0128** [comment]
不是很清楚你的意思。我使用跟这个效果差不多：

https://github.com/org-roam/org-roam/blob/master/doc/images/org-roam-graph.gif

**Comment by yibie** [comment]
![企业微信20200524110542](https://user-images.githubusercontent.com/365484/82757449-245f1600-9e13-11ea-93f5-09fb39f7dbf6.png)

**Comment by seagle0128** [comment]
请阅读org-roam的手册。
