### ISSUE TITLE
不知为何minibar的显示失效了

### ISSUE THREAD

**Issue by yibie** [seagle0128/.emacs.d#220]
启动Emacs，会出现如下信息：

custom-initialize-reset: peculiar error: "UNIQUE constraint failed: files.file"
user-error: Minibuffer window is not active

**Comment by seagle0128** [comment]
See https://github.com/org-roam/org-roam/issues/739.

Delete ~/org/org-roam.db and restart.

**Comment by seagle0128** [comment]
Fixed in upstream.
