### ISSUE TITLE
Org mode 插入链接时相对路径出错

### ISSUE THREAD

**Issue by cycoe** [seagle0128/.emacs.d#221]
我的目录结构为
```bash
.
├── mind
│   ├── a.jpg
│   └── b.jpg
└── mind.org
```
编辑 `mind.org` 时想通过 `org-insert-link` 插入 `a.jpg` ，正确的链接应为 `[[file://mind/a.jpg]]` ，实际得到的为 `[[file://a.jpg]]` ，并且发现文件的 `default-directory` 变量在插入链接后被修改为了 `./mind/`，禁用 `ivy-mode` 后正常

**Comment by seagle0128** [comment]
我发现是`ivy-prescient`的bug。

**Comment by cycoe** [comment]
> 我发现是`ivy-prescient`的问题，禁用它就好了。
> 
> See [raxod502/prescient.el#61](https://github.com/raxod502/prescient.el/issues/61)

非常感谢，终于能继续愉快地使用 Org mode 了

**Comment by seagle0128** [comment]
@cycoe 你能测试下现在还有这个问题吗？在我的环境中已经正常了。

**Comment by cycoe** [comment]
> @cycoe 你能测试下现在还有这个问题吗？在我的环境中已经正常了。

问题已经修复
