### ISSUE TITLE
After upgrading the packages, the emacs get the error when restart.

### ISSUE THREAD

**Issue by WindWang2** [seagle0128/.emacs.d#222]
The hint: Symbol's function definition is void: `treemacs-unless-let`.

**Comment by seagle0128** [comment]
https://github.com/Alexander-Miller/treemacs/issues/682

**Comment by WindWang2** [comment]
Thanks, it seems that the package in melpa was not the latest.

**Comment by seagle0128** [comment]
It has been updated in melpa, but not in mirrors.
