### ISSUE TITLE
swiper-isearch-backward搜索结果按行号排序

### ISSUE THREAD

**Issue by johncming** [seagle0128/.emacs.d#223]
目前感觉没有顺序，像是最近使用的排在前面，其实按行号排序更自然。

**Comment by seagle0128** [comment]
不明白具体意思。

**Comment by johncming** [comment]
![image](https://user-images.githubusercontent.com/11719334/84098375-a5d0be00-aa39-11ea-80d1-5a10ceda5833.png)
搜索出来的结果，行号没有排序

**Comment by seagle0128** [comment]
1. 你说使用swiper-isearch-backward，但是图上是rg。
1. 自行添加的配置，需要修改ivy-re-builders-alist，或者关闭prescient-mode。
