### ISSUE TITLE
ubuntu 18.4 Terminal 有几个问题请教下

### ISSUE THREAD

**Issue by semgilo** [seagle0128/.emacs.d#224]
使用的是emacs 16.3版本
问题一：编辑后怎么撤消（updo）操作
问题二：ivy默认好像是没有的启
顺便问下 这种模式下需要注意什么

**Comment by seagle0128** [comment]
1. 应该是26.3？
1. undo：`C-/` `C-_`, `M-x undo`, `C-x u`.
1. `ivy-mode`默认是启用的。请先阅读https://oremacs.com/swiper/。
