### ISSUE TITLE
查看文件的名字匹配算法总是不太如意

### ISSUE THREAD

**Issue by semgilo** [seagle0128/.emacs.d#225]
![image](https://user-images.githubusercontent.com/7121873/84337052-42769580-abcb-11ea-9295-11626022de02.png)
如图所示，我经常打了全名字但我想要的经常是在下面不是在第一个，这个不知道可不可以优化下，最近使用您的配置感觉很不错。大佬厉害了，之前使用purcell的，它的匹配规则就会让想要的在第一个

**Comment by seagle0128** [comment]
Try disabling `ivy-prescient-mode`.

**Comment by semgilo** [comment]
ivy-prescient-mode
