### ISSUE TITLE
modern mode line not worked when call xref

### ISSUE THREAD

**Issue by johncming** [seagle0128/.emacs.d#227]
![image](https://user-images.githubusercontent.com/11719334/86119296-c48c1700-bb04-11ea-8c7e-f319d70ac695.png)

**Comment by seagle0128** [comment]
I believe it's related to `ivy-hydra` (actually is `lv`).

**Comment by seagle0128** [comment]
Fixed by https://github.com/seagle0128/doom-modeline/commit/a921eeba1e2da05ff962e637ac98a9b5fd0fa727.
