### ISSUE TITLE
call to (require 'some-config.el) does not work

### ISSUE THREAD

**Issue by atanasj** [seagle0128/.emacs.d#229]
I'm in the process of moving configuration from my `custom-post.org` file out to individual `some-config.el` type files. I have tried calling it both from the 'custom-post.org` and the `init.el` files. It works in the latter but not the former. 

I would rather not mess with what you have done in the `init.el` (and once things are working may submit a pull request for certain config, such as my `ess` config i.e., #144).

How can I get these files loaded via the `custom-post.org` file?

**Comment by seagle0128** [comment]
You need `custom.el`.

**Comment by atanasj** [comment]
Thanks for that. Where exactly should I put it in the file? Seems to error when I just put it in the middle of the `custom.el` file.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/27214625/86523179-070a7680-beac-11ea-8b8c-1903e8ed3ee3.png">

**Comment by seagle0128** [comment]
Try with-eval-after-load.

**Comment by atanasj** [comment]
That worked... Thanks!

**Comment by atanasj** [comment]
I thought I had this working but not so! Not sure what I did to get it working or what I have done to make it stop. 

This is what I have in my `custom.el` file:

```elisp
(with-eval-after-load 'init-evil)
(with-eval-after-load 'init-ess)
```
This is my folder structure where the files are stored:

```bash
├── README.md
├── init-ess.el
├── init-evil.el
└── pandoc-mode
    ├── default.pandoc
    ├── markdown.pandoc
    ├── md.pandoc
    └── native.pandoc
```

However, this does not load the relevant configuration documented in those files ([see repo with files here if that helps](https://github.com/atanasj/centaur-site-lisp)), but when I evaluate the above `init-*` files, everything works as expected. Any idea what could be going wrong?

**Comment by seagle0128** [comment]
I am confused what are you doing. if you just want to load the config files, add `(require 'init-xxx)` to `inti.el`. If you want to add some configs, put these into `custom.el`. 
```elisp
(with-eval-after-load 'init-evil
  (xxxx)
  (xxxx)
)
```

**Comment by atanasj** [comment]
Yes, all I want to do is add the config files, and when I add themm to the `init.el` they work as expected. Just wasn't sure this was the right spot for them or not as I didn't want them to be overwritten during an update. 

It all works as expected then… Thanks! :-)

**Comment by seagle0128** [comment]
IMO, this may work for you.
```elisp
(with-eval-after-load 'use-package
  (require 'init-evil)
)
```

**Comment by atanasj** [comment]
Do you think that is preferable to appending to the `init.el`?

**Comment by seagle0128** [comment]
If you are preparing the PR, I prefer `inti.el`. The only concern is for `init-evil.el`. I don't want to make it as default or option in Centaur, since I am not using `evil` and no promise to support it.

**Comment by atanasj** [comment]
No, of course not. I'll experiment and well all good to go I'll make a pull request on the `ess` configuration. Cheers.

**Comment by atanasj** [comment]
Would you then recommend removing the `evil` bindings from the `initi-ess.el` file and just keep all `evil` config separate?

**Comment by seagle0128** [comment]
> Would you then recommend removing the evil bindings from the initi-ess.el file and just keep all evil config separate?

Yes, please.

**Comment by atanasj** [comment]
> > Would you then recommend removing the evil bindings from the initi-ess.el file and just keep all evil config separate?

> Yes, please.

Okay, will do.
