### ISSUE TITLE
Update to .zsh and config breaks

### ISSUE THREAD

**Issue by atanasj** [seagle0128/.emacs.d#230]
This is something I'm missing her, but I'm wanting to change from `bash` to `zsh`, however my config breaks. For example, `lsp-r` no longer works. Also, `treemacs` cannot find `python`. I have copied all my paths from by `.bash_profile` to my `.zshrc`... Any ideas?

**Comment by seagle0128** [comment]
I guess you should put something (like `PATH`) to `.zshenv` or `.zsh_profile`. `.bash_profile` is not equal to `.zshrc`.

**Comment by atanasj** [comment]
Thanks… Where do I put that? Sorry to ask, but you seem to know… lol

**Comment by atanasj** [comment]
All good, I figured it out. Thanks again for all your help!! :-)
