### ISSUE TITLE
Chinese Input Method Layer support

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [seagle0128/.emacs.d#235]
Currently, in Linux, the emacs must be executed by
```
$ LC_CTYPE=zh_CN.UTF-8 emacs
```
Then the Chinese input method works. 
(Manjaro Linux + fcitx with google-pinyin, and the short-cut is `Super + Space`)

I saw that Spacemacs already integrates fcitx in its layer.

So could Centaur Emacs support fcitx too?

**Comment by seagle0128** [comment]
It's should be the configuration of os env, while not Emacs.
