### ISSUE TITLE
`C-x o` can not switch window to treemacs sidebar 

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [seagle0128/.emacs.d#237]
Maybe it's a silly question, but when I use `C-x o`, I can't switch from window to the treemacs sidebar.

The cursor only jumps between the buffer windows, So how can I jump to the treemacs sidebar by using shortcut.

Thanks in advance

**Comment by jidibinlin** [comment]
@ZhengshuaiPENG I have the same problems. How you solved it

**Comment by seagle0128** [comment]
It's as designed. Use `M-0` to jump to treemacs.

**Comment by ZhengshuaiPENG** [comment]
> @ZhengshuaiPENG I have the same problems. How you solved it

I read the `.emacs.d/lisp/init-treemacs.el`, and I found the keybindings there
