### ISSUE TITLE
FYI emacs-solaire-mode issues after upgrading to Emacs 27.1

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#244]
An issue has been created in the repo -  hlissner/emacs-solaire-mode#35

This work around worked for me - https://github.com/hlissner/emacs-solaire-mode/issues/35#issuecomment-663107645

Apart from that inactive buffer in the split window is not dimmed.

Just wanted to let you know.

**Comment by seagle0128** [comment]
Thanks for letting me know!

**Comment by andreyorst** [comment]
> I suspect it's related to hlissner/emacs-solaire-mode@5baf494.
can confirm that reverting to commit that is previous to `5baf494` fixes the issue.

**Comment by seagle0128** [comment]
This workaround should fix the issue: `(setq solaire-mode-auto-swap-bg t)`.
