### ISSUE TITLE
package cl is deprecated

### ISSUE THREAD

**Issue by penn201500** [seagle0128/.emacs.d#247]
new installed .emacs.d and emacs-27.1, mac osx 14.6; start emacs will get "packge cl is deprecated"

![image](https://user-images.githubusercontent.com/16840448/90229779-0bcb2e80-de4b-11ea-9944-9ae8b74d3efc.png)

step:
1. cd ~/.emacs.d/elpa
2. rg "require 'cl\)" . 
this will display many  .el files (require 'cl)

then,  add "(setq byte-compile-warnings '(cl-functions))" to init.el ; warning disappear. It's solved or just suppressed?

**Comment by seagle0128** [comment]
It just suppresses the warnings. It should be addressed in the upstreams.
