### ISSUE TITLE
Error (use-package): Failed to install psvn: Package ‘psvn-’ is unavailable

### ISSUE THREAD

**Issue by aircjm** [seagle0128/.emacs.d#25]
![image](https://user-images.githubusercontent.com/18283183/41282342-6a1e37a4-6e66-11e8-92a7-b6a337273101.png)

加载完之后报这个error并不影响使用，使用环境是OS X

**Comment by seagle0128** [comment]
Seems `psvn` has been removed form Melpa recently. I deleted it as well. Please update with `M-x update-config` and restart. If you want to use `svn`, you can use `magit-svn` or `dsvn` instead.

**Comment by aircjm** [comment]
非常感谢
