### ISSUE TITLE
pop-shell

### ISSUE THREAD

**Issue by donneyT** [seagle0128/.emacs.d#251]
I have 2 project A and B
open any proA file  then press F9  can toggle shell 
input some command 
press F9 twice  
input will not disappear

next I open proB file  then press F9 can toggle shell too
but input some command press F9 twice
input disappear

next  switch to proA file  working well again
I don`t know why ~

**Comment by donneyT** [comment]
图太大了传不上来 。。。
重新描述一下

就是我先打开一个A项目的文件  这时候按F9  可以开关 并且在shell里的输入 记录 都不会消失
这时候我切到项目B的文件  按F9  还是可以开关 但是窗口会闪烁 并且输入的内容会丢失
重新打开A项目的文件  又会变正常

**Comment by donneyT** [comment]
就是说 你在当前目录下 第一次pop-shell  vtrem 不会执行cd xxxxx
切换文件后 再次pop-shell  每次都会自动执行一次 cd 到当前目录  但其实  只有切换目录后第一次需要执行

**Comment by seagle0128** [comment]
It works for me. If you still have the issue with `shell-pop`, please file an issue there.
