### ISSUE TITLE
如何设置缩进宽度

### ISSUE THREAD

**Issue by chekore** [seagle0128/.emacs.d#26]
请问如何设置缩进宽度,在custom.el中设置(setq default-tab-width 2)并不生效.

**Comment by chekore** [comment]
我是想默认缩进宽度为2, 上面的写法好像还是不生效

**Comment by seagle0128** [comment]
这段配置就是默认设置为2的，但每种语言的mode缩进是单独设置的，需要明确是什么mode。
你需要查下当前buffer里这两个变量的值是多少，另外还有需要查`indent` `level`之类的变量。
```elisp
(setq-default c-basic-offset 2
                    tab-width 2)
```

**Comment by seagle0128** [comment]
Closing it since there is no update so far.
