### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by edwardlin** [seagle0128/.emacs.d#261]
Warning (initialization): An error occurred while loading ‘/home/wymund24/.emacs.d/init.el’:

File error: make client process failed, Connection refused, :name, raw.githubusercontent.com, :buffer, #<killed buffer>, :host, raw.githubusercontent.com, :service, 443, :nowait, nil, :tls-parameters, nil

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

How to solve it?

**Comment by seagle0128** [comment]
Please check your network connection. Or 翻墙。
