### ISSUE TITLE
Autocomplete pop is too narrow.

### ISSUE THREAD

**Issue by d3v-S** [seagle0128/.emacs.d#263]
The autocomplete pop is too narrow to work. It has to be expanded mouse by dragging it. 

![emacs_centaur_aiutocomplete](https://user-images.githubusercontent.com/67001383/95670970-577e2800-0baf-11eb-9680-c80e0a3c3d58.png)

**Comment by seagle0128** [comment]
Please provide details as the template to reproduce the issue.

**Comment by d3v-S** [comment]
1. install centaur emacs
2. bear make in linux-kernel repo
3. create test.c in root of the folder.
4. "hadimba" is a struct in test.c

the autocomplete can be dragged to elongate. The auto-complete options are okay but can not see it.

**Comment by d3v-S** [comment]
updated to 27,1, issue seems to be resolved. 

Now having issues with tabnine, wrong predictions. How can we change the default backend?  multiple "M-q" is hanging emacs.

**Comment by d3v-S** [comment]
solved. Updated to emacs 27.1.
