### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by RohitSingh107** [seagle0128/.emacs.d#264]
How it is different from Doom Emacs ?

**Comment by seagle0128** [comment]
Plese see https://github.com/seagle0128/.emacs.d/blob/master/README.md.

Simply, `Centaur Emacs` is an Emacs distribution that aims to enhance the default Emacs experience. It alters a lot of the default settings, bundles a plethora of additional packages and adds its own core library to the mix. The final product offers an easy to use Emacs configuration for Emacs newcomers and lots of additional power for Emacs power users.

`Doom` has its own framework and more features with many tricks and `evil` keybindings. `Centaur Emacs` is simpler and faster, with vanilla keybindings.
