### ISSUE TITLE
counsel-外部命令出现(wrong-number-of-arguments (1 . 1) 2 )

### ISSUE THREAD

**Issue by jueqingsizhe66** [seagle0128/.emacs.d#266]
出现错误命令:
- counsel-git
- counsel-fzf
- counsel-ag
- counsel-rg
错误debug信息：
`Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  counsel--executable-find("git" t)
  counsel-require-program("git ls-files -z --full-name --")
  counsel-git()
  funcall-interactively(counsel-git)
  #<subr call-interactively>(counsel-git nil nil)
  apply(#<subr call-interactively> counsel-git (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> counsel-git nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (counsel-git nil nil))
  call-interactively(counsel-git nil nil)
  command-execute(counsel-git)
`

`Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  counsel--executable-find("rg" t)
  counsel-require-program(("rg" "-M" "240" "--with-filename" "--no-heading" "--line-number" "--color" "never" "%s" "--path-separator" "/" "."))
  counsel-ag(nil nil nil nil :caller counsel-rg)
  counsel-rg()
  funcall-interactively(counsel-rg)
  #<subr call-interactively>(counsel-rg nil nil)
  apply(#<subr call-interactively> counsel-rg (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> counsel-rg nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (counsel-rg nil nil))
  call-interactively(counsel-rg nil nil)
  command-execute(counsel-rg)
`

采用当前库的init-ivy.el配置rg
`  ;; Use the faster search tool: ripgrep (`rg')
  (when (executable-find "rg")
    (setq counsel-grep-base-command "rg -S --no-heading --line-number --color never %s %s")
    (when (and sys/macp (executable-find "gls"))
      (setq counsel-find-file-occur-use-find nil
            counsel-find-file-occur-cmd
            "gls -a | grep -i -E '%s' | tr '\\n' '\\0' | xargs -0 gls -d --group-directories-first")))
`
暂未找到原因。

**Comment by seagle0128** [comment]
Are you using `Centaur Emacs` without any changes? I cannot reproduce the issue locally.
