### ISSUE TITLE
lsp-mode issue

### ISSUE THREAD

**Issue by on99** [seagle0128/.emacs.d#268]
Fresh centaur emacs.d without any modification/customization on Ubuntu, lsp-mode asks me to select project root everytime when I open a project even if the project root already presents in .lsp-session-v1. Can you please help?

**Comment by seagle0128** [comment]
The prompt should not been popped if you input `i`. 
1. If it's still there, please file an issue for `lsp-mode`.
or 
1. `(setq lsp-auto-guess-root t)`.

**Comment by on99** [comment]
Hi @seagle0128 , I asked for help in [gitter](https://gitter.im/emacs-lsp/lsp-mode?at=5fb9296329cc4d734821d526) and @yyoncho gave me a hand, he thought it's most likely caused by https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-lsp.el#L224. I found this line one code was introduced 4 months before, and IIRC I did not have such issue half a year ago.

I also filed an issue in lsp-treemacs https://github.com/emacs-lsp/lsp-treemacs/issues/79, though I do not really understand why it's related to lsp-treemacs, can you please reopen this issue and help? Thank you!
