### ISSUE TITLE
Weird character on the mode-line

### ISSUE THREAD

**Issue by GeneKao** [seagle0128/.emacs.d#27]
Hi Vincent, is it normal to have this character on the doom mode-line? Thanks. 

<img width="575" alt="doom" src="https://user-images.githubusercontent.com/1162842/42743997-4e372492-88c9-11e8-83bd-33462308ce52.png">

**Comment by GeneKao** [comment]
Ah, never mind. 😄I just found the solution in another repo of yours - [doom-modeline](https://seagle0128.github.io/doom-modeline/). Thanks for the amazing theme!

**Comment by seagle0128** [comment]
Glad to know you like `doom-modeline`!
I think you may miss `M-x all-the-icons-install-fonts`.

**Comment by Griger** [comment]
Hi, I have a similar issue about icons (I use Arch Linux). In my case some icons are shown but other are not.
In addition, in most modes the line is too high. On the other hand, in c++-mode is ok. I show you some images:
![doomlinehigh](https://user-images.githubusercontent.com/7707062/51463857-9b3e5780-1d64-11e9-9692-21185f94d054.jpg)
![doomlinec mode](https://user-images.githubusercontent.com/7707062/51463863-9e394800-1d64-11e9-9376-797a26e4805d.png)
My configuration is:
```(setq doom-modeline-icon t)
(setq doom-modeline-major-mode-icon t)
(setq doom-modeline-major-mode-color-icon t)
(setq doom-modeline-minor-modes nil)
(setq doom-modeline-github nil)```
I have install the fonts with `M-x all-the-icons-install-fonts`, so I don't know how to solve this problem.

Thanks a lot. Regards.

**Comment by Griger** [comment]
Hi @seagle0128, if I disable icons the height is correct. In my case I am using `pretty-mode` and fira-code font ligatures.

**Comment by seagle0128** [comment]
I found this issue https://github.com/seagle0128/doom-modeline/issues/69. Please check pretty-symbol-mode.

**Comment by Griger** [comment]
Ok, I have installed all the fonts by hand in Arch Linux (it seems that is not enough install them by `M-x all-the-icons-install-fonts`). After that, I am going to check if a I can enable `pretty-mode` again.

Do you know what this big icon stands for?
![image](https://user-images.githubusercontent.com/7707062/51474278-08f77d00-1d7f-11e9-820c-4317bf6b5667.png)
Thanks, a lot.

**Comment by seagle0128** [comment]
It's git-branch.

**Comment by Griger** [comment]
Oh, thx. Is there an intuitive way to change it to be smaller? I have found some definitions in the all-the-icons.elc archive, like for example `(messages-buffer-mode all-the-icons-faicon "stack-overflow" :v-adjust -0.1)`. But I want it to be smaller:
![image](https://user-images.githubusercontent.com/7707062/51484347-9e086f00-1d9b-11e9-8096-e2f79bf8ba0e.png)

**Comment by seagle0128** [comment]
Are you using my config? Or yourself? I have no context. It seems the fonts issue as I mentioned, you can ask help for developers of  `all-the-icons`.

**Comment by Griger** [comment]
I am using your config. I am going to ask to the `all-the-icons` developers. Thanks a lot. And thanks for your great module :).

**Comment by seagle0128** [comment]
@Griger OK. May I know your environment details? Like OS, DE/WM, emacs version, etc. I recommend source code pro font. Try it.

**Comment by Griger** [comment]
I use Arch Linux 4.20.3 with KDE Plasma 5.14.5 and Emacs 26.1. I going to check source code pro font. Thx a lot.
