### ISSUE TITLE
中英文输入会卡字符

### ISSUE THREAD

**Issue by lizetong** [seagle0128/.emacs.d#271]
在按Shift切换中英文输入的时候，会出现一种bug现象，需要重启emacs才能解决。
bug：在切换中英文后，会出现，每次按一个按键时会多打一个字母
例如：输入“{”，会输入“H{”
输入“func”，会输入“HfHuHnHc”。

测试了一下不是键盘问题

是用搜狗输入法会出现，使用系统默认输入法也会出现。

**Comment by seagle0128** [comment]
你用的Emacs是28，对吗？试试 27和26.

**Comment by seagle0128** [comment]
确认是Emacs native branch 的问题。
