### ISSUE TITLE
Emacs hangs when trying to enable Two-Column Editing with C-x 6 2

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#275]
Emacs hangs when trying to enable `Two-Column Editing` with `C-x 6 2` and I see `Autoscrolling is on` message in the mini-buffer.

enabling `toggle-debug-on-error` and `toggle-debug-on-quit` did not work either.

Tried `C-g` multiple time, but that does not kill the current process.

Update:

Same functionality is working fine with `emacs -Q --l ~/.emacs.d/init-mini.el`

**Comment by seagle0128** [comment]
I cannot reproduce in my local env. Please provide more details.

**Comment by CsBigDataHub** [comment]
Figured it out, conflict with a package
