### ISSUE TITLE
无法切换中文输入法，该如何设置

### ISSUE THREAD

**Issue by etclub** [seagle0128/.emacs.d#276]
这应该是个question，而不是issue

目前控制台，firefox等应用中都是可以通过Ctrl-SPACE切换输入法的

但是使用`LC_CTYPE=zh_CN.UTF-8 emacs`启动后
Ctrl-SPACE都是在active/deactive mark

然后配置中加入
`(global-unset-key (kbd "C-SPC"))`
Ctrl-SPACE直接提示undefined

**Comment by seagle0128** [comment]
没有明确上下文，无法回答。猜测你这个是Linux系统和输入法本身的问题，请搜索相关的信息。
