### ISSUE TITLE
【解决方法】内地的同学安装时需设置代理 (Solve Chinese mainland users install error)

### ISSUE THREAD

**Issue by NeroSong** [seagle0128/.emacs.d#280]
虽然作者提供了 Customize 功能，但打开如下注释并应用配置后：
```lisp
;; 使用代理
(setq centaur-proxy "127.0.0.1:1080") 
;; 或者换源
(setq centaur-package-archives 'emacs-china)
```
启动初始化依然会出现网络错误：
```bash
File error: make client process failed, Connection refused, 
:name, raw.githubusercontent.com, :buffer, #, 
:host, raw.githubusercontent.com, :service, 443, 
:nowait, nil, :tls-parameters, nil
```
原因在于初始化会访问 github 的素材服务器 `raw.githubusercontent.com`，而这个域名被墙了。
访问该域名下的资源在加载自定义配置之前，所以此时在 custom.el 中的代理无效。

### 解决方法

- 启用系统级全局代理（注意：要设置所有流量都被代理，不单是开个 Http 或者 Socks 代理端口）

或者：

- 在`init.el`开头加入代理配置：
```lisp
(setq url-proxy-services
      '(("http"     . "127.0.0.1:1080")
      ("https"     . "127.0.0.1:1080")))
```

现在重启 Emacs 就能顺利安装了 :)

**Comment by NeroSong** [comment]
最后感谢作者开源如此优秀的配置，照顾了很多细节，用来写笔记和代码真是太好用了 😁👍

**Comment by seagle0128** [comment]
`(setq centaur-proxy "127.0.0.1:1080") ` 只是设置了代理参数，但并没有启用。启用需要用`proxy-http-enable`。
