### ISSUE TITLE
终端下使用 org-mode 无法正常显示

### ISSUE THREAD

**Issue by Clloz** [seagle0128/.emacs.d#281]
我今天刚刚换上centaur这个配置，没有进行过改动。我一般是在终端里面使用 emacs（daemon），使用的时候发现两个问题，一个是在终端的黑色背景下，很多主题的字看不清，最后我换成了 doom-city-lights 这个主题才是比较能正常显示的。另一个就是org文件无法正常显示，有时候进去是空白，C-n 之后能够显示一些行，C-p之后又看不到。

我的 emacs 版本是 27.1，系统是MacOS 10.15.3，终端是iTerm2 和 zsh。使用 GUI 都没有这些问题。

顺便问一下有没有办法在终端中显示图标。

**Comment by seagle0128** [comment]
看看你的iterm配置，我这里正常的

![image](https://user-images.githubusercontent.com/140797/106468914-8101ed00-64d9-11eb-8f38-aa473df4f9ec.png)

**Comment by Clloz** [comment]
能看一下你的 item2 配置吗，我不太清楚是哪个配置的问题，我的字体设置是 cascadia code，非ASCII 字符的字体是 Hack Nerd Font，感谢。

**Comment by seagle0128** [comment]
这个怎么看？还是详细描述下你的配置和重现步骤，最好有log、截图、录屏之类的。

**Comment by Clloz** [comment]
下面第一张图是我从dashboard打开org文件的样子，好像一些dashboard的文字和线还残留在上面，然后随着我按 C-n，org文件的文字开始一行一行的显示，显示比较混乱。
<img width="1680" alt="Screen Shot 2021-02-02 at 20 52 04" src="https://user-images.githubusercontent.com/17775199/106603193-f254a500-6598-11eb-9f6f-b09e8acd6404.png">
<img width="1680" alt="Screen Shot 2021-02-02 at 20 52 25" src="https://user-images.githubusercontent.com/17775199/106603246-06000b80-6599-11eb-82f3-43c3906ca1e5.png">

**Comment by seagle0128** [comment]
这个没法帮你排查，跟配置没有关系。

**Comment by WindWang2** [comment]
我也是这个问题，初步排查，在终端模式下，关闭org-superstar-mode就可以正常显示（当然headline变成了*）。GUI端并无问题。

**Comment by seagle0128** [comment]
所以还是字符集的问题？我可以优化下，在terminal下不打开org-superstar-mode。
