### ISSUE TITLE
ERROR after compling

### ISSUE THREAD

**Issue by Saonnya** [seagle0128/.emacs.d#282]
Error (bytecomp): Loading file .../.emacs.d/elpa/f-20191110.1357/f.elc failed to provide feature ‘f’
During the compling process, twice had it asked me: Buffer " *http mirrors.ustc.edu.cn:443*" has a running process; kill it? (y or n)
Centaur emacs now looks good except there's no dashboard
(I'm using it on windows 10)

Wondering anybody has any idea how to fix it. Thanks very much!!!

**Comment by seagle0128** [comment]
You need to reinstall `f`.
