### ISSUE TITLE
[Help] company-backends conflict in some modes

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#283]
Hi @seagle0128 ,

I have been using [jenkinsfile-mode](https://github.com/john2x/jenkinsfile-mode) and due to `company-backends` conflict `company` was not displaying `company-keywords`  or `company-dabbrev-code`.

I had to `M-:` eval: `(push '(company-keywords company-dabbrev-code) company-backends)` for company to work in `jenkinsfile-mode`

Do you have a better solution for me to get this working? reordering backends perhaps?

**Comment by seagle0128** [comment]
Try this snippet:

```elisp
(add-hook 'jenkinsfile-mode
                   (lambda ()
                          (push '(company-keywords company-dabbrev-code) company-backends)))
```  

But I am curious what value of `company-backends` in jenkinsfile-mode? The default value is 
```elisp
((company-capf :with company-yasnippet)  
(company-dabbrev-code company-keywords company-files) 
company-dabbrev)
```

**Comment by CsBigDataHub** [comment]
Thanks @seagle0128 ,

jenkinsfile-mode just has `company-keywords` .
