### ISSUE TITLE
after update previously binded key does not work anymore

### ISSUE THREAD

**Issue by phisu** [seagle0128/.emacs.d#285]
i have in my custom-post.el

(global-set-key (kbd "C-x g") 'magit-status)

after the last update of centaur-emacs C-x g does not work anymore. the mini-buffer says: C-x g is undefined. what is going wrong?

**Comment by seagle0128** [comment]
Try re-installing `magit` package. It does work well for me.

**Comment by seagle0128** [comment]
It does work well for me. Try re-installing the `magit` package.

**Comment by phisu** [comment]
i set 
(global-set-key (kbd "C-x g") 'magit-status)
as first line in my custom-post.el. this solved my problem.
