### ISSUE TITLE
Was ivy display mode changed? 

### ISSUE THREAD

**Issue by KarthikNayak** [seagle0128/.emacs.d#293]
Hello @seagle0128 

Did we change the way we display the ivy frame?

It's now floating by default. What setting does this come under?

**Comment by KarthikNayak** [comment]
![Screenshot 2021-03-26 at 22 58 09](https://user-images.githubusercontent.com/1786334/112696777-bea24700-8e86-11eb-91d3-ad28b8362a69.png)

Notice the screenshot!

**Comment by seagle0128** [comment]
Yes. The default behavior was changed recently. If you want to change back, just use this setting in `custom.el`.

```elisp
(setq centaur-completion-style 'minibuffer)
```

**Comment by seagle0128** [comment]
Anyway I change the default style back.

**Comment by KarthikNayak** [comment]
Hahah thank you!

**Comment by seagle0128** [comment]
Welcome
