### ISSUE TITLE
Company: frontend company-box-frontend error

### ISSUE THREAD

**Issue by on99** [seagle0128/.emacs.d#294]
After upgrading both centaur emacs distribution and other packages, this issue occurs again, do you have the same issue?

refs https://github.com/sebastiencs/company-box/issues/123
refs https://github.com/sebastiencs/company-box/issues/135

**Comment by rangerzhou** [comment]
大佬，看到你升级过libc6，我从18.04下载了个libc6-2.33的包强行安装，导致出问题了，有啥办法修复吗？拜谢！

```
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libc6-dbg : Breaks: libc6-dbg:i386 (!= 2.27-3ubuntu1.4) but 2.33-0ubuntu4 is installed
 libc6-dbg:i386 : Depends: libc6:i386 (= 2.33-0ubuntu4) but 2.27-3ubuntu1.4 is installed
                  Breaks: libc6-dbg (!= 2.33-0ubuntu4) but 2.27-3ubuntu1.4 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by seagle0128** [comment]
@on99 Same issue here. Please file an issue for `company-box`.

**Comment by on99** [comment]
@seagle0128 I do leave a comment in company-box https://github.com/sebastiencs/company-box/issues/158
