### ISSUE TITLE
Company in LSP go-mode acting weird

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#296]
company is not showing right candidates.

![image](https://user-images.githubusercontent.com/23665525/113928349-473cb380-97b4-11eb-9b04-65495df17a2c.png)

- company-backends used

```
((company-capf :with company-yasnippet)
 (company-dabbrev-code company-keywords company-files)
 company-dabbrev)
```

Company version: 0.9.13
LSP :: lsp-mode 20210407.1022, Emacs 27.2.50, darwin
gopls version - golang.org/x/tools/gopls v0.6.9

**Comment by CsBigDataHub** [comment]
Looks like this is a issue with `LSP-MODE` not sure what.
I changed `centaur-lsp` to `eglot` to rule out if `company-mode` has a issue, but every thing works just fine with `eglot`.

**Comment by seagle0128** [comment]
So please file an issue for `lsp-mode`?
