### ISSUE TITLE
can not run normally

### ISSUE THREAD

**Issue by newlife** [seagle0128/.emacs.d#297]
Set package archives to `tuna'
Loading theme `doom-one'
[Treemacs] Warning: coudn't find default background colour for icons, falling back on #2d2d31.
[Treemacs] Warning: couldn't find hl-line-mode's background color for icons, falling back on #2d2d31.
**_Eager macro-expansion failure: (wrong-number-of-arguments (2 . 2) 4)_**
could not find banner /root/.emacs.d/logo.png, use default instead
Loading /root/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
**_custom-initialize-reset: Invalid version syntax: `' (must start with a number)_**

seems  two errors 

how to fix this ?

**Comment by seagle0128** [comment]
Can you please provide the backtrace?
