### ISSUE TITLE
can't open magit-status

### ISSUE THREAD

**Issue by requireonce** [seagle0128/.emacs.d#298]
Hello @seagle0128 :
when I type'C-x g' to open magit-status, it can't work, magit window can't open. 
Does you have the same problem?
It has a error log as below,

error log:
Loading file /home/johns/.emacs.d/elpa/with-editor-20210319.1930/with-editor.elc failed to provide feature ‘with-editor’

**Comment by seagle0128** [comment]
`M-x package-reinstall with-editor RET`

**Comment by requireonce** [comment]
> `M-x package-reinstall with-editor RET`

It works for me, thank you.

**Comment by requireonce** [comment]
Reinstall package solved my problem.
