### ISSUE TITLE
label emoji can't display, did you encountered this problem ?

### ISSUE THREAD

**Issue by requireonce** [seagle0128/.emacs.d#299]
Hi @seagle0128 
    I'm using linux os, but the label emoji(🏷) can't display when I use org-mode.
Did you encounter this problem ?
Or dou you have any good idea to solve this problem ?

screenshot:

![Screenshot_20210422_142538](https://user-images.githubusercontent.com/19338131/115666079-b4387780-a376-11eb-9781-1a4a98fe2d73.png)

**Comment by seagle0128** [comment]
It's related to the fonts. Please try another font. It's fine in my env.

**Comment by requireonce** [comment]
thanks, I'll try other font.
