### ISSUE TITLE
no todos in magit-status-buffer

### ISSUE THREAD

**Issue by phisu** [seagle0128/.emacs.d#301]
i am unable to get magit-todos-mode to run.  when i call magit-status, i do not see todos of my project. but in the minibuffer i get the message 

`magit-todos: Not overriding bind of "jT" in ‘magit-status-mode-map’.`

when i am in the magit-status-buffer 'j-T' does not exists. so i try M-x magit-todos-jump-to-todos. but i get only "Section "TODOs" wasn't found.

I no longer know my way around and i did not found any helpful hints by googling this issue.

can you help me to get magit-todos running?

i am using the newest centaur configuration framework on emacs 27.2 (ubuntu 20.10). i am using a fresh installation from yesterday.

**Comment by seagle0128** [comment]
It seems an issue of the upstream. I tried with vanilla Emacs (`emacs -Q`), magit-todos list doesn't exist, either. Please file an issue on https://github.com/alphapapa/magit-todos.

**Comment by CsBigDataHub** [comment]
@phisu 

try this -

add `'(magit-todos-keyword-suffix "\\(?:([^)]+)\\)?:")` in to your custom-file.

if you are coding for Python, you will need to have `TODO` in this format.

`# TODO:` - i.e., `#` comment character `space` `TODO` .

if `elisp` - `; TODO:`

**Comment by phisu** [comment]
@CsBigDataHub thank you. this helped.

**Comment by alphapapa** [comment]
@CsBigDataHub  Rather than directing users to use `setq`, please direct them to the customization system, which guides them through customizing these settings.  `M-x customize-group RET magit-todos RET`.

**Comment by phisu** [comment]
@CsBigDataHub @alphapapa 
i tried it again. but i had no success. i copied the above line from @CsBigDataHub  into my custom.el and added for example the following file to my project. but in the magit-status-buffer i don't see a list of my TODOs

the content of my file:

```
<?php
// TODO: test
# TODO: does this work?
/* TODO: or this? */

$VOC = 1000;

$formel = "if ( $VOC <= 250 ) {10}
else if ( $VOC > 3000 ) {0}
else { ( ( 120 / 11 ) - $VOC * ( 1 / 275 ) ) }";

$ret = eval($formel);
?>
```
i am using emacs 27.1 on ubuntu 21.4 and the centaur configuration framework. 

let me know if you want me to do any more tests.

**Comment by alphapapa** [comment]
@phisu Please see my comment: https://github.com/seagle0128/.emacs.d/issues/301#issuecomment-856690046

**Comment by phisu** [comment]
@alphapapa 
I did  `M-x customize-group RET magit-todos RET` and set `Magit Todos Keyword Suffix: Required colon (matching e.g. "TODO:"` and `Magit Todos Mode: on `and `Magit Todos Scanner: Automatic`. Everything else is unchanged.

I restarted emacs and called magit-status in  the project where the above file is located. i do not see any TODOs.

is what I have done right?

**Comment by CsBigDataHub** [comment]
@seagle0128 @phisu 

I have this in my `custom.el` file under `custom-set-variables`

```
 '(magit-todos-keyword-suffix "\\(?:([^)]+)\\)?:")
```
I see `TODO` in `.emacs.d`, `python` and `csharp` projects. I use `27.2` on `ubuntu` and `28.0.50` on MacOs. Everything work fine for me.

@phisu did you restart emacs after customizing the variable?

**Comment by alphapapa** [comment]
@phisu You said yesterday at https://github.com/alphapapa/magit-todos/issues/117#issuecomment-856454486 that the problem was that your items were not in the correct format, and that the problem was solved.  Now you seem to be saying that it's not solved.

Since the package works properly for me and other users on a variety of systems and versions, I don't think there is a new bug in the package.  I doubt it's related to Centaur, but if it is, I can't help you with that.  Regardless, the advice I would give is the same as always: try to reproduce the problem in a clean Emacs config.  Beyond that, I can't help you.

**Comment by seagle0128** [comment]
I tested with Emacs 27.2 on Windows, the TODO list was displayed correctly, but nothing on 28.
