### ISSUE TITLE
in some situation emacs becomes very slow

### ISSUE THREAD

**Issue by phisu** [seagle0128/.emacs.d#304]
i have a php file that has about 3500 lines. when i change a string in it, emacs is very busy and it takes a very long time for my typed characters to appear on the screen. i can then only wait for emacs to respond again (about a minute or sometimes longer). To explain an example: 

i have the following line (line 166 in the file with 3500 lines) and i put the cursor after "WHERE". then i type an quote. then i have to wait forever until the quote appears. and i can't continue working.

`$q = "SELECT structure_id,count(id) as num FROM `structure_fldDefs` WHERE version = '.$version.' group by structure_id";`

if the same line is at the very bottom of the file, i don't have this problem.

the file is not in any project, but is in a directory by itself for the test. i mention this to eliminate my assumption that the slow behavior might depend on the size of the project.

i suspect that centaur emacs is busy formatting, indenting and syntax checking the rest of the file. and that probably takes a long time for the whole file.

because i am not familiar with the internals of emacs, i would like to ask what i can do to avoid this problem; or where can i report this problem to get an improvement of a module. or do i have to change something in the emacs configuration?

i am using a fresh installation of centaur with emacs 27.2 on ubuntu 20.10 and intelephense as lsp server for php files.

[further considerations](https://github.com/DarthFennec/highlight-indent-guides/issues/33#issuecomment-830828023) to this problem.

**Comment by seagle0128** [comment]
The workaround is to disable `highlight-indent-guides-mode` in php-mode.

**Comment by phisu** [comment]
`Please file an issue in upstream.`
do you mean i should open a new issue here?

**Comment by seagle0128** [comment]
If you think it's an issue of `highlight-indent-guides`, please file an issue in https://github.com/DarthFennec/highlight-indent-guides/issues/
