### ISSUE TITLE
error: [Treemacs] Something went wrong when finding tag 'foo': (wrong-type-argument integer-or-marker-p nil) 

### ISSUE THREAD

**Issue by phisu** [seagle0128/.emacs.d#305]
for this problem i have already created an issue at treemacs and got a partial answer [there](https://github.com/Alexander-Miller/treemacs/issues/796). it seems that the problem is related to the open-dashboard() function. this is defined in .emacs.d/lisp/init-dashboard.el. unfortunately, i don't understand treemacs' relation to this function. 
do you see any way to solve this problem or shed some light on the treemacs connection?

**Comment by seagle0128** [comment]
I add comments in https://github.com/Alexander-Miller/treemacs/issues/796
