### ISSUE TITLE
Installation error while installing packages

### ISSUE THREAD

**Issue by quarkquartet** [seagle0128/.emacs.d#307]
Running on a ssh server with emacs-25.2. (emmm it >25.1 so theoretically it should work....)

> Error (use-package): Failed to parse package elfeed: Symbol’s function definition is void: caadr
Error (use-package): Failed to parse package ztree: Symbol’s function definition is void: caadr
Error (use-package): Failed to install memory-usage: Package ‘memory-usage-’ is unavailable
Error (use-package): Failed to parse package smerge-mode: Symbol’s function definition is void: caadr
Error (use-package): Failed to parse package lsp-ui: Symbol’s function definition is void: caadr
Error (use-package): Failed to install lsp-mode: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install lsp-ivy: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install lsp-treemacs: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install lsp-pyright: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install ccls: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install lsp-julia: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install lsp-java: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to parse package dumb-jump: Symbol’s function definition is void: caadr
Error (use-package): Failed to install editorconfig: Package ‘nadvice-0.3’ is unavailable
Error (use-package): Failed to install csharp-mode: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install csv-mode: Package ‘csv-mode-’ is unavailable
Error (use-package): Failed to install mermaid-mode: Package ‘emacs-25.3’ is unavailable
Error (use-package): Failed to install rustic: Package ‘emacs-26.1’ is unavailable

I tried the solutions in [https://github.com/seagle0128/.emacs.d/issues/98](url), nothing works. 

Any idea?

**Comment by quarkquartet** [comment]
Sorry for the trouble. I tried the updated version. But still some errors: this time the packages that failed to install are different:

> Error (use-package): Failed to install gnu-elpa-keyring-update: Package ‘gnu-elpa-keyring-update-’ is unavailable
Error (use-package): Failed to install paradox: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install undo-tree: Package ‘undo-tree-’ is unavailable
Error (use-package): Failed to install dired-git-info: Package ‘dired-git-info-’ is unavailable
Error (use-package): Failed to install rainbow-mode: Package ‘rainbow-mode-’ is unavailable
Error (use-package): Failed to install treemacs: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install memory-usage: Package ‘memory-usage-’ is unavailable
Error (use-package): Failed to install editorconfig: Package ‘nadvice-0.3’ is unavailable
Error (use-package): Failed to install csharp-mode: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install csv-mode: Package ‘csv-mode-’ is unavailable
Error (use-package): Failed to install mermaid-mode: Package ‘emacs-25.3’ is unavailable

The ssh server is Ubuntu 18.04. Emacs version 25.2.2.

**Comment by seagle0128** [comment]
Please check the network, or change another mirror.

**Comment by quarkquartet** [comment]
> Please check the network, or change another mirror.

I think it's not network problem..I'm installing a lot of configurations these days and there are not any problems. I also tried Centaur installation several times, but it's still the case. 

I agree it's something due to the mirror, but how to change mirror in Centaur? I mean, should I change the mirror sources ini the `custom.el` or the original code? What are some possible mirror sources, could you please give some recommendations?

**Comment by seagle0128** [comment]
See https://github.com/seagle0128/.emacs.d#manual.

```elisp
(setq centaur-package-archives 'melpa)         ; Package repo: melpa, emacs-china, netease, ustc, tencent or tuna
```

**Comment by quarkquartet** [comment]
> See https://github.com/seagle0128/.emacs.d#manual.
> 
> ```emacs-lisp
> (setq centaur-package-archives 'melpa)         ; Package repo: melpa, emacs-china, netease, ustc, tencent or tuna
> ```

This is exactly what I did before this reply.

Unfortunately, I tried to add the line `﻿(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")`, tried `M-x package-refresh-contents`, and tried all the mirrors listed. But nothing works. I also tried to use my wifi at home instead of in the office, but it still does not work (I'm not pretty sure whether changing my personal wifi will change anything since I'm using a ssh server. Perhaps the ssh server uses its own connection.)

I already tried installing other things on this server, i.e. zsh, vim config, etc. Only emacs mirror gives me this error.

Any other idea?

Still appreciate a lot for your help!

**Comment by quarkquartet** [comment]
I'm trying to debug step-by-step.

I deleted all the configurations, and simply add elpa sources. Then `M-x package-install`

Then I got this: 

> Failed to verify signature archive-contents.sig:
No public key for 066DAFCB81E42C40 created at 2021-06-09T17:10:02-0400 using RSA
Command output:
gpg: Signature made Wed 09 Jun 2021 05:10:02 PM EDT
gpg:                using RSA key C433554766D3DDC64221BFAA066DAFCB81E42C40
gpg: Can't check signature: No public key

I searched by google, it said it can be solved by (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3"). But no.

**Comment by seagle0128** [comment]
1. Check your local network environment, or try other network connection, like 4G/5G. In my env, `gnutls-algorithm-priority` is nil.
1. `(setq package-check-signature nil)`

**Comment by quarkquartet** [comment]
Thanks for your reply. I tried `(setq package-check-signature nil)`, this works together with set melpa to netease. (Although I do not understand. I'm currently in US, why this mirror works better?)
Currently these three packages are still fail to be installed.

> Error (use-package): Failed to install treemacs: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install csharp-mode: Package ‘emacs-26.1’ is unavailable
Error (use-package): Failed to install mermaid-mode: Package ‘emacs-25.3’ is unavailable

The other packages are ready. I'm sure that this time the gnu-keyring-update is in the .emacs.d/elpa. Sorry for the bothering. For the remaining one, does those indeed require higher emacs version so that there is no way to fix?

**Comment by seagle0128** [comment]
I don't know the details of your network. Just using `(setq package-check-signature nil)`. It will ignore the signature checking.
