### ISSUE TITLE
Support emacs 27.2

### ISSUE THREAD

**Issue by crazyraven** [seagle0128/.emacs.d#308]
Hi
I'm fedora linux user and I'm happy to use emacs with your customization.
After my laptop upgraded to fedora 34, emacs is updated 27.1 to 27.2 as well but after that, centaur emacs doesn't work any more. 
I've fresh installed without any custom-post.el but emacs stuck like below capture without errors.

![image](https://user-images.githubusercontent.com/38021808/120211823-4c762600-c26c-11eb-8c02-2b00ab7639ae.png)

Your advise will be much appreciated.

**Comment by seagle0128** [comment]
Emacs 27.x should be supported. Delete elpa directory and reinstall the packages. Good luck!

**Comment by crazyraven** [comment]
I removed emacs.d directory and fresh installed again but it stuck again.

**Comment by seagle0128** [comment]
Hmm... I can do nothing without any details. Can you reproduce with `emacs -Q`? Or comment or remove some configurations  from `init.el` to troubleshoot?

**Comment by crazyraven** [comment]
Thank you for point out to troubleshoot.
As your advise, make configurations in init.el commented one by one and finally figure out what makes it stuck.
When I make comment  (require 'init-basic) in init.el, emacs started compiling without errors. is it safe to use without 'init-basic'?

Thank you :)

**Comment by seagle0128** [comment]
You can use it without `init-basic`, but I don't recommend. Try to troubleshoot `init-basic.el` with the same approach.

**Comment by crazyraven** [comment]
cause of stuck was a "exec-path-from-shell".
compare to old init-basic, the line 'exec-path-from-shell-arguments '("-l")' has removed in current version. after add it, the installing  is working.

**Comment by seagle0128** [comment]
So you need to check what's the problem of your shell configurations?

**Comment by crazyraven** [comment]
it stuck without my shell customization. I think there are some conflict with updated fedora shell initialization script because other linux distro such as debian, it works with the same shell customization.

**Comment by seagle0128** [comment]
Suggest to query for `exec-path-from-shell`. I am closing this issue. Thanks!
