### ISSUE TITLE
Settings in custom-post.org resp. *.el won't be applied

### ISSUE THREAD

**Issue by mbutz** [seagle0128/.emacs.d#312]
I really do like Centaur Emacs. Thanks a lot for this available!

One thing I couldn't solve: I have several settings in my `custom-post.org'.

E. g.:

```
(setq cursor-type '(bar . 2))

;; and my Tidal Cycles setup:

(use-package tidal
  :hook (tidal-mode-hook . tidal-setup)
  :config
  (defun tidal-setup()
    (flyspell-mode nil)
    (company-box-mode nil)
    (display-line-numbers-mode nil)
    (diff-hl-mode nil)
    )
)

```
These settings will not be applied after loading Emacs. Probably I am doing something terribly wrong. If that's the case I'd be very grateful for a hint how to solve that.

**Comment by seagle0128** [comment]
Glad to know you like Centaur!

I checked the snippet, and I think it should be:

```elisp
(setq-default cursor-type '(bar . 2))

;; and my Tidal Cycles setup:

(use-package tidal
  :hook (tidal-mode . tidal-setup)
  :config
  (defun tidal-setup()
    (flyspell-mode nil)
    (company-box-mode nil)
    (display-line-numbers-mode nil)
    (diff-hl-mode nil)
    )
)
```

**Comment by mbutz** [comment]
Yes, thanks a lot. This did the trick for the cursor type.

All the stuff in the tidal setup will still be ignored despite the fact that tidal mode will be loaded properly.

**Comment by seagle0128** [comment]
Welcome!
