### ISSUE TITLE
company-box making emacs unusable after latest changes in company-mode

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#313]
`company-mode` has new updates -
https://github.com/company-mode/company-mode/blob/master/NEWS.md
 and `company-box` is not compatible with those changes. This is breaking emacs.

Is it possible to remove `company-box` and just leverage icon support for `company-mode` it self?

https://github.com/company-mode/company-mode/pull/1070

Also search for `icon` in https://github.com/company-mode/company-mode/blob/master/NEWS.md for new icon functions

**Comment by CsBigDataHub** [comment]
Icon support in `company-mode` can be achieved by 
`company-format-margin-function #'company-detect-icons-margin`

**Comment by CsBigDataHub** [comment]
created PR to fix company-box 
https://github.com/sebastiencs/company-box/pull/168

**Comment by seagle0128** [comment]
I saw your PR of `company-box`. Hope the author to merge it soon.
Well, I know company support icons now, basically support vscode icons. `company-box` supports both icons and help docs, so I prefer it. With my fine-tuning, it looks great IMO.

**Comment by CsBigDataHub** [comment]
> With my fine-tuning, it looks great IMO.
Yes it does ;)

> If company-box is not maintained actively, perhaps I will consider other solution.

completely agree.

PR sebastiencs/company-box#168 is pushed to melpa. closing the issue.

**Comment by seagle0128** [comment]
Thanks!
