### ISSUE TITLE
Use Citre together with lsp mode

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#314]
Just an FYI if you are interested - https://github.com/universal-ctags/citre/wiki/Use-Citre-together-with-lsp-mode

**Comment by seagle0128** [comment]
I am thinking how to integrate citre into lsp-mode, but I need some time to make it have better experience. And do you happen to know how to integrate into eglot?

**Comment by CsBigDataHub** [comment]
`company-citre` should work for both `lsp-mode` and `eglot`.

`define-advice xref--create-fetcher` also the same since `eglot` also uses `xref`

with `lsp-citre-capf-function` all that needed to change is `lsp-completion-at-point` to `eglot-completion-at-point`.

reference -
https://github.com/joaotavora/eglot/blob/194b178ef41ccd3d937983f3829d44a546bb24d6/eglot.el#L1536-L1537

**Comment by seagle0128** [comment]
According to your request and comments, I tried to integrate lsp/eglot with citre. Honestly I didn't test completely. Please help to test and provide feedback. Thanks!

**Comment by CsBigDataHub** [comment]
@seagle0128 Thanks, I tried it with a sample python project with `pyright` but I could not really see a difference.
I think its because `pyright` is fast enough to supersede `citre` completeion-at-point. Let try it with C# and golang and I can give more informed feedback.

**Comment by seagle0128** [comment]
@CsBigDataHub Maybe you need to kill the lsp server to test?

**Comment by CsBigDataHub** [comment]
Yes with out lsp mode I see the completions but there is not documentation on the completions. Moreover I do not see completions on  packages like 'sys' when using 'citre'. I wanted to check its integration with LSP mode. So turning off LSP mode is not an option.
