### ISSUE TITLE
problems with counsel-M-x when the mouse in the pop window

### ISSUE THREAD

**Issue by jidibinlin** [seagle0128/.emacs.d#319]
![problem](https://user-images.githubusercontent.com/38578679/129471886-7d2df387-9111-4183-9b24-cb65e4bde574.gif)

**Comment by seagle0128** [comment]
Are you using Linux? Which distribution? I couldn't reproduce on Ubuntu.

**Comment by jidibinlin** [comment]
I used ubuntu 20.04

**Comment by jidibinlin** [comment]
It`s may relate to i3wm.
when i use gnome it`s work fine.

**Comment by seagle0128** [comment]
If it's related to WM, I can do nothing with it.

**Comment by jidibinlin** [comment]
OK，thanks
