### ISSUE TITLE
How to add other package and add my own config for the package?

### ISSUE THREAD

**Issue by YukoOshima** [seagle0128/.emacs.d#327]
I wonder how to add other package and add my own config for the package?
Because I found that the custom.el doesn't support `use-package`. 
So I don't know whether there's a center dot file for the config?

**Comment by seagle0128** [comment]
You may need `custom-post.el`.

**Comment by YukoOshima** [comment]
May I know whether there's a `custom-post.el` template or doc?

**Comment by seagle0128** [comment]
Just like other init-xx.el file. It's loaded in `after-init-hook`.
