### ISSUE TITLE
error with global-prettier-mode nil

### ISSUE THREAD

**Issue by phisu** [seagle0128/.emacs.d#329]
in my custom.el I have 

'(global-prettier-mode nil)

since some time I get the following error, when I save a php file. 

` Error: Cannot find prettier anywhere, check troubleshooting instructions.`

i know i don't have prettier installed. but i don't want prettier either. that's why i set the corresponding configuration variable to nil.  what can i do to avoid the error message?

**Comment by seagle0128** [comment]
```ellisp
(with-eval-after-load 'prettier
  (global-prettier-mode -1))
```
