### ISSUE TITLE
关于python环境检测的问题

### ISSUE THREAD

**Issue by lartpang** [seagle0128/.emacs.d#33]
Ubuntu 18.04

在原机的基础上安装了anaconda3，主环境为3.6.5版本。

---

![image](https://user-images.githubusercontent.com/26847524/45657573-8d11cd80-bb1d-11e8-97b0-99f3ceb8a28d.png)

问题1：这里python版本的含义是指处理当前文件时，插件所使用的python环境么？
问题2：这里的python版本是如何检测的呢？

我从图标打开emacs和从终端打开emacs，进入同一个python文件，但是检测的环境不同。图表对应2.7.15rc1，但是终端对应的就是3.6.5

![image](https://user-images.githubusercontent.com/26847524/45657637-d06c3c00-bb1d-11e8-9be1-2c2d181fc70a.png)

问题3：请问如何手动切换环境呢？请问您是怎么应对的呢？

---

我查看了 issue https://github.com/seagle0128/.emacs.d/pull/24 但是对应的代码没有在我安装的配置代码中。（这。。）

**Comment by seagle0128** [comment]
这是因为你的GUI环境和terminal环境的环境变量不同导致的。你可以用`M-x getenv RET PATH RET`来查看。另外，你可以在GUI和Terminal下分别执行以下命令获取Python版本：`M-! python --version`。

GUI环境下，建议用`exec-shell-path`导入Terminal下的`PATH`，这样就保持一致了。

**Comment by seagle0128** [comment]
看起来你是直接用的Centaur Emacs。 目前个人使用zsh (参考配置https://github.com/seagle0128/dotfiles )，为了加快启动速度，去掉了参数"-i"（--interactive）, `(setq exec-path-from-shell-arguments '("-l"))` 。这段告警我默认屏蔽掉了。

`exec-path-from-shell`中有这样一段message： 
> "You appear to be setting environment variables %S in your .bashrc or .zshrc: those files are only read by interactive shells, so you should instead set environment variables in startup files like .profile, .bash_profile or .zshenv.  Refer to your shell's man page for more info.  Customize `exec-path-from-shell-arguments' to remove \"-i\" when done, or disable `exec-path-from-shell-check-startup-files' to disable this message."

如果你不怕启动慢，可以设置参数为`(setq exec-path-from-shell-arguments '("-l" “-i”))`。个人更建议把环境变量之类的放到.profile, .bash_profile 或者 .zshenv。这算是一个比较复杂的问题了，你很细心注意到了。我会先加到FAQ里，方便其他人查阅。

谢谢你的详细反馈！

**Comment by lartpang** [comment]
首先感谢您的积极回复，确实，加上了 "-i" 参数会使得emacs可以读取到.bashrc的PATH，但是我对于这个指令：

![img](https://user-images.githubusercontent.com/26847524/45725024-5acea180-bbeb-11e8-889b-563b618e93e0.png)

的结果很疑惑。

**问题：是不可以像我这样使用么？或者说是有其他的原因？**

我的流程：

1. M-x exec-path-from-shell-copy-env RET
2. RET
3. 得到了下面的错误

![image](https://user-images.githubusercontent.com/26847524/45741062-3e515a00-bc29-11e8-8dad-ac91e4173a9f.png)

**Comment by seagle0128** [comment]
你可以用`C-h f exec-path-from-shell-copy-env RET` 查看帮助。这个函数必须带参数(环境变量的名字)
`（exec-path-from-shell-copy-env NAME)`

所以，如果你使用应该像这样：`M-x exec-path-from-shell-copy-env RET PATH RET`。

这个包的原理就是解析shell启动配置，将需要的环境变量通过`exec-path-from-shell-copy-env` 拷贝到Emacs内部。

**Comment by lartpang** [comment]
非常感谢您的耐心解释，理解了。

**Comment by seagle0128** [comment]
不客气。Enjoy 😄
