### ISSUE TITLE
[Bug] (use-package git-modes) git-modes 找不到

### ISSUE THREAD

**Issue by jidibinlin** [seagle0128/.emacs.d#332]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

今天更新之后，发现启动报错了 说"git-modes-"找不到，不懂为啥
![git-modes](https://user-images.githubusercontent.com/38578679/140086944-8615323b-2bcb-416b-87d0-43ca2301857f.PNG)

### Steps to reproduce

我同步了下然后打开emacs就这样了

### Expected behavior

不报错就好

### OS

Linux

### Emacs Version

gccemacs-28

### Anything else

我去init-vcs.el里面单独执行了(use-package git-modes)报错了，应该是这个地方有啥问题吧。

我用的gcc-emacs-29
archlinux

**Comment by jidibinlin** [comment]
![init-vcs](https://user-images.githubusercontent.com/38578679/140092391-a55b5246-043f-4e94-b7cf-94c47353d2c5.PNG)
刚去看了下 这两个修改都导致了一些问题
上面的那个倒是magit-diff magit-log等命令打不开，应该是跟posframe那边有关系

**Comment by seagle0128** [comment]
1. 更新到最新配置；
2. 使用melpa源。国内源最近有问题；
3. 刷新后更新包。

**Comment by jidibinlin** [comment]
posframe--set-frame-szie 那边的参数类型应该是弄错了。改成这样就可以了
![init-vcs](https://user-images.githubusercontent.com/38578679/140258453-8f3ab4d7-e676-4f05-8c1d-769d14e1202e.PNG)

**Comment by seagle0128** [comment]
posframe 又改函数了，我已经去掉了，并做了优化。
