### ISSUE TITLE
[Feature Request] make a suggestion that integrateing the virtual environment  for python-mode may be more convenient for pythoners.；Is there any plan ?

### ISSUE THREAD

**Issue by requireonce** [seagle0128/.emacs.d#334]
**Describe the solution you'd like**
can switch between many different python edition, such as python2.7 and python3.8

**Describe alternatives you've considered**
Most of the time, pydev is a good choice at many.

**Comment by seagle0128** [comment]
Did you try http://github.com/jorgenschaefer/pyvenv or https://github.com/aculich/virtualenv.el ?

**Comment by seagle0128** [comment]
Closing it due to no update recently.
