### ISSUE TITLE
[Bug] Error (use-package): Failed to install git-modes: Package ‘git-modes-’ is unavailable

### ISSUE THREAD

**Issue by morole** [seagle0128/.emacs.d#335]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Error (use-package): Failed to install git-modes: Package ‘git-modes-’ is unavailable

### Steps to reproduce

Download the latest package and report this error all the time after startup

### Expected behavior

macOS 11.4
emacs 27.2.2
 Latest centaur

### OS

MacOS

### Emacs Version

27

### Error callstack

```emacs-lisp
Error (use-package): Failed to install git-modes: Package ‘git-modes-’ is unavailable
```

**Comment by seagle0128** [comment]
Change archive package mirror to mela.org, and refresh the contents.
