### ISSUE TITLE
[Bug]  GUI too large when start up

### ISSUE THREAD

**Issue by LimingFang** [seagle0128/.emacs.d#336]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

when I open emacs via app or terminal, it just becomes too large, fulfilling all my window, but strangely, it's not even in the full-screen mode!
我用图标或者终端打开emacs，刚下载完centuar emacs都是正常的，但是不知道做了啥设置，突然打开就这样了：他不是最大化模式，就是大得离谱，我根本无法操作它，我意思是，在mac上即使手动拉大，也是应该能看到左上角红色、黄色、绿色那几个按钮的，但目前我看不到了。
但是我`emacs -Q`就没问题
![IMG_0499 Large](https://user-images.githubusercontent.com/28479651/143604219-6ed6428a-424c-4d49-9512-4242d66aea6d.jpeg)

### Steps to reproduce

正常图标打开emacs或者terminal下输入`emacs`

### Expected behavior

正常大小的图标

### OS

MacOS

### Emacs Version

27

### Anything else

我是M1 MacBook pro

**Comment by seagle0128** [comment]
可以尝试以下几种解决方案：
1. 关闭Emacs，删除`~/.emacs.d/persp-confs/persp-frame`文件
2. custom.el中设置`(setq centaur-restore-frame-geometry nil)`
3. 禁用`persp-mode`

猜测你是在terminal和GUI模式下来回切换，或者外接显示屏之后造成该现象。

**Comment by LimingFang** [comment]
我前两步做了，第三步您是指`M-x customize`，然后只需要设置第一项为nil就行了对吗
<img width="918" alt="截屏2021-11-27 09 53 49" src="https://user-images.githubusercontent.com/28479651/143664507-65e465ed-f08e-439b-a73d-8d2a2c0fa668.png">
我这三步做完就正常了！感谢🙏

**Comment by LimingFang** [comment]
似乎打开是正常了，但是我在全屏模式下是像使用`M-x`的时候，都会另外开一个窗口，然后此时emacs窗口就不对了，虽然重启又会恢复正常

**Comment by seagle0128** [comment]
全屏模式下必须使用 `(setq ns-use-native-fullscreen nil)`，这是Emacs自己的bug。最新的28已经修复了该问题。

**Comment by LimingFang** [comment]
感谢您的回复！
我之前也有使用magnet窗口管理工具，我现在升级到29啦，一切都解决了，感谢。
centaur emacs非常好用！不过我之后会根据个人需要做一些精简
