### ISSUE TITLE
[Help Wanted]:go-mode disable godoc auto showing

### ISSUE THREAD

**Issue by LimingFang** [seagle0128/.emacs.d#337]
**描述：**
编辑golang文件时，我发现光标所在的变量或者函数上方会自动跳出一个doc文档，我不希望它自动跳出，我更希望我在某些时候去通过command调用它/
<img width="667" alt="截屏2021-11-27 12 03 06" src="https://user-images.githubusercontent.com/28479651/143667443-594877d8-cb76-4a2a-af03-ab913cab1b77.png">
**目前进度：**
我查了go-mode README，有一个`godoc-at-point`，它会调用`godoc-at-point-function`，后者绑定在`<f1>`，因此我通过f1能查询变量文档，但是我如何避免它自动显示呢？
**环境：**
- emacs27
- macbook16 M1Pro，12.0.1

**Comment by LimingFang** [comment]
经过我的初步查询，是lsp-ui相关的问题，我自己在check一下

**Comment by seagle0128** [comment]
See `lsp-ui-doc-mode` and `lsp-ui-doc-enable`.
