### ISSUE TITLE
[Bug] M-x doesn't work properly

### ISSUE THREAD

**Issue by YukoOshima** [seagle0128/.emacs.d#338]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

M-x wont list all the function any more.

### Steps to reproduce

1. Install emacs-plus
2. Key M-x. The function hints list doesn't come out.

### Expected behavior

The function hints list should come out.

### OS

MacOS

### Emacs Version

28

### Anything else

I'm using emacs-plus.

**Comment by seagle0128** [comment]
I believe it works well on macOS. What's in your `custom.el`? Try `(setq centaur-completion-style 'minibuffer)` in custom.el.

**Comment by YukoOshima** [comment]
It works well in terminal emacs
![image](https://user-images.githubusercontent.com/17468913/144167958-e5e8255b-a779-4696-93b7-b244363513a1.png)

But for GUI emacs, the mini buffer doesn't come out 

![image](https://user-images.githubusercontent.com/17468913/144167996-386de307-8108-4db9-b910-ea7e1e9702e3.png)

My emacs version is emacs-plus@28.

**Comment by YukoOshima** [comment]
> I believe it works well on macOS. What's in your `custom.el`? Try `(setq centaur-completion-style 'minibuffer)` in custom.el.

I've tried to add this statement, and it still can not work in GUI emacs. 
And my computer is `m1 macmini`.

**Comment by seagle0128** [comment]
In GUI, the default behavior is to display in child frame, at the center of the frame.
