### ISSUE TITLE
face-attribute: Setting current directory: No such file or directory, /build/emacs/src/emacs-27.2/

### ISSUE THREAD

**Issue by rif** [seagle0128/.emacs.d#339]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Starting a few days ago when I start emacs on linux (arch) I get the following error:

face-attribute: `Setting` current directory: No such file or directory, /build/emacs/src/emacs-27.2/

and emacs stops loading configuration.

I get this message on two separate machines with the same linux OS.

### Steps to reproduce

Just start emacs

### Expected behavior

Emacs loading the configuration as usual.

### OS

Linux

### Emacs Version

27

### Anything else

As a workaround, I created the entire /build/emacs/src/emacs-27.2/ path and then emacs starts correctly.

**Comment by seagle0128** [comment]
How about `emacs -Q`?

**Comment by rif** [comment]
emacs -Q and emacs -Q --l ~/.emacs.d/init-mini.el are fine, they don't have the issue.

**Comment by seagle0128** [comment]
No idea. It's better have the backtrace for the further investigation.

**Comment by seagle0128** [comment]
`M-x toggle-debug-on-error`.

**Comment by rif** [comment]
But the error occurs during startup and by the time I can enter this command the error already happened.

**Comment by seagle0128** [comment]
See the command args:`emacs --debug-init`.

**Comment by rif** [comment]
I only get "Setting current directory: No such file or directory, /build/emacs/src/emacs-27.2/" in the bottom echo area
An in the *Messages* I get this:


Loading /home/rif/.emacs.d/custom.el (source)...done
Set package archives to ‘melpa’
Loaded theme ‘doom-city-lights’
[Treemacs] Warning: coudn’t find default background colour for icons, falling back on #2d2d31.
[Treemacs] Warning: couldn’t find hl-line-mode’s background color for icons, falling back on #2d2d31.
Starting new Ispell process aspell with default dictionary...done
Loading /home/rif/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
custom-initialize-reset: Setting current directory: No such file or directory, /build/emacs/src/emacs-27.2/

**Comment by rif** [comment]
If you don't see any hint in these messages I guess we can close this issue because it's probably not related to your configs.

**Comment by seagle0128** [comment]
Yep, according to the messages above, it seems you built the emacs yourself. I don't think it's related to the configuration.

**Comment by seagle0128** [comment]
I found it might be related to blamer. I removed this package now.

**Comment by rif** [comment]
Yes, I confirm the issue is gone after centaur-update. Thank you!
