### ISSUE TITLE
关于emacs27上的使用问题

### ISSUE THREAD

**Issue by lartpang** [seagle0128/.emacs.d#34]
您好，由于最开始使用的自己编译的emacs26，有些小问题。所以我改用了emacs27。

这里就有个**建议**和一个**疑惑**。

**建议**

https://github.com/seagle0128/.emacs.d/blob/7bd8baf704dbe88bd49307eac35ef9fb100a7b0c/lisp/init-package.el#L85

这里可以改成：

```lisp
(when (version< emacs-version "27.0")
  (package-initialize))
```

**疑惑**

关于treemacs的图标，我现在成了这个样子：

![image](https://user-images.githubusercontent.com/26847524/45813887-71b5e680-bd06-11e8-80c5-e7b8831d2afd.png)

**请问这是正常的么？** 我之前使用这个light主题的时候，目录树并无图标。

请问如果这是正常的， **那么目录树的图标可以调整背景色么**？在主题上显得有些突兀。

**Comment by lartpang** [comment]
出于对emacs27的尝试，我又一次使用了doom主题，发现了一个严重的问题。对于emacs gui版本，会无法进入。我尝试了终端执行`emacs`，出现了如下的错误：（ 终端版本的emacs -nw可以进入）
```
lart@lart:~$ emacs
Fatal error 11: Segmentation fault
Backtrace:
emacs[0x51170e]
emacs[0x4f7bba]
emacs[0x50fbee]
emacs[0x50fe08]
emacs[0x50fe8c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fa4c0bc1890]
emacs[0x5e2d8f]
emacs[0x5e3223]
emacs[0x5e354e]
emacs[0x4495c9]
emacs[0x44cb81]
emacs[0x44d688]
emacs[0x44da76]
emacs[0x44eb0b]
emacs[0x44da76]
emacs[0x44fcdd]
emacs[0x44ff0b]
emacs[0x468634]
emacs[0x46c6bb]
emacs[0x56e846]
emacs[0x437174]
emacs[0x459781]
emacs[0x45b5dd]
emacs[0x41dffa]
emacs[0x56f621]
emacs[0x5ab6b0]
emacs[0x5721a6]
emacs[0x56f59f]
emacs[0x5ab6b0]
emacs[0x5721a6]
emacs[0x56f59f]
emacs[0x56f649]
emacs[0x56ec5c]
emacs[0x56ed8b]
emacs[0x56f621]
emacs[0x5ab6b0]
emacs[0x56f59f]
emacs[0x5ab3d8]
emacs[0x56f064]
emacs[0x5ab65c]
emacs[0x57167d]
...
段错误 (核心已转储)
```
不知这是什么问题？是我的emacs的问题么？

**Comment by lartpang** [comment]
我又测试了emacs25，发现doom主题还是有些问题，一度无法进入界面，只好使用了其他主题。

**Comment by seagle0128** [comment]
由于我没有使用 Emacs27，这些问题需要一些时间调查。

**Comment by lartpang** [comment]
关于问题1，这里有个类似的issue：https://github.com/jkitchin/scimax/issues/194#issuecomment-380470596

这个是关于该问题的警告：

![image](https://user-images.githubusercontent.com/26847524/45856371-c436e780-bd86-11e8-9613-2ad4d145de16.png)

关于问题2，是在说不出来原因，那我暂时就不用doom吧，我在尝试尝试

关于问题3：

> treemacs 应该显示如下，你升级了最新的配置并安装了相应字体吗？
> 猜测你没有运行M-x all-the-icons-install-fonts。

我是运行了。

---

在彻底重装了一下（emacs27、该配置），doom可以用了。感谢。

**Comment by seagle0128** [comment]
I added `(when (< emacs-major-version 27) (package-initialize))` but reverted it, since it broken the CI.
It seems Emacs 27 still needs (package-initialize) to initialize all packages at startup. Anyway I am still investigating.

**Comment by SysConKonn** [comment]
我应该怎么样才能让treemacs像他这样呢？![image](https://i.loli.net/2019/01/18/5c414ff30c51a.png
)我现在只能做到这样，对此我似乎没有办法。
![img](https://i.loli.net/2019/01/18/5c41504942247.png)

**Comment by seagle0128** [comment]
(setq treemacs-icon-open-png
      (concat (all-the-icons-octicon "chevron-down"  :height 0.75 :v-adjust
0.1 :face 'font-lock-keyword-face)
              " "
              (all-the-icons-octicon "file-directory" :v-adjust 0 :face
'font-lock-keyword-face)
              " ")
      treemacs-icon-closed-png
      (concat (all-the-icons-octicon "chevron-right"  :height 0.75
:v-adjust 0.1 :face 'font-lock-keyword-face)
              " "
              (all-the-icons-octicon "file-directory" :v-adjust 0 :face
'font-lock-keyword-face)
              " "))

Thanks & Regards
Vincent Zhang
