### ISSUE TITLE
[Bug] 判断emacs版本问题

### ISSUE THREAD

**Issue by wow-yorick** [seagle0128/.emacs.d#343]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

![image](https://user-images.githubusercontent.com/3367220/150459738-efed6a52-7a5d-443e-afda-5daf917fac42.png)
![image](https://user-images.githubusercontent.com/3367220/150459752-fc259304-20d2-40fe-b484-02b90cb6b3c8.png)
![image](https://user-images.githubusercontent.com/3367220/150459827-1dd37fbf-ac09-49c5-8fd3-7faa0b5b4c42.png)
我的版本在判断版本时返回的是27   常量定义中用的是3开头的，导致我的版本中加载的是 ob-sh

### Steps to reproduce

![Uploading image.png…]()

### Expected behavior

加载正确的包ob-shell

### OS

MacOS

### Emacs Version

27

**Comment by seagle0128** [comment]
>我的版本在判断版本时返回的是27 常量定义中用的是3开头的，导致我的版本中加载的是 ob-sh

Centaur 中的配置是判断>=26 使用 `ob-shell`，否则是`ob-sh`。不明白你说的常量定义是3开头指的是什么？你可以检查下`emacs/>=26p`的值是不是t。

```elisp
 ;; ob-sh renamed to ob-shell since 26.1.
  (if emacs/>=26p
      (cl-pushnew '(shell . t) load-language-list)
    (cl-pushnew '(sh . t) load-language-list))
```

**Comment by wow-yorick** [comment]
![image](https://user-images.githubusercontent.com/3367220/150480794-6e0dff60-be35-462a-86d8-a5da5ca1f1df.png)

**Comment by wow-yorick** [comment]
抱歉，可能我拉的版本问题，主分支上没这个问题
