### ISSUE TITLE
Change symbol overlay color on monokai theme

### ISSUE THREAD

**Issue by maingoh** [seagle0128/.emacs.d#344]
I have installed the monokai package and added `(load-theme 'monokai t)` to my `custom-post.el`, the theme loads correctly but the symbol overlay (font color and highlighted region) is almost the same color as the background which make it not readable.

Any idea on how to fix this ?

**Comment by mowind** [comment]
Try `(disable-theme 'doom-one)`

**Comment by seagle0128** [comment]
Report to the author of `monokai`, or customize the face of `region`.

**Comment by maingoh** [comment]
Thank you @mowind it was the indeed `doom-one` theme which was still enabled and conflicting with monokai.
No need to customize it !

I take the advantage of this issue to thank you @seagle0128 for this very nice distribution which look very complete and more stable than spacemacs :)

**Comment by seagle0128** [comment]
I wouldn't suggest to use `monokai-theme` since it's incompatible with Centaur. You should try `doom-monokai-classic`, `doom-monokai-pro`, or `doom-molokai`. If you really want to use other themes, use `counsel-load-theme` to avoid the conflicts.

**Comment by maingoh** [comment]
I have seen the doom versions but they don't seem exactly like the original monokai. Did you have to modify each of the available theme to make them compatible with centaur ? What does centaur change that makes other themes incompatible ?
