### ISSUE TITLE
M-. doesn't work

### ISSUE THREAD

**Issue by GeneKao** [seagle0128/.emacs.d#35]
"xref-find-definitions" short-cut "M-." doesn't work anymore. Any idea? Thanks. 

(M-. pushes, M-, pops) "M-," go back works though.

**Comment by seagle0128** [comment]
Hello, which mode do have this problem?
Please also check `C-h k M-. RET`

**Comment by GeneKao** [comment]
I am using anaconda python, and I installed python-language-server through `conda install`, and it seems working fine. 

I try to bind C-. with lsp-ui-peek-find-definitions and it works, but M-. doesn't work. 

Here is my `C-h k C-. RET` result
```
C-. runs the command lsp-ui-peek-find-definitions (found in global-map), which
is an interactive autoloaded compiled Lisp function in ‘lsp-ui-peek.el’.

It is bound to C-., M-., <menu-bar> <edit> <goto> <xref-find-def>.

(lsp-ui-peek-find-definitions)

Find definitions to the IDENTIFIER at point.
```

I temperarily edited the `init-edit.el` like this:

```lisp
;; Framework for mode-specific buffer indexes
;; (use-package imenu
;;   :ensure nil
;;   :bind (("C-." . imenu)))

(use-package lsp-ui
  :bind (("C-." . lsp-ui-peek-find-definitions)))
```

**Comment by seagle0128** [comment]
In Centaur Emacs, `M-.` is bonded to `lsp-ui-peek-find-definitions` if `lsp-mode` is enabled. You should disable `anacoda-mode` in your env.
BTW, if you don't like lsp, please use `(setq centaur-lsp nil)`.

**Comment by GeneKao** [comment]
Ah, thanks! My bad, I didn't close anaconda in the buffer after updating so they might be conflicting with each other. 
I killed it and restarted emacs, now everything works perfectly. 

Thanks a lot!

**Comment by seagle0128** [comment]
Welcome! Good to know it works 😄
