### ISSUE TITLE
[Bug] use minibuffer not found #353

### ISSUE THREAD

**Issue by 7ym0n** [seagle0128/.emacs.d#354]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

(setq dotfairy-completion-style 'minibuffer) ; lsp-ui-doc-border  see PR #353

### Steps to reproduce

start 

### Expected behavior

error

### OS

MacOS

### Emacs Version

28

**Comment by 7ym0n** [comment]
dict same issue.

`shell-pop--shell' need move up, it's function scope error.

**Comment by CsBigDataHub** [comment]
> dict same issue.
> 
> `shell-pop--shell' need move up, it's function scope error.

Yup I did the same thing, `shell-pop--shell` was not loading during startup. 
I thought it was just me.
Moving the function up fixed the issue. see https://github.com/seagle0128/.emacs.d/issues/348
