### ISSUE TITLE
[Bug] Invalid face posframe-border

### ISSUE THREAD

**Issue by laampui** [seagle0128/.emacs.d#356]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

![image](https://user-images.githubusercontent.com/15785343/166131943-59b1e3b4-8d07-4fc4-ab3d-08dab09552f2.png)

### Steps to reproduce
custom.el
`(setq centaur-completion-style 'minibuffer)`

`emacs --debug-init`

### Expected behavior

normal

### OS

Linux

### Emacs Version

gccemacs-28

**Comment by 7ym0n** [comment]
@laampui  see PR #355 , revert to old code.
