### ISSUE TITLE
[Tips] pdf-tools about poppler 22.05

### ISSUE THREAD

**Issue by ShaMaTeTuanZhang** [seagle0128/.emacs.d#358]
I don't know if it's appropriate to post this issue here.

After May 7,Latest Poppler package breaks compilation of pdf-tools [see this](https://bugs.archlinux.org/task/74676)
```
./configure -q --bindir=/home/1/.emacs.d/elpa/pdf-tools-20220426.2203/ && make clean && make -s
configure: error: cannot find necessary  poppler-private header (see README.org)
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.
```
We need downgraded poppler, poppler-qt and poppler-glib to the previous version 22.03 to compile properly.

Or don't use the package until [this](https://github.com/vedang/pdf-tools/issues/103) finised.

**Comment by seagle0128** [comment]
Thanks for letting me know it! I tried on macOS and it seems no such issue.

**Comment by ShaMaTeTuanZhang** [comment]
This looks like it will only be produced on some of the more rapidly updated distributions
Alternatively compiling this plugin using C++17 can be done using

**Comment by seagle0128** [comment]
Yep, let's waiting for the fixing from the upstream.

**Comment by ShaMaTeTuanZhang** [comment]
Upstream [fixed](https://github.com/vedang/pdf-tools/commit/4460a4fd3122e6b53cab1b7d86d6e19022d81fb1) the problem.
After updating the package it compiles properly.

**Comment by seagle0128** [comment]
Thanks! I am closing it.
