### ISSUE TITLE
when opening emacs the window is divided into dashboard and scratch

### ISSUE THREAD

**Issue by phisu** [seagle0128/.emacs.d#359]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

today i reinstalled ubuntu 22.04, emacs 8.1 (snap version) and centaur emacs with git clone. now when i start emacs by typing emacs in a terminal, emacs starts and shows a halved window with a scratch buffer on top and the centaur dashboard on the bottom. what do i have to do so that the scratch buffer doesn't appear on startup and only the dashboard is visible?

### Steps to reproduce

start emacs

### Expected behavior

only the dashboard should appear at emacs startup.

### OS

Linux

### Emacs Version

28

**Comment by ShaMaTeTuanZhang** [comment]
It may be that some packages report an error at startup,check the *Message*, or other buffers
Or try `(setq inhibit-startup-screen t)`

**Comment by seagle0128** [comment]
Are you sure you are using Emacs 8.1? 

Maybe there are some errors at startup. Another case is some packages are installed at first time and will introduce some compiler warnings. Ignore it and restart Emacs, then the dashboard will be displayed correctly.

PS: please retitle.

**Comment by rif** [comment]
This is a frequent issue on Linux. I just ignored it but I can confirm it's happening.

**Comment by seagle0128** [comment]
I am using Ubuntu 20.04 and no issue there. Could you please provide recordings and other details?

**Comment by rif** [comment]
[Recording](https://transfer.sh/yurvRe/recording.mp4)

arch with latest emacs and updated centaur

**Comment by seagle0128** [comment]
Can you share the messages, errors and/or warnings?

**Comment by rif** [comment]
Set package archives to ‘melpa’
Warning: exec-path-from-shell execution took 644ms. See the README for tips on reducing this.
circadian.el — enabled doom-one
tsc-dyn-get: Using source :github (:loaded nil :recorded 0.18.0 :requested 0.18.0)
tsc-dyn-get: Recorded version already satifies requested -> loading
[tree-sitter-langs] Running (git rev-parse --show-toplevel) in /home/rif/.emacs.d/elpa/tree-sitter-langs-20220508.636/
The directory /home/rif/.emacs.d/elpa/tree-sitter-langs-20220508.636/ doesn’t seem to be a git working dir. Grammar-building functions will not work.
tree-sitter-langs: Grammar bundle v0.12.0 was already installed; skipped
Starting new Ispell process aspell with default dictionary...done
Warning: exec-path-from-shell execution took 625ms. See the README for tips on reducing this.
Clearing removed files...done
Processing modified files...done
Loading /home/rif/.emacs.d/persp-confs/persp-frame...done
PNG warning: iCCP: extra compressed data
Loading /home/rif/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
[yas] Prepared just-in-time loading of snippets successfully.
ad-handle-definition: ‘easy-mark’ got redefined
Overriding package-menu--print-info with paradox--print-info
Overriding package-menu--print-info-simple with paradox--print-info
Overriding package-menu--generate with paradox--generate-menu
Overriding package-menu-mode with paradox-menu-mode
Loading /home/rif/.emacs.d/custom-post.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
PNG warning: iCCP: extra compressed data
delete-other-windows: Cannot make side window the only window
next-line: End of buffer
previous-line: Beginning of buffer [6 times]
Beginning of buffer [3 times]
Mark set

**Comment by rif** [comment]
Is this what you need or should I run emacs with some debugging flag?

**Comment by phisu** [comment]
sorry for the typo: i installed emacs 28.1

yesterday i was able to open emacs several times and always observed the same phenomenon.
today centaur emacs starts only with the dashboard. 
for all i care, you can close this ticket.

thanks for the attention

**Comment by seagle0128** [comment]
Try the latest version, please.
