### ISSUE TITLE
Consider drop browse-kill-ring?

### ISSUE THREAD

**Issue by re-mx** [seagle0128/.emacs.d#36]
Hello:

I found that the demand for "browsing the `kill-ring`" is not large.

In most cases, we only need to select an item from the kill-ring to paste into the text, so `counsel-yank-pop` is enough.

Please forgive my obsessive-compulsive disorder...

Thank you.

**Comment by seagle0128** [comment]
You are right! `browse-kill-ring` is kept just for compatibility. I am thinking about it.
Thanks for your suggestion!

**Comment by re-mx** [comment]
I am also considering compatibility issues...

What kind of compatibility problems do you think will lead to?

**Comment by seagle0128** [comment]
Before there are three options of completion framework in Centaur Emacs. For `ido`, `browse-kill-ring` is the 1st choice. Anyway I've removed it already, since only `ivy` is kept now.
