### ISSUE TITLE
[Feature Request] XDG support

### ISSUE THREAD

**Issue by zabbal** [seagle0128/.emacs.d#363]
**Is your feature request related to a problem? Please describe.**
Since few releases Emacs support XDG spec.
Using Centaur in XDG-compliant way would make it easier to do things like backup (without polluting it with cache or logs).

**Describe the solution you'd like**
Use ~/config/emacs for Centaur install by default.

**Describe alternatives you've considered**
Manual installation intoproper XDG directory. It kinda works but I'm afaid I might miss smth so it would be better to make it default so more eyes (including maintainers) are on it.

**Additional context**
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by seagle0128** [comment]
Do you mean use this? Since I am not using Linux, I'm also not sure.

```elisp
git clone --depth 1 https://github.com/seagle0128/.emacs.d.git $XDG_CONFIG_DIRS/.emacs.d
```

**Comment by zabbal** [comment]
`git clone --depth 1 https://github.com/seagle0128/.emacs.d.git $XDG_CONFIG_HOME/emacs` - more like that.
