### ISSUE TITLE
[Bug] Blank screen on the first start

### ISSUE THREAD

**Issue by linsui** [seagle0128/.emacs.d#365]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

On the first start, there is only a blank screen for a long time. I know it was installing packages but it would be better to show some messages. I guess it should display something but it doesn't work well for me.

### Steps to reproduce

Clone the repo and start emacs. I hope this can do the same thing.

### Expected behavior

Doomemacs and spacemacs display the installing progress on the screen.

### OS

Linux

### Emacs Version

gccemacs-28

**Comment by seagle0128** [comment]
It's as designed, for suppressing the redisplays at startup. If you want to display message (altough some, and noisy flicking), check `init-ui.el` and use below.

```elisp
(setq inhibit-startup-echo-area-message nil)
(advice-remove #'display-startup-echo-area-message #'ignore)
```

**Comment by linsui** [comment]
Thanks!
