### ISSUE TITLE
[Bug] The line is too short on the start screen

### ISSUE THREAD

**Issue by linsui** [seagle0128/.emacs.d#366]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

![image](https://user-images.githubusercontent.com/36977733/177081507-5a5a104b-2549-4da1-a8c9-4ad61387124e.png)

The line is only half of the window width long.

### Steps to reproduce

I just install it and start the emacs. I haven't do anything.

### Expected behavior

The line should be as long as the windows width.

### OS

Linux

### Emacs Version

gccemacs-28

**Comment by seagle0128** [comment]
1. How about refresh the dashboard (`g`)?
2. Which font are you using? Can you please try other fonts and restart? You can change it in `custom.el`.

**Comment by linsui** [comment]
Refreshing doesn't work. I didn't change the font setting. At least `DejaVu Sans Mono` is available on my system so it should work. I tried to add `Source Han Mono` but nothing changed.

**Comment by seagle0128** [comment]
I couldn't reproduce this issue. If you still have this issue, please file an issue on the upstream. https://github.com/emacs-dashboard/emacs-dashboard.

**Comment by linsui** [comment]
JFYI, https://github.com/purcell/page-break-lines/issues/36

**Comment by laampui** [comment]
turns out there 's variable called `page-break-lines-char`

`(setq page-break-lines-char ?😅)`

![image](https://user-images.githubusercontent.com/15785343/180643940-13bca318-939f-41f0-867c-ec5c433e81ee.png)
