### ISSUE TITLE
follow your install ,start emacs but hang [Bug] 

### ISSUE THREAD

**Issue by bookeezhou** [seagle0128/.emacs.d#367]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

when i follow install step . clone git master branch.
emacs was hanged when start

### Steps to reproduce

blank emacs no any message

### Expected behavior

first start need to install package.

### OS

Linux

### Emacs Version

28

**Comment by seagle0128** [comment]
`C-g` and check the messages. Find out what caused the hang. Generally it's because of network. e.g. git clone `pdf-tools`.
Use the proxy to complete it.

**Comment by bookeezhou** [comment]
execute `C-g`  , get not nothing message. i change init-custom.el  proxy  setup , set  my proxy , but alse with hang .

**Comment by seagle0128** [comment]
Are you sure there is no message in `*Messages*` buffer? I can do nothing with your network issue.

**Comment by bookeezhou** [comment]
yes. but now i change custom.el  proxy and package-archive . now ,thing is going well.
emacs is installing now, it spend 20 mins from now on.

**Comment by bookeezhou** [comment]
> Are you sure there is no message in `*Messages*` buffer? I can do nothing with your network issue.

success setup emacs configuration. thank you.
may by you should say that installation may take long time.
