### ISSUE TITLE
[Bug] Grip Mode Internal Server Error

### ISSUE THREAD

**Issue by wulfalpha** [seagle0128/.emacs.d#372]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

I get an internal server error every time I activate grip mode but NOT when using grip from the command line on the same document. the output looks like this
`
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wulfalpha/.local/lib/python3.9/site-packages/grip/app.py", line 190, in _render_page
    content = self.renderer.render(text, self.auth)
  File "/home/wulfalpha/.local/lib/python3.9/site-packages/grip/renderers.py", line 79, in render
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com//markdown/raw
127.0.0.1 - - [02/Oct/2022 16:13:24] "[35m[1mGET / HTTP/1.1[0m" 500 -
127.0.0.1 - - [02/Oct/2022 16:13:28] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -`
I made sure I was running the latest grip with pip and the most interesting thing is it *used to work* but stopped when I changed my config to supress errors in emacs. What was there was not changed. I just moved the code from my init to my config.

### Steps to reproduce

Here is the code from my config.el
`;; Start grip when opening a markdown/org buffer
(add-hook 'markdown-mode-hook #'grip-mode)
(add-hook 'org-mode-hook #'grip-mode)
(setq grip-binary-path "/home/wulfalpha/.local/bin/grip")
(setq grip-github-api-url "https://api.github.com/")
(setq grip-gitub-user " ")
(setq grip-github-password "################################")
(setq grip-update-after-change nil)
(setq grip-preview-host "localhost")
;; Grip markdown
(add-hook 'markdown-mode-hook #'grip-mode)
(add-hook 'org-mode-hook #'grip-mode)
`
With this it throws that 500 error.

### Expected behavior

It should just work like it did before

### OS

Linux

### Emacs Version

28

### Error callstack

```emacs-lisp
tsc-dyn-get: Using source :github (:loaded nil :recorded 0.18.0 :requested 0.18.0)
tsc-dyn-get: Recorded version already satifies requested -> loading
[tree-sitter-langs] Running (git rev-parse --show-toplevel) in /home/wulfalpha/.emacs.d/.local/straight/build-28.1/tree-sitter-langs/
The directory /home/wulfalpha/.emacs.d/.local/straight/build-28.1/tree-sitter-langs/ doesn’t seem to be a git working dir. Grammar-building functions will not work.
tree-sitter-langs: Grammar bundle v0.12.4 was already installed; skipped
Doom loaded 279 packages across 51 modules in 2.560s
Package cl is deprecated
[yas] Check your `yas-snippet-dirs': /home/wulfalpha/.config/doom/snippets/ is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
Making before-save-hook buffer-local while locally let-bound!
org-babel-exp process python at position 156...
org-babel-exp process python at position 334...
org-babel-exp process python at position 972...
Wrote /home/wulfalpha/Documents/Projects/PythonClass/CSAssignment4.md
"CSAssignment4.md" 50L, 1113C written
Preview ‘/home/wulfalpha/Documents/Projects/PythonClass/CSAssignment4.org’ on http://localhost:14643
Starting new Ispell process aspell with default dictionary...done
Process ‘grip-14643’ killed
Making before-save-hook buffer-local while locally let-bound!
org-babel-exp process python at position 156...
org-babel-exp process python at position 334...
org-babel-exp process python at position 972...
Wrote /home/wulfalpha/Documents/Projects/PythonClass/CSAssignment4.md
"CSAssignment4.md" 50L, 1113C written
Reverting buffer ‘PythonClass’.
Preview ‘/home/wulfalpha/Documents/Projects/PythonClass/CSAssignment4.org’ on http://localhost:18277
Quit
Error in post-command-hook (evil-ex-abort): (user-error "No recursive edit is in progress")
Quit [2 times]
Debug on Error enabled globally
End of buffer
Beginning of buffer [7 times]
```

**Comment by seagle0128** [comment]
The related configurations are not changed. I confirm it works in my local env. Please check your private configurations.

**Comment by wulfalpha** [comment]
Shoot guess i'm back to square 1 then. Grip command line does work. and I tried a new access token but that didn't help either. Does it prefer the auth info in settings.py in the grip directory? like will that overwrite what i have in my config?

**Comment by wulfalpha** [comment]
also to be clear. I AM trying to use grip   on an org document. If it helps

**Comment by wulfalpha** [comment]
but the same thing happens on a regular markdown file

**Comment by seagle0128** [comment]
I am pretty sure `grip-mode` works well for both markdown and org files.
