### ISSUE TITLE
[Bug] org-agenda does not get all the todos from the org files generated by org-roam

### ISSUE THREAD

**Issue by rainstormstudio** [seagle0128/.emacs.d#374]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

When using org-roam to capture some nodes, org-agenda cannot recognize those newly generated nodes and thus cannot gather all of the todos in the org-roam nodes.

### Steps to reproduce

1. call `M-x org-roam-capture` or `M-x org-roam-dailies-capture-today`
2. add `* TODO a new task` and possibly add a schedule/deadline as well
3. `C-c C-c` to save the new node

### Expected behavior

`C-c a` or call `M-x org-agenda` to open org-agenda and press `t` to see List of all TODO entries. It should show the new node we just created `TODO a new task`

### OS

Windows

### Emacs Version

28

### Anything else

My understanding is that `org-agenda-files` does not have the correct values. After setting `org-agenda-files (list centaur-org-directory (format "%s/%s" centaur-org-directory "daily") (format "%s/%s" centaur-org-directory "roam"))` in the `.emacs.d/lisp/init-org.el`, this issue will be solved. Basically `org-agenda-files` originally did not include `daily` and `roam` folders under `centaur-org-directory`

**Comment by seagle0128** [comment]
I added `roam` path, but it seems `daily` path is not common.

**Comment by rainstormstudio** [comment]
It seems `daily` is used for `M-x org-roam-dailies-capture-today`. Sometimes I use it for keeping track of daily tasks. This could be personal tastes so I think adding `roam` is enough.

**Comment by chejingchi** [comment]
i have the same problem. I changed org-agenda-files in custom.el，but it wont be in use.How can I change it in custom

**Comment by seagle0128** [comment]
@chejingchi try `(with-after-load 'org)`
