### ISSUE TITLE
[Bug] lsp-headerline-breadcrumb-path-face giving `nil`

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#375]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Debugger entered--Lisp error: (error "Invalid face underline" :style wave :color nil)
  internal-set-lisp-face-attribute(lsp-headerline-breadcrumb-path-error-face :underline (:style wave :color nil) #<frame F1 0xa5f910>)
  set-face-attribute(lsp-headerline-breadcrumb-path-error-face #<frame F1 0xa5f910> :underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face)
  apply(set-face-attribute lsp-headerline-breadcrumb-path-error-face #<frame F1 0xa5f910> (:underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face))
  face-spec-set-2(lsp-headerline-breadcrumb-path-error-face #<frame F1 0xa5f910> (:underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face))
  face-spec-recalc(lsp-headerline-breadcrumb-path-error-face #<frame F1 0xa5f910>)
  face-spec-set(lsp-headerline-breadcrumb-path-error-face ((t :underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face)))
  apply(face-spec-set (lsp-headerline-breadcrumb-path-error-face ((t :underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face))))

### Steps to reproduce

Get latest version of LSP-MODE and restart emacs with `--debug-init`

### Expected behavior

no errors at start-up

### OS

MacOS

### Emacs Version

28

### Error callstack

```emacs-lisp
Debugger entered--Lisp error: (error "Invalid face underline" :style wave :color nil)
internal-set-lisp-face-attribute(lsp-headerline-breadcrumb-path-error-face :underline (:style wave :color nil) #<frame F1 0xa5f910>)
set-face-attribute(lsp-headerline-breadcrumb-path-error-face #<frame F1 0xa5f910> :underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face)
apply(set-face-attribute lsp-headerline-breadcrumb-path-error-face #<frame F1 0xa5f910> (:underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face))
face-spec-set-2(lsp-headerline-breadcrumb-path-error-face #<frame F1 0xa5f910> (:underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face))
face-spec-recalc(lsp-headerline-breadcrumb-path-error-face #<frame F1 0xa5f910>)
face-spec-set(lsp-headerline-breadcrumb-path-error-face ((t :underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face)))
apply(face-spec-set (lsp-headerline-breadcrumb-path-error-face ((t :underline (:style wave :color nil) :inherit lsp-headerline-breadcrumb-path-face))))
```

### Anything else

Github actions are also failing due to same issue - 

https://github.com/seagle0128/.emacs.d/actions/runs/3478740965/jobs/5816461524

**Comment by seagle0128** [comment]
Closed by afb8fb62f265aaf3f57d9170f7d0747d14fa4a2c .
