### ISSUE TITLE
[Bug] emacs hang on startup

### ISSUE THREAD

**Issue by darkhandz** [seagle0128/.emacs.d#379]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

I am using Emacs For Windows which is download from [official site](http://mirror-hk.koddos.net/gnu/emacs/windows/emacs-28/emacs-28.1.zip).
I clone the repo and then open runemacs.exe, then emacs has no response(even I hit C-g), and the ram grows endless(more than 32GB).
I had tried enable centaur-proxy with clash-for-windows or switch to tuna/emacs-cn, but nothing changed.
If i run` emacs -Q -l ~/.emacs.d/init-mini.el`, I can see the plain emacs window with text content, everything seems good.

![image](https://user-images.githubusercontent.com/2143333/204101272-48304c68-cca3-432b-b5ed-cfccc8f620fe.png)

### Steps to reproduce

1. Extract emacs-28.2.zip to D:\emacs, add D:\emacs\bin to env PATH
2. git clone --depth 1 https://github.com/seagle0128/.emacs.d.git %HOME%\.emacs.d
3. open runemacs.exe

### Expected behavior

download dependency packages, then back to work.

### OS

Windows

### Emacs Version

28

**Comment by seagle0128** [comment]
Check your network connection, please. You may need VPN.

**Comment by darkhandz** [comment]
I also try many times under VPN network, but still not work.

**Comment by seagle0128** [comment]
Many packages will be pulled from GitHub during the startup. If you still fail to start Emacs, try another VPN, or change to the melpa mirror (refer to the `custom.el`), and/or disable init-reader and init-shell if you are using macOS or Linux.

**Comment by darkhandz** [comment]
I see, but my VPN is reliable (company use, for chrome cast test), so I think that's not a network issue, maybe related to Windows.
I also tried set to 'melpa, still same issue.
I will try again on WSL later.

**Comment by seagle0128** [comment]
>I also tried set to 'melpa, still same issue.

Did you try other mirror? Not 'melpa.

**Comment by darkhandz** [comment]
On WSL2，I try to use tuna mirror, Emacs hang for a few minutes, and the memory use will raise up to 8GB，but finally the installation done.
![image](https://user-images.githubusercontent.com/2143333/206895156-713c9a7d-bde7-485f-88a1-d4f64fdcc731.png)

**Comment by seagle0128** [comment]
@darkhandz It's as designed during the installation.

**Comment by seagle0128** [comment]
@darkhandz I did some optimizations recently. Please try the latest version. It will provide more information even when the init-file breaks the startup.
