### ISSUE TITLE
Some problems:

### ISSUE THREAD

**Issue by xircon** [seagle0128/.emacs.d#38]
Using chemacs (https://github.com/plexus/chemacs) to test out different configurations and I am getting some weird problems.

+ I added some code to custom.el:
```
(set-face-foreground 'font-lock-comment-face  "Purple")
(set-face-attribute 'font-lock-comment-face nil :bold t)
(set-face-background 'region "Dark blue")
(set-face-background 'mode-line "red") ;; << This line is just to test I wasn't going mad :D
```
It doesn't load, but it works if I evaluate the code in the scratch buffer.

+ Tried to turn on the dashboard per instructions - it never turns on.

+ I get a weird message on shut down
```
Current desktop was not loaded from a file. Overwrite this desktop file? (y or n)
```
Have to enter "y" to quit.

### Other than that, love what you have done it is so organized :D 

I launch Emacs with:
```
emacs --with-profile centaur &> /dev/null &
```
I cloned centaur to ```~/.centaur.d```
I have checked and the emacs user directory is set correctly and anyway everything else seems to run OK so far.

**Comment by seagle0128** [comment]
> (set-face-foreground 'font-lock-comment-face  "Purple")
(set-face-attribute 'font-lock-comment-face nil :bold t)
(set-face-background 'region "Dark blue")
(set-face-background 'mode-line "red") ;; << This line is just to test I wasn't going mad :D

You should add these codes in `custom-post.el` or in `after-load-theme-hook`.

> Tried to turn on the dashboard per instructions - it never turns on.
`(setq centaur-dashboard t)` should work.

> Current desktop was not loaded from a file. Overwrite this desktop file? (y or n)
Update the configurations and try again. It was addressed already.

**Comment by seagle0128** [comment]
Do you still have questions or issues? I'd like close it since there is no update recently.

**Comment by xircon** [comment]
Apologies, been moving house and it took forever to get connected to the internet.

Thank you!!
