### ISSUE TITLE
[Bug] jit-lock-fontify-now consumes a lot of cpu, hangs buffer

### ISSUE THREAD

**Issue by acdoussan** [seagle0128/.emacs.d#382]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

When editing a file I get random hangs, think I have traced this down to jit-lock-fontify-now. I primarily notice this in "large" buffers, I suspect this is trying to fontify the whole buffer every time a "bulk" change is made.

```
- redisplay_internal (C function)                                 786  68%
 - jit-lock-function                                              781  67%
  - jit-lock-fontify-now                                          781  67%
   - jit-lock--run-functions                                      781  67%
    - run-hook-wrapped                                            781  67%
     - #<compiled 0x34ca921>                                      781  67%
      - font-lock-fontify-region                                  781  67%
       - font-lock-default-fontify-region                         781  67%
        - font-lock-fontify-keywords-region                       780  67%
         - eval                                                   746  64%
          - prog1                                                 745  64%
           - progn                                                745  64%
            - typescript--backward-to-parameter-list              745  64%
             - looking-back                                       744  64%
              - re-search-backward                                744  64%
               - apply                                            744  64%
                  ad-Advice-re-search-backward                    744  64%
             + re-search-backward                                   1   0%
          + save-excursion                                          1   0%
         + typescript--class-decl-matcher                          14   1%
         + re-search-forward                                       11   0%
         + typescript--jsdoc-empty-tag-matcher                      1   0%
         + #<compiled 0x18e7715>                                    1   0%
         + typescript--jsdoc-param-matcher                          1   0%
         + #<compiled 0x18d73d5>                                    1   0%
           rainbow-delimiters--propertize                           1   0%
         + typescript--jsdoc-typed-tag-matcher                      1   0%
         + typescript--jsdoc-arg-tag-matcher                        1   0%
 + eval                                                             5   0%
+ command-execute                                                 280  24%
+ ...                                                              80   6%
+ timer-event-handler                                               1   0%
  undo-auto--add-boundary                                           1   0%
+ flycheck-maybe-display-error-at-point-soon                        1   0%
+ yas-maybe-expand-abbrev-key-filter                                1   0%

```

### Steps to reproduce

work in a large TS file (3k+ lines) (im using TypeScript Mode) paste some code that does not have the right indentation, and then try to auto intent all of it by selecting it with C + Space, and pressing tab once it is all selected (im able to reproduce with ~10 lines).

### Expected behavior

auto indent happens "instantly" as it used to (basically no lag).

### OS

Linux

### Emacs Version

27

### Anything else

emacs version is 27.2

$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
HOME_URL="https://amazonlinux.com/"

**Comment by acdoussan** [comment]
this is actually happening to me now whenever I make any edit to the file, don't have to paste / auto indent, adding a blank line still causes a hang / makes editing the file almost impossible

**Comment by acdoussan** [comment]
disabling `jit-lock-mode` seems to fix it, but it looks like this disables all syntax highlighting?

**Comment by acdoussan** [comment]
looks like it might just be a TS mode problem https://github.com/emacs-typescript/typescript.el#good-news

https://github.com/emacs-typescript/typescript.el/issues/166

**Comment by acdoussan** [comment]
pretty sure its TS mode related, not seeing the same behavior in `web-mode` on a .tsx file

**Comment by acdoussan** [comment]
should we consider using https://github.com/emacs-typescript/typescript.el/blob/feature/tsx-support/typescript-tree-sitter.el for TS files, rather than `typescript-mode` as it is basically deprecated?

**Comment by seagle0128** [comment]
Try `tree-sitter`. And in 29, the native tree-sitter is supported.

**Comment by acdoussan** [comment]
Should `tree-sitter` be the default for `.ts` files? I have `(setq centaur-tree-sitter t)` in my `custom.el`.

I've tried adding the following to my `custom-post.el` but doesn't appear to work / make any difference.

`(add-hook 'typescript-mode-hook #'tree-sitter-mode)` based off of https://emacs-tree-sitter.github.io/getting-started/

**Comment by acdoussan** [comment]
opened up a separate issue (https://github.com/seagle0128/.emacs.d/issues/385) probably why tree-sitter isn't working

**Comment by seagle0128** [comment]
Now `centaur-tree-sitter` is only available in 29. For 27, please see https://github.com/emacs-tree-sitter/elisp-tree-sitter. This is not supported in Centaur Emacs since it's not native in Emacs.
