### ISSUE TITLE
[Bug] Missalinged dashboard screen

### ISSUE THREAD

**Issue by HashRaygoza** [seagle0128/.emacs.d#386]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Using a fresh install directly from Github the dashboard screen text is off center, leaning to the right of the window, this happens on Emacs 28.2 on Fedora Linux

### Steps to reproduce

1. Obtain Centaur Emacs from Github with the command: git clone --depth 1 https://github.com/seagle0128/.emacs.d.git ~/.emacs.d
2. Open emacs
3. Wait until all packages are downloaded and install
4. The dashboard text is off center as show on attached screencap

### Expected behavior

The dashboard text being centered as show on the repository screencaps

### OS

Linux

### Emacs Version

28

### Anything else

An screencap of how the dashboard looks

![Captura desde 2023-01-07 10-56-47](https://user-images.githubusercontent.com/19654490/211161824-55ca842f-d8ee-4e65-ac2e-6cfed35058fd.png)

**Comment by seagle0128** [comment]
@jcs090218 is the maintainer of [emacs-dashboard](https://github.com/emacs-dashboard/emacs-dashboard). Could you please take a look at this issue?

**Comment by HashRaygoza** [comment]
Thank you, it seems to be a problem with a third party dependency, I'll wait for an update from their side
