### ISSUE TITLE
[Bug] custom-initialize-reset: Symbol’s value as variable is void: doom-modeline-ellipsisWarning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.

### ISSUE THREAD

**Issue by acdoussan** [seagle0128/.emacs.d#389]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Reinstalled this morning, I get the following error when opening emacs.

```
custom-initialize-reset: Symbol’s value as variable is void: doom-modeline-ellipsisWarning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.
```

Appears this causes my custom-post.el to not run at all. Looks like the CI is failing since yesterday as well?

### Steps to reproduce

install latest commit, open emacs, get error in messages.

### Expected behavior

no error, custom-post loads correctly.

### OS

Linux

### Emacs Version

29

**Comment by acdoussan** [comment]
as a side note, should I clone using a tag, rather than just pulling the latest from mainline every time I install? Might be worth updating the quick start guide to mention that tags are available if you want a repeatable version, didn't know they were there

**Comment by acdoussan** [comment]
example command using a tag
```
git clone --depth 1 --branch v6.0.0 https://github.com/seagle0128/.emacs.d.git ~/.emacs.d
```

**Comment by seagle0128** [comment]
>custom-initialize-reset: Symbol’s value as variable is void: doom-modeline-ellipsis

The latest `doom-modeline`  has fixed this issue.

>Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.

It comes out from `doom-themes`. Report to the upstream or just ignore.
