### ISSUE TITLE
[Bug] Emacs hang on first startup with contacting host: github.com:443

### ISSUE THREAD

**Issue by HapCoderWei** [seagle0128/.emacs.d#390]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

OS: OSX 12.6.3
Kernal : Darwin 192.168.1.5 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64
emacs version : GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2021-03-27

After emacs first startup on this .emacs.d, I start emacs again and it always hang on startup with minibuffer display

> Contacting host: github.com:443

I also tried to set the proxy in custom.el and enable it, but seems not work, it still hang on there. My proxy server is ok, i can use is normally in Chrome. Below is the screenshot and \*Message\* buffer log:
<img width="580" alt="截屏2023-02-19 10 30 16" src="https://user-images.githubusercontent.com/6915031/219908947-01666aba-86cb-41a1-ba5a-170249d53034.png">
<img width="1137" alt="截屏2023-02-19 10 31 12" src="https://user-images.githubusercontent.com/6915031/219908938-ade38724-b21c-486e-8744-ee2b3fc2ed97.png">

Could you please give some help, Thanks a lot for your work👍

### Steps to reproduce

Clone emacs.d to my home directory, and start emacs gui. After it finished install and compile, type C-x C-c and restart emacs again, then it shows this issue.

### Expected behavior

Expect emacs second start normally and can be used with all things done. Or the proxy set works well, and network access can go though with proxy.

### OS

MacOS

### Emacs Version

27

**Comment by seagle0128** [comment]
Try just using http proxy while not enabling both http and socks proxy.

**Comment by HapCoderWei** [comment]
Wow, you are right. After set http proxy only, the network access goes without hang there. Thanks Again! 👍
