### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lumy** [seagle0128/.emacs.d#391]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Can't set shift key for windmove using customize command.

### Steps to reproduce

git clone v6.0.0 of this repo.
use customize and modify windmove related param.
do the same to uman shift-select-mode.
ending up with a custom.el like this:
```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(go-autocomplete go-complete go-eldoc go-fill-struct go-imports go-mode gnugo))
 '(shift-select-mode nil)
 '(windmove-allow-all-windows t)
 '(windmove-default-keybindings '([ignore] shift))
 '(windmove-mode t))
```

### Expected behavior

Windmove should be mapped on shift+arrow key 

### OS

Linux

### Emacs Version

28

**Comment by seagle0128** [comment]
Add this to `custom-post.el`.
```elisp
(windmove-default-keybindings 'shift)
```
