### ISSUE TITLE
启动时会链接github，在没有网络的时候会卡着不动，有什么好办法吗

### ISSUE THREAD

**Issue by uphiel** [seagle0128/.emacs.d#392]

**Comment by seagle0128** [comment]
Please provide more details.

My suggestion is using proxy or githubhosts.

**Comment by uphiel** [comment]
Your solution is a situation with a network, but a situation without a network? If you can't open it, you can't use it。

**Comment by seagle0128** [comment]
Does `C-g` work?
You need to provide which packages or when hangs exactly. I guess pdf-tools causes it. You can comment it

**Comment by uphiel** [comment]
Ok,Thanks
