### ISSUE TITLE
[Bug] Term C-c o is not bound to ace-window/other-window

### ISSUE THREAD

**Issue by ketakopter** [seagle0128/.emacs.d#393]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

When changing windows, I use `C-x o`, which is bound to `ace-window`. If I'm in a terminal window (e.g. starting it with `M-x term`) in character mode, usually key bindings are translated to `C-c`, for example I can switch to buffer using `C-c b`. However, `C-c o` runs `counsel-outline` and I found no way to change to another window using keybindings.

### Steps to reproduce

- `M-x term`
- `C-c o`

### Expected behavior

With `C-c o` in terminal mode, I would expect to run `ace-window` or `other-window`.

### OS

Linux

### Emacs Version

28

**Comment by seagle0128** [comment]
Thanks for reporting!

`vterm` is recommended in Centaur Emacs. If you still prefer `term` , you should unbind keybindings of `counsel-mode` in `term-mode`.
