### ISSUE TITLE
[Bug]  The highlight-indet-guides-mode is enabled in the terminal mode, and the buffer division cannot be aligned

### ISSUE THREAD

**Issue by yxing-xyz** [seagle0128/.emacs.d#395]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

The highlight-indet-guides-mode is enabled in the terminal mode, and the buffer division cannot be aligned.
开启highlight-indet-guides-mode，终端模式下，文字不能对齐.
![image](https://user-images.githubusercontent.com/19182789/226893235-cc3b6cbf-b24c-4bf3-a958-23236913d005.png)

### Steps to reproduce

1. SSH into the server, start emacs, and open the go project
2. Window split

### Expected behavior

none

### OS

Linux

### Emacs Version

28

**Comment by seagle0128** [comment]
Please try other fonts or terminals, and check the results.

**Comment by yxing-xyz** [comment]
Mac alacritty and melo fonts also have problems, I'd better turn off the mirro mode. 
![image](https://user-images.githubusercontent.com/19182789/227137209-2701e61a-2eea-43c9-8e7a-708e0b593374.png)

**Comment by seagle0128** [comment]
What is `mirror-mode`? Does it cause the issue?

**Comment by yxing-xyz** [comment]
The highlight-indent-guides-mode in the terminal text mode causes the sub-screen of the function {} symbol to be misaligned.

**Comment by yxing-xyz** [comment]
There are problems with the st terminal under linux, alacritty and iterm under mac. The font has tried menlo and CodeNewRoman Nerd

**Comment by yxing-xyz** [comment]
大佬的键映射很优雅。只是有的绑定用Ctrl+特殊字符就不能被虚拟终端发送出去了。
Ctrl+特殊字符是超出虚拟终端控制序列，比如`ctrl + :` 的`avy-goto-char`就没办法在终端用，需要重新映射.
