### ISSUE TITLE
[Bug] 打开 treemacs的帮助后，出现如下错误

### ISSUE THREAD

**Issue by chengyi** [seagle0128/.emacs.d#396]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

打开treemacs的帮助后，尝试关闭，出现
Window #<window 17 on  *LV*> has same side left as window #<window 15 on  *Treemacs-Scoped-Buffer-No Perspective*> but no common parent
并无法关闭任何window

### Steps to reproduce

1. press `C-x t t` to open treemacs
2. press `?` in treemacs window to open help
3. press `esc` try to close help window

### Expected behavior

能够正常的关闭treemacs 的help window
不出现错误

### OS

Linux

### Emacs Version

gccemacs-28

**Comment by seagle0128** [comment]
I couldn't reproduce this issue following by the steps above, on both Windows and macOS.

**Comment by chengyi** [comment]
> I couldn't reproduce this issue following by the steps above, on both Windows and macOS.

after I update packages, this bug is fixed.
