### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sirius00** [seagle0128/.emacs.d#397]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

我在安装之后，打开 emacs 之后
出现如下：
Compiling file /Users/cobb/.emacs.d/elpa/restclient-20221203.1808/restclient.el at Tue Apr 11 16:29:26 2023
Entering directory ‘/Users/cobb/.emacs.d/elpa/restclient-20221203.1808/’

Compiling internal form(s) at Tue Apr 11 16:29:27 2023
Error (bytecomp): Invalid image type ‘svg’ [15 times]
Warning (bytecomp): custom-declare-variable `dumb-jump-window' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-use-visible-window' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-selector' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-ag-cmd' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-rg-cmd' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-git-grep-cmd' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-ag-word-boundary' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-rg-word-boundary' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-git-grep-word-boundary' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-grep-word-boundary' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-fallback-regex' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-max-find-time' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-git-grep-search-untracked' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-find-rules' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `dumb-jump-project' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters [2 times]
Warning (bytecomp): Use -zip-pair instead of -zip to get a list of pairs
Warning (bytecomp):  docstring wider than 80 characters [6 times]
Warning (bytecomp): reference to free variable ‘find-tag-marker-ring’
Warning (bytecomp):  docstring wider than 80 characters [8 times]
Warning (bytecomp): the function ‘first’ is not known to be defined.
Warning (bytecomp): the function ‘tramp-dissect-file-name’ is not known to be defined.
Warning (bytecomp): the function ‘tramp-file-name-localname’ is not known to be defined.
Warning (bytecomp): the function ‘helm-make-source’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘end’
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): Use keywords rather than deprecated positional arguments to `define-minor-mode'
Warning (bytecomp): global/dynamic var ‘groovysh’ lacks a prefix
Warning (bytecomp): defvar `lua-electric-flag' docstring wider than 80 characters
Warning (bytecomp): defconst `lua-block-token-alist' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `plantuml-default-exec-mode' docstring wider than 80 characters
Warning (bytecomp): defcustom for ‘plantuml-indent-level’ fails to specify type [2 times]
Warning (bytecomp): defvar `plantuml-exec-mode' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters [10 times]
Warning (bytecomp): Unused lexical argument `status'
Warning (bytecomp):  docstring wider than 80 characters [2 times]
Warning (bytecomp): defvar `plantuml-indent-regexp-group-start' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): reference to free variable ‘plantuml-indent-regexp-end’
Warning (bytecomp): reference to free variable ‘plantuml-indent-regexp-start’
Warning (bytecomp): custom-declare-variable `scala-compile-always-ask' docstring wider than 80 characters
Warning (bytecomp): defconst `scala-mode-pretty-categories-alist' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters [4 times]
Warning (bytecomp): ‘next-line’ is for interactive use only; use ‘forward-line’ instead.
Warning (bytecomp): ‘easy-menu-add’ is an obsolete function (as of 28.1); this was always a no-op in Emacs and can be safely removed.
Warning (bytecomp): the function ‘ignore-case’ is not known to be defined.
Warning (bytecomp): the function ‘meta’ is not known to be defined.
Warning (bytecomp): the function ‘candidates’ is not known to be defined.
Warning (bytecomp): the function ‘prefix’ is not known to be defined.
Warning (bytecomp): the function ‘case’ is not known to be defined.
Warning (bytecomp):  docstring wider than 80 characters [2 times]
Warning (bytecomp): custom-declare-variable `highlight-defined-face-use-itself' docstring wider than 80 characters
Warning (bytecomp): indirect-function called with 2 arguments, but accepts only 1 [2 times]
Warning (bytecomp): Use -zip-pair instead of -zip to get a list of pairs
Warning (bytecomp): Unused lexical variable `symbols-with-pos-enabled'
Warning (bytecomp): the function ‘symbol-with-pos-pos’ is not known to be defined.
Warning (bytecomp): the function ‘symbol-with-pos-p’ is not known to be defined.
Warning (bytecomp): ‘elisp-eldoc-documentation-function’ is an obsolete function (as of 28.1); use ElDoc’s interfaces instead.
Warning (bytecomp): Use -zip-pair instead of -zip to get a list of pairs
Warning (bytecomp): help-fns--autoloaded-p called with 1 argument, but requires 2
Warning (bytecomp): Use keywords rather than deprecated positional arguments to `define-minor-mode'
Warning (bytecomp): Empty let* body
Warning (bytecomp): ‘go-guess-gopath’ is an obsolete function (as of 1.7.0); GOPATH has been deprecated in favour of Go modules.
Warning (bytecomp): the function ‘go-end-of-defun’ is not known to be defined.
Error (bytecomp): Unable to find ‘go’ in ‘exec-path’!
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp):  docstring wider than 80 characters [2 times]
Warning (bytecomp): Unused lexical argument `arg'
Warning (bytecomp): assignment to free variable ‘command’
Warning (bytecomp): reference to free variable ‘command’
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): Unused lexical argument `arg'
Warning (bytecomp): Unused lexical argument `proc'
Warning (bytecomp): Unused lexical argument `msg'
Warning (bytecomp): global/dynamic var ‘eglot’ lacks a prefix [2 times]
Warning (bytecomp): reference to free variable ‘flycheck-error-list-buffer’
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): the function ‘flycheck-list-errors’ is not known to be defined.
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): Unused lexical argument `msg'
Warning (bytecomp): reference to free variable ‘poly-rustic-cargo-compilation-hostmode’
Warning (bytecomp): reference to free variable ‘poly-rustic-cargo-comint-innermode’
Warning (bytecomp): reference to free variable ‘rustic-cargo-comint-run-mode’
Warning (bytecomp): the function ‘define-polymode’ is not known to be defined.
Warning (bytecomp): the function ‘define-innermode’ is not known to be defined.
Warning (bytecomp): the function ‘define-hostmode’ is not known to be defined.
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): reference to free variable ‘rustic-compilation-workspace’
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp): global/dynamic var ‘eglot’ lacks a prefix
Warning (bytecomp): the function ‘eglot--TextDocumentPositionParams’ is not known to be defined.
Warning (bytecomp): the function ‘eglot--current-server-or-lose’ is not known to be defined.
Warning (bytecomp): the function ‘jsonrpc-request’ is not known to be defined.
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp): custom-declare-variable `rustic-flycheck-clippy-params-stable' docstring wider than 80 characters
Warning (bytecomp): custom-declare-variable `rustic-flycheck-clippy-params-nightly' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): Unused lexical argument `server'
Warning (bytecomp): reference to free variable ‘eglot--{}’
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp): the function ‘eglot-rust-analyzer--eieio-childp’ is not known to be defined.
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp): value returned from (file-exists-p src-path) is unused
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp): ‘project-roots’ is an obsolete function (as of 0.3.0); use ‘project-root’ instead.
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp): Unused lexical variable `spellcheck-command'
Warning (bytecomp): the function ‘inheritenv-apply’ is not known to be defined.
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): ‘lsp-after-diagnostics-hook’ is an obsolete variable (as of lsp-mode 6.4); use ‘lsp-diagnostics-updated-hook’ instead.
Warning (bytecomp): defgroup for ‘rust-playground’ fails to specify containing group
Warning (bytecomp): custom-declare-variable `rust-playground-confirm-deletion' docstring wider than 80 characters
Warning (bytecomp): defcustom for ‘rust-playground-cargo-toml-template’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘rust-playground-main-rs-template’ fails to specify type
Warning (bytecomp): custom-declare-variable `rust-playground-main-rs-template' docstring wider than 80 characters
Warning (bytecomp): defcustom for ‘rust-playground-main-rs-template’ fails to specify type
Warning (bytecomp):  docstring wider than 80 characters [2 times]
Warning (bytecomp): defface for ‘rbenv-active-ruby-face’ fails to specify containing group
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): defcustom for ‘global-rbenv-mode’ fails to specify containing group [2 times]
Warning (bytecomp): ‘ruby-backward-sexp’ is an obsolete function (as of 28.1); use ‘backward-sexp’ instead.
Warning (bytecomp): Package cl is deprecated
Warning (bytecomp):  docstring wider than 80 characters [3 times]
Warning (bytecomp): defcustom for ‘yari-ri-program-name’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘yari-ruby-program-name’ fails to specify type [2 times]
Warning (bytecomp): ‘assert’ is an obsolete alias (as of 27.1); use ‘cl-assert’ instead.
Warning (bytecomp): the function ‘helm’ is not known to be defined.
Warning (bytecomp): the function ‘anything’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘ido-decorations’
Warning (bytecomp):  docstring wider than 80 characters [2 times]
Warning (bytecomp): ‘goto-line’ is for interactive use only; use ‘forward-line’ instead. [2 times]
Warning (bytecomp): the function ‘sql-comint’ is not known to be defined.
Warning (bytecomp): the function ‘sql-set-product-feature’ is not known to be defined.
Warning (bytecomp): the function ‘sql-get-product-feature’ is not known to be defined.
Warning (bytecomp): looking-back called with 1 argument, but requires 2-3 [3 times]
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): reference to free variable ‘css-mode-syntax-table’
Warning (bytecomp): ‘flymake-init-create-temp-buffer-copy’ is an obsolete function (as of 26.1); use ‘flymake-proc-init-create-temp-buffer-copy’ instead.
Warning (bytecomp): ‘flymake-allowed-file-name-masks’ is an obsolete variable (as of 26.1); use ‘flymake-proc-allowed-file-name-masks’ instead. [2 times]
Warning (bytecomp): ‘flymake-err-line-patterns’ is an obsolete variable (as of 26.1); use ‘flymake-proc-err-line-patterns’ instead. [2 times]
Warning (bytecomp): defvar `jsons-parsed-regions' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): value returned from (match-end 0) is unused [3 times]
Warning (bytecomp):  docstring wider than 80 characters [3 times]
Warning (bytecomp): defvar `js2-typed-array-externs' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters [2 times]
Warning (bytecomp): the function ‘rxt--re-builder-switch-pcre-mode’ might not be defined at runtime.
Warning (bytecomp): defconst `typescript--type-name-re' docstring wider than 80 characters
Warning (bytecomp): defvar `typescript--quick-match-re-func' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters [3 times]
Warning (bytecomp): ‘font-lock-fontify-buffer’ is for interactive use only; use ‘font-lock-ensure’ or ‘font-lock-flush’ instead.
Warning (bytecomp): ‘syntax-begin-function’ is an obsolete variable (as of 25.1).
Warning (bytecomp): the function ‘flyspell-generic-progmode-verify’ is not known to be defined.
Warning (bytecomp): the function ‘indium-connect-to-nodejs’ is not known to be defined.
Warning (bytecomp): the function ‘realgud:nodejs’ is not known to be defined.
Warning (bytecomp): Unused lexical variable `end' [6 times]
Warning (bytecomp): the function ‘web-mode-part-args-beginning’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘ruby-font-lock-syntax-table’
Warning (bytecomp): reference to free variable ‘textile-mode-syntax-table’
Warning (bytecomp): reference to free variable ‘font-lock-beg’
Warning (bytecomp): reference to free variable ‘font-lock-end’
Warning (bytecomp): assignment to free variable ‘font-lock-beg’
Warning (bytecomp): assignment to free variable ‘font-lock-end’
Warning (bytecomp): custom-declare-variable `restclient-vars-max-passes' docstring wider than 80 characters
Warning (bytecomp):  docstring wider than 80 characters
Warning (bytecomp): Unused lexical argument `args'
Warning (bytecomp):  docstring wider than 80 characters
显示这些内容，而我也已经在custom.el 文件中打开了 dashboard，但是完全不显示，求助该如何解决

### Steps to reproduce

1. git 安装配置
2. 打开 emacs

### Expected behavior

能够正常显示 dashboard

### OS

MacOS

### Emacs Version

28

**Comment by sirius00** [comment]
![CleanShot 2023-04-11 at 19 48 58](https://user-images.githubusercontent.com/45954864/231153915-7a4fa2a2-7f9f-48ac-9204-92e34da53bd4.png)
还有这些信息

**Comment by seagle0128** [comment]
Please see your `system-configuration-features`, check if there is "RSVG".
Recommend to use [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus).

**Comment by xlmo** [comment]
安装  librsvg， 然后重新编译Emacs。

Ubuntu下  `sudo` apt install librsvg2-dev`
