### ISSUE TITLE
[Bug] Cannot start emacs

### ISSUE THREAD

**Issue by rif** [seagle0128/.emacs.d#398]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

I get this error when starting emacs after an centaur-update.

face-attribute: Error during redisplay: (substitute-command-keys "Symbol's function definition is void") signaled (void-function funncall) 

I can only use emacs if I comment out (require 'init-ivy)  

### Steps to reproduce

Update all the packages and start centaur emacs. It might be that a external package is broken

### Expected behavior

Be able to start emacs

### OS

Linux

### Emacs Version

28

### Error callstack

```emacs-lisp
how do I reproduce the error with toggle-debug-on-error?
```

**Comment by seagle0128** [comment]
1. Try using `emacs --debug-init` to start for troubleshooting.
2. Try reinstalling ivy and related packages.

**Comment by rif** [comment]
I am starting emacs in the terminal only as I am on Wayland and I don't have emacs 29 yet

**Comment by seagle0128** [comment]
Upgrade  `all-the-icons-ivy-rich` to the latest. Try it after a few hours. See https://github.com/seagle0128/all-the-icons-ivy-rich/issues/34.
