### ISSUE TITLE
org-roam show "finalizer failed: (wrong-type-argument sqlitep nil)"

### ISSUE THREAD

**Issue by WindWang2** [seagle0128/.emacs.d#399]
After toggle the org-roam-db-autosync-mode (enable), the Message buffer will report "finalizer failed: (wrong-type-argument sqlitep nil)".
 The config file is default without any modification.

Test on archlinux and Mac.

I do not figure out whether it is bug or not.

M-x org-roam-db-autosync-mode (disable to enable)
```
Clearing removed files...done
Processing modified files...done
finalizer failed: (wrong-type-argument sqlitep nil)
```

**Comment by OrionRandD** [comment]
I am also having this issue => finalizer failed: (wrong-type-argument sqlitep nil)

And I have already purged  emacsql, reinstalled and recompiled...
And the error appears again.
So, seems to be a bug...

**Comment by seagle0128** [comment]
Can anyone provide the backtrace or something else?

**Comment by iris-garcia** [comment]
Also having this issue

**Comment by OrionRandD** [comment]
> Also having this issue

The issue here is no more. After recompiling my emacs packages...
Perhaps, try to delete it, reinstall and recompile.

**Comment by meedstrom** [comment]
Thank you. I tried to recompile, but that didn't work. Total reinstallation did.
