### ISSUE TITLE
Please consider the computer with small-capacity RAM

### ISSUE THREAD

**Issue by ReimuXMX** [seagle0128/.emacs.d#4]
Hello, and sorry for my poor English.

I am a new in Emacs, So I don't understand the principle.

But what I see is:
Your configuration runs on the computer with 2G RAM will be error.

Emacs version: 25.2
OS: Arch Linux x86_64
Hardware: VirtualBox 5.1.26 VM

Thanks.

**Comment by ReimuXMX** [comment]
Thank you for your warm reply!

This error occurs from time to time and occurs only when a large number of third-party packages are being installed after the first startup.

This is a screenshot:
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/26828933/30423478-84e9284e-9975-11e7-9a12-864ffa6ea8ce.png">

I'm sorry I can't provide text version of the error message. Because Emacs was dead ...

Thanks again for your reply~~

**Comment by seagle0128** [comment]
Try `emacs --debug-init` to get more details and attach here.
If possible, please try to add more memory for the VM and try again.

**Comment by ReimuXMX** [comment]
Well...this question may have no solution ...

My VM is limited. It **CAN NOT** change any hardware settings. And I have to use the Emacs with GUI.
This problem also appears on spacemacs.

**Comment by seagle0128** [comment]
Well, I was unable to reproduce in my VM. 
I think you can install the packages in console at the first startup.

In terminal 
```sh
emacs -nw --debug-init
```
Let's see what will happen.

**Comment by ReimuXMX** [comment]
These limits are artificially increased, so them is impossible to remove. Because I'm not the system administrator.

I can only start built-in commands such as `ls` from the terminal.

The screenshot for `emacs --debug-init`:
<img width="1280" alt="3" src="https://user-images.githubusercontent.com/26828933/30424837-bfa80a0a-9979-11e7-83a6-983457c2da11.png">

**Comment by seagle0128** [comment]
Oh man! That should be the administrator restricts the resource usage :(
Only built-in commands are able to be run in the terminal? If you are able to find the path of `emacs`, you should be able to run it. Please make sure if `PATH` is correct.

Otherwise, tell your admin, "Stupid! How can I work without terminal on Linux?"

**Comment by ReimuXMX** [comment]
My administrator is really stupid and pedantic, it does not matter. He never looked at GitHub, and he thought git was a monster.

If not for some special reasons, I will be  talk about this matter in the Emacs-China QQ group: Emacs @ newsmth .

**Comment by seagle0128** [comment]
I got an idea, maybe you can try this method:
Comment `(setq gc-cons-threshold 30000000)` in `init.el`, Line 55.
Or set it to small number, but >=800000.

Good luck, man!

**Comment by ReimuXMX** [comment]
Thanks!

I set it to 2000000, it works, and no burst table for RAM.

**Comment by seagle0128** [comment]
Welcome! Enjoy `Centaur Emacs` then :)
