### ISSUE TITLE
[Bug] "Wrong type argument: stringp, nil" when I try to run Emacs after installing Centaur Emacs. 

### ISSUE THREAD

**Issue by Ushio-Clover** [seagle0128/.emacs.d#400]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

After installing Centaur Emacs, I tried to start emacs and got the following error: "**Wrong type argument: stringp, nil**"
Since I'm new to emacs, I can't seem to figure out what's causing the problem by myself.

- OS: macOS 13.4 22F5049e arm64
- Shell: fish 3.6.1
- Terminal: wezterm (tmux 3.3a)
- Emacs version: 28.2*

----
I just used the default configuration for everything and didn't change the emacs configuration file myself.

### Steps to reproduce

1. When I start emacs on my terminal, the first thing that comes up is the following screen:

<img width="1728" alt="Screenshot 2023-05-01 at 10 07 39" src="https://user-images.githubusercontent.com/104703663/235392746-6a241366-61f0-4796-b0ce-08fa1c79efbe.png">

2. Soon the following error screen appears and nothing else happens.

<img width="1728" alt="Screenshot 2023-05-01 at 10 27 06" src="https://user-images.githubusercontent.com/104703663/235392834-79872083-5345-45fc-a205-011408f23e5a.png">

### Expected behavior

A normal startup page, and no errors should be reported.

### OS

MacOS

### Emacs Version

28

**Comment by Ushio-Clover** [comment]
> Try `emacs --debug-init`.

Thank you for your kindness. But nothing else happened. Is there something wrong with my operation? I tried starting emacs with the "--debug-init" parameter but it didn't return any error messages. (I run it in a terminal instead of GUI mode.)

I tried disabling **centaur-package-archives** and enabling the HTTP/HTTPS proxy, and it still didn't work.

I'm wondering if this is a problem with my network.

**Comment by seagle0128** [comment]
It seems the installation failed. I am not sure if it's due to the network issue, but try another archive mirror, e.g. ustc.

**Comment by Ushio-Clover** [comment]
> It seems the installation failed. I am not sure if it's due to the network issue, but try another archive mirror, e.g. ustc.
> 
> Updated: Please remove dap-mode in init-lsp.el or update to the latest.

@seagle0128 Thank you! Now it's working fine.
