### ISSUE TITLE
[Bug] Unable to find icon with name ‘nf-oct-primitive_dot’

### ISSUE THREAD

**Issue by chengyi** [seagle0128/.emacs.d#403]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

when doing a fresh install, it reports `Unable to find icon with name ‘nf-oct-primitive_dot’ in icon set ‘octico`

### Steps to reproduce

doing a fresh install

### Expected behavior

start without reporting error

### OS

Linux

### Emacs Version

gccemacs-28

**Comment by chengyi** [comment]
stack info:
stack info:
Debugger entered--Lisp error: (error "Unable to find icon with name ‘nf-oct-primitive_do...")
  error("Unable to find icon with name `%s' in icon set `%s..." "nf-oct-primitive_dot" octicon)
  nerd-icons-octicon("nf-oct-primitive_dot" :height 1.0 :v-adjust 0.01)
  #f(compiled-function () #<bytecode -0x15eb54ad8f2e7339>)()
  funcall(#f(compiled-function () #<bytecode -0x15eb54ad8f2e7339>))
  eval((funcall #'#f(compiled-function () #<bytecode -0x15eb54ad8f2e7339>)))
  custom-initialize-reset(dashboard-agenda-item-icon (funcall #'#f(compiled-function () #<bytecode -0x15eb54ad8f2e7339>)))
  custom-declare-variable(dashboard-agenda-item-icon (funcall #'#f(compiled-function () #<bytecode -0x15eb54ad8f2e7339>)) "Agenda item icon." :type string :group dashboard)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\304\305\306\"\210\307\310\311\312\313DD\314\315\316\317\320&\7\210\307\321\311\312\322DD\323\315\324\317\320&\7\210\307\325\311..." [require cl-lib image subr-x defalias org-time-less-p time-less-p custom-declare-variable dashboard-page-separator funcall function #f(compiled-function () #<bytecode 0x1f4000162c914>) "Separator to use between the different pages." :type string :group dashboard dashboard-image-banner-max-height #f(compiled-function () #<bytecode 0x1f400016fe914>) "Maximum height of banner image.\n\nThis setting appl..." integer dashboard-image-banner-max-width #f(compiled-function () #<bytecode 0x1f400016fe914>) "Maximum width of banner image.\n\nThis setting appli..." dashboard-set-heading-icons #f(compiled-function () #<bytecode 0x1f400016fe914>) "When non nil, heading sections will have icons." boolean dashboard-set-file-icons #f(compiled-function () #<bytecode 0x1f400016fe914>) "When non nil, file lists will have icons." dashboard-set-navigator #f(compiled-function () #<bytecode 0x1f400016fe914>) "When non nil, a navigator will be displayed under ..." dashboard-set-init-info #f(compiled-function () #<bytecode 0x1f400016fe5d4>) "When non nil, init info will be displayed under th..." dashboard-set-footer #f(compiled-function () #<bytecode 0x1f400016fe5d4>) "When non nil, a footer will be displayed at the bo..." dashboard-footer-messages #f(compiled-function () #<bytecode 0x17e4d5d8e6bd9da9>) "A list of messages, one of which dashboard chooses..." list dashboard-icon-type #f(compiled-function () #<bytecode 0x18a2d6c6a8e5910f>) "Icon type used for dashboard.\nThe value can be one..." symbol :set #f(compiled-function (k v) #<bytecode -0x382efc010f79c31>) ...] 10)
  require(dashboard-widgets)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\304\305\306\307\310\311%\207" [require ffap recentf dashboard-widgets custom-declare-group dashboard nil "Extensible startup screen." :group applications] 6)
  (dashboard-setup-startup-hook)
  (progn (use-package-ensure-elpa 'dashboard '(t) 'nil) (apply #'face-spec-set '(dashboard-heading (...))) (apply #'face-spec-set '(dashboard-items-face (...))) (apply #'face-spec-set '(dashboard-no-items-face (...))) (if (fboundp 'quit-dashboard) nil (autoload #'quit-dashboard "dashboard" nil t)) (if (fboundp 'dashboard-refresh-buffer) nil (autoload #'dashboard-refresh-buffer "dashboard" nil t)) (if (fboundp 'open-dashboard) nil (autoload #'open-dashboard "dashboard" nil t)) (if (fboundp 'previous-line) nil (autoload #'previous-line "dashboard" nil t)) (if (fboundp 'next-line) nil (autoload #'next-line "dashboard" nil t)) (if (fboundp 'widget-backward) nil (autoload #'widget-backward "dashboard" nil t)) (if (fboundp 'widget-forward) nil (autoload #'widget-forward "dashboard" nil t)) (if (fboundp 'widget-button-press) nil (autoload #'widget-button-press "dashboard" nil t)) (if (fboundp 'dashboard-goto-projects) nil (autoload #'dashboard-goto-projects "dashboard" nil t)) (if (fboundp 'dashboard-goto-bookmarks) nil (autoload #'dashboard-goto-bookmarks "dashboard" nil t)) (if (fboundp 'dashboard-goto-recent-files) nil (autoload #'dashboard-goto-recent-files "dashboard" nil t)) (if (fboundp 'dashboard-previous-section) nil (autoload #'dashboard-previous-section "dashboard" nil t)) (if (fboundp 'dashboard-next-section) nil (autoload #'dashboard-next-section "dashboard" nil t)) (if (fboundp 'find-custom-file) nil (autoload #'find-custom-file "dashboard" nil t)) (if (fboundp 'restore-session) nil (autoload #'restore-session "dashboard" nil t)) (if (fboundp 'restore-previous-session) nil (autoload #'restore-previous-session "dashboard" nil t)) (if (fboundp 'browse-homepage) nil (autoload #'browse-homepage "dashboard" nil t)) (if (fboundp 'update-config-and-packages) nil (autoload #'update-config-and-packages "dashboard" nil t)) (if (fboundp 'dashboard-hydra/body) nil (autoload #'dashboard-hydra/body "dashboard" nil t)) (setq dashboard-banner-logo-title "CENTAUR EMACS - Enjoy Programmin..." dashboard-startup-banner (or centaur-logo 'official) dashboard-page-separator "\n\f\n" dashboard-projects-backend 'project-el dashboard-path-style 'truncate-middle dashboard-path-max-length 60 dashboard-center-content t dashboard-show-shortcuts nil dashboard-items '((recents . 10) (bookmarks . 5) (projects . 5)) dashboard-set-init-info t dashboard-display-icons-p #'icons-displayable-p dashboard-icon-type 'nerd-icons dashboard-set-file-icons centaur-icon dashboard-set-heading-icons centaur-icon dashboard-heading-icons '((recents . "nf-oct-history") (bookmarks . "nf-oct-bookmark") (agenda . "nf-oct-calendar") (projects . "nf-oct-briefcase") (registers . "nf-oct-database")) dashboard-set-footer ...) (dashboard-setup-startup-hook) (eval-after-load 'dashboard #'(lambda nil (progn ... ... ... ... ... ... ... ... ... ... ... t))) (add-hook 'dashboard-mode-hook #'(lambda nil (set ... nil) (if ... ...))) (progn '(:title (pretty-hydra-title "Dashboard" ... "nf-md-view_dashboard") :color pink :quit-key ("q" "C-g") :hint nil) (progn (set (defvar dashboard-hydra/params nil "Params of dashboard-hydra.") '...) (set (defvar dashboard-hydra/docstring nil "Docstring of dashboard-hydra.") "\n\n %s(pretty-hydra-title \"Dashbo...") (set (defvar dashboard-hydra/heads nil "Heads for dashboard-hydra.") '...) (set (defvar dashboard-hydra/keymap nil "Keymap for dashboard-hydra.") '...) (set (defvar dashboard-hydra/hint nil "Dynamic hint for dashboard-hydra...") '...) (defalias 'dashboard-hydra/update-config-and-packages-and-exit #'...) (defalias 'dashboard-hydra/browse-homepage-and-exit #'...) (defalias 'dashboard-hydra/restore-previous-session-and-exit #'...) (defalias 'dashboard-hydra/restore-session-and-exit #'...) (defalias 'dashboard-hydra/find-custom-file-and-exit #'...) (defalias 'dashboard-hydra/dashboard-next-section #'...) (defalias 'dashboard-hydra/dashboard-previous-section #'...) (defalias 'dashboard-hydra/dashboard-goto-recent-files #'...) (defalias 'dashboard-hydra/dashboard-goto-bookmarks #'...) (defalias 'dashboard-hydra/dashboard-goto-projects #'...) (defalias 'dashboard-hydra/widget-button-press-and-exit #'...) (defalias 'dashboard-hydra/widget-forward #'...) (defalias 'dashboard-hydra/widget-backward #'...) (defalias 'dashboard-hydra/next-line #'...) (defalias 'dashboard-hydra/previous-line #'...) (defalias 'dashboard-hydra/open-dashboard-and-exit #'...) (defalias 'dashboard-hydra/dashboard-refresh-buffer-and-exit #'...) (defalias 'dashboard-hydra/quit-dashboard-and-exit #'...) (defalias 'dashboard-hydra/nil #'...) (defalias 'dashboard-hydra/body #'...))) (progn (let* ((name "<f2>") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'open-dashboard)) (if (boundp 'dashboard-mode-map) (progn (let* ... ... ...) (let* ... ... ...) (let* ... ... ...) (let* ... ... ...) (let* ... ... ...) (let* ... ... ...) (let* ... ... ...) (let* ... ... ...)) (eval-after-load 'dashboard #'...))))
  (progn (progn (use-package-ensure-elpa 'dashboard '(t) 'nil) (apply #'face-spec-set '(dashboard-heading ...)) (apply #'face-spec-set '(dashboard-items-face ...)) (apply #'face-spec-set '(dashboard-no-items-face ...)) (if (fboundp 'quit-dashboard) nil (autoload #'quit-dashboard "dashboard" nil t)) (if (fboundp 'dashboard-refresh-buffer) nil (autoload #'dashboard-refresh-buffer "dashboard" nil t)) (if (fboundp 'open-dashboard) nil (autoload #'open-dashboard "dashboard" nil t)) (if (fboundp 'previous-line) nil (autoload #'previous-line "dashboard" nil t)) (if (fboundp 'next-line) nil (autoload #'next-line "dashboard" nil t)) (if (fboundp 'widget-backward) nil (autoload #'widget-backward "dashboard" nil t)) (if (fboundp 'widget-forward) nil (autoload #'widget-forward "dashboard" nil t)) (if (fboundp 'widget-button-press) nil (autoload #'widget-button-press "dashboard" nil t)) (if (fboundp 'dashboard-goto-projects) nil (autoload #'dashboard-goto-projects "dashboard" nil t)) (if (fboundp 'dashboard-goto-bookmarks) nil (autoload #'dashboard-goto-bookmarks "dashboard" nil t)) (if (fboundp 'dashboard-goto-recent-files) nil (autoload #'dashboard-goto-recent-files "dashboard" nil t)) (if (fboundp 'dashboard-previous-section) nil (autoload #'dashboard-previous-section "dashboard" nil t)) (if (fboundp 'dashboard-next-section) nil (autoload #'dashboard-next-section "dashboard" nil t)) (if (fboundp 'find-custom-file) nil (autoload #'find-custom-file "dashboard" nil t)) (if (fboundp 'restore-session) nil (autoload #'restore-session "dashboard" nil t)) (if (fboundp 'restore-previous-session) nil (autoload #'restore-previous-session "dashboard" nil t)) (if (fboundp 'browse-homepage) nil (autoload #'browse-homepage "dashboard" nil t)) (if (fboundp 'update-config-and-packages) nil (autoload #'update-config-and-packages "dashboard" nil t)) (if (fboundp 'dashboard-hydra/body) nil (autoload #'dashboard-hydra/body "dashboard" nil t)) (setq dashboard-banner-logo-title "CENTAUR EMACS - Enjoy Programmin..." dashboard-startup-banner (or centaur-logo 'official) dashboard-page-separator "\n\f\n" dashboard-projects-backend 'project-el dashboard-path-style 'truncate-middle dashboard-path-max-length 60 dashboard-center-content t dashboard-show-shortcuts nil dashboard-items '(... ... ...) dashboard-set-init-info t dashboard-display-icons-p #'icons-displayable-p dashboard-icon-type 'nerd-icons dashboard-set-file-icons centaur-icon dashboard-set-heading-icons centaur-icon dashboard-heading-icons '(... ... ... ... ...) dashboard-set-footer ...) (dashboard-setup-startup-hook) (eval-after-load 'dashboard #'(lambda nil ...)) (add-hook 'dashboard-mode-hook #'(lambda nil ... ...)) (progn '(:title ... :color pink :quit-key ... :hint nil) (progn (set ... ...) (set ... "\n\n %s(pretty-hydra-title \"Dashbo...") (set ... ...) (set ... ...) (set ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...))) (progn (let* (... ... ... ... ...) (let ... ...) (define-key kmap key ...)) (if (boundp ...) (progn ... ... ... ... ... ... ... ...) (eval-after-load ... ...)))))
  (if centaur-dashboard (progn (progn (use-package-ensure-elpa 'dashboard '(t) 'nil) (apply #'face-spec-set '(dashboard-heading ...)) (apply #'face-spec-set '(dashboard-items-face ...)) (apply #'face-spec-set '(dashboard-no-items-face ...)) (if (fboundp 'quit-dashboard) nil (autoload #'quit-dashboard "dashboard" nil t)) (if (fboundp 'dashboard-refresh-buffer) nil (autoload #'dashboard-refresh-buffer "dashboard" nil t)) (if (fboundp 'open-dashboard) nil (autoload #'open-dashboard "dashboard" nil t)) (if (fboundp 'previous-line) nil (autoload #'previous-line "dashboard" nil t)) (if (fboundp 'next-line) nil (autoload #'next-line "dashboard" nil t)) (if (fboundp 'widget-backward) nil (autoload #'widget-backward "dashboard" nil t)) (if (fboundp 'widget-forward) nil (autoload #'widget-forward "dashboard" nil t)) (if (fboundp 'widget-button-press) nil (autoload #'widget-button-press "dashboard" nil t)) (if (fboundp 'dashboard-goto-projects) nil (autoload #'dashboard-goto-projects "dashboard" nil t)) (if (fboundp 'dashboard-goto-bookmarks) nil (autoload #'dashboard-goto-bookmarks "dashboard" nil t)) (if (fboundp 'dashboard-goto-recent-files) nil (autoload #'dashboard-goto-recent-files "dashboard" nil t)) (if (fboundp 'dashboard-previous-section) nil (autoload #'dashboard-previous-section "dashboard" nil t)) (if (fboundp 'dashboard-next-section) nil (autoload #'dashboard-next-section "dashboard" nil t)) (if (fboundp 'find-custom-file) nil (autoload #'find-custom-file "dashboard" nil t)) (if (fboundp 'restore-session) nil (autoload #'restore-session "dashboard" nil t)) (if (fboundp 'restore-previous-session) nil (autoload #'restore-previous-session "dashboard" nil t)) (if (fboundp 'browse-homepage) nil (autoload #'browse-homepage "dashboard" nil t)) (if (fboundp 'update-config-and-packages) nil (autoload #'update-config-and-packages "dashboard" nil t)) (if (fboundp 'dashboard-hydra/body) nil (autoload #'dashboard-hydra/body "dashboard" nil t)) (setq dashboard-banner-logo-title "CENTAUR EMACS - Enjoy Programming & Wr..." dashboard-startup-banner (or centaur-logo 'official) dashboard-page-separator "\n\f\n" dashboard-projects-backend 'project-el dashboard-path-style 'truncate-middle dashboard-path-max-length 60 dashboard-center-content t dashboard-show-shortcuts nil dashboard-items '(... ... ...) dashboard-set-init-info t dashboard-display-icons-p #'icons-displayable-p dashboard-icon-type 'nerd-icons dashboard-set-file-icons centaur-icon dashboard-set-heading-icons centaur-icon dashboard-heading-icons '(... ... ... ... ...) dashboard-set-footer t dashboard-footer-icon (cond (... ...) (t ...)) dashboard-set-navigator t dashboard-navigator-buttons ...) (dashboard-setup-startup-hook) (eval-after-load 'dashboard #'(lambda nil ...)) (add-hook 'dashboard-mode-hook #'(lambda nil ... ...)) (progn '(:title ... :color pink :quit-key ... :hint nil) (progn (set ... ...) (set ... "\n\n %s(pretty-hydra-title \"Dashboard\" '...") (set ... ...) (set ... ...) (set ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...))) (progn (let* (... ... ... ... ...) (let ... ...) (define-key kmap key ...)) (if (boundp ...) (progn ... ... ... ... ... ... ... ...) (eval-after-load ... ...))))))
  load-with-code-conversion("/home/xxxx/.emacs.d/lisp/init-dashboard.el" "/home/xxxx/.emacs.d/lisp/init-dashboard.el" nil t)
  require(init-dashboard)
  load-with-code-conversion("/home/xxxx/.emacs.d/init.el" "/home/xxxx/.emacs.d/init.el" t t)
  load("/home/xxxx/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0xd1ba1a6f0a1072a>) #f(compiled-function () #<bytecode -0x1f3c686ddc0cdc35>) t)
  command-line()
  normal-top-level()

**Comment by seagle0128** [comment]
Please update `dashboard` package. See https://github.com/emacs-dashboard/emacs-dashboard/commit/fd7819cc90e5381c3e7788325ef8f1fec3100201
