### ISSUE TITLE
请问如何配置并切换中文输入法为双拼

### ISSUE THREAD

**Issue by wyz2gh** [seagle0128/.emacs.d#405]
如题，windows11，emacs版本是29。
请问是否可以配置中文输入法为双拼？该如何配置？
我找目前的配置文件，没有找到相关的内容。

**Comment by seagle0128** [comment]
默认不支持双拼，可以参考：
https://github.com/tumashu/pyim
https://github.com/DogLooksGood/emacs-rime

在`custom-post.el`中添加配置即可。

**Comment by wyz2gh** [comment]
好的，感谢，我学习一下
