### ISSUE TITLE
[Bug] Segmentation fault after installing centaur-fonts

### ISSUE THREAD

**Issue by br2soft** [seagle0128/.emacs.d#409]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Emacs crashes with an segmentation fault on Linux after installing Centaur Emacs Fonts.

### Steps to reproduce

Setup any current Linux system (I tried Debian Bookworm on a real installation and current Arch (in VirtualBox) and install Emacs. Then clone the repro and start Emacs. Wait a long time for the first run. After finish of all downloads and lisp compiles, try to install the Centaur Emacs Fonts calling M-x install-centaur-fonts.

Then close Emacs and restart the program. Move the mouse over the icons and you receive a segementation fault.

Without installing the fonts, this does not happen.

### Expected behavior

No crash having a good looking Emacs config.

### OS

Linux

### Emacs Version

28

**Comment by seagle0128** [comment]
Try removing the fonts and install via `M-x nerd-icons-install-fonts`.

**Comment by br2soft** [comment]
When I installed the icons they are displayed correctly. I tried to remove the font NFM.ttf from ~/.local/share/fonts and executed M-x nerd-icons-install-fonts. The font is restored and the segmentation fault occurs again.

**Comment by br2soft** [comment]
The problem also occurs in Ubuntu 23.04 (VirtualBox).  Using emacs in  terminal mode works with the fonts installed. It seems to be a problem with GTK.

**Comment by seagle0128** [comment]
Can you please try Emacs 29+?

**Comment by br2soft** [comment]
I tried building emacs from source with Debian Bookworm to get Emacs 30... and finally, it works, no crashes.
