### ISSUE TITLE
[Bug] Starup failed

### ISSUE THREAD

**Issue by beast-pro** [seagle0128/.emacs.d#410]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

after update to latest  Centaur Emacs startup failed, error message is :
```
custom-initialize-reset: Unable to find icon with name ‘nf-oct-history’ in icon set ‘octicon’
```
I am sure that I have installed the Nerd Font: 
![image](https://github.com/seagle0128/.emacs.d/assets/116860578/b4000ef6-5c4d-4cba-9bbe-844dc1592d3f)

### Steps to reproduce

nil

### Expected behavior

nil 

### OS

MacOS

### Emacs Version

29

**Comment by beast-pro** [comment]
Restarting also gives the same error, when I comment out the following code, it works fine：
![image](https://github.com/seagle0128/.emacs.d/assets/116860578/dc336d00-984d-4c7a-bf1b-ab8ee1f9eed1)

**Comment by seagle0128** [comment]
I think the nerd font is not installed correctly. Please check if other nerd fonts are installed, and what else in your private configurations.

**Comment by beast-pro** [comment]
In the picture, you can see all of the fonts that I have downloaded. NFM.ttf was downloaded by centaur-install-fonts, and SymbolsNerdFont-Regular and SymbolsNerdFontMono-Regular were downloaded manually. I am still getting the same error after restarting Emacs. Can you show me the fonts that you have installed?
![image](https://github.com/seagle0128/.emacs.d/assets/116860578/75d073fc-d857-4ada-a3e5-6af409340a58)

**Comment by seagle0128** [comment]
Can you please run `M-x nerd-icons-insert` to search oct fonts?

**Comment by beast-pro** [comment]
![image](https://github.com/seagle0128/.emacs.d/assets/116860578/3b7ef6d3-8ec6-4bf0-940e-4f6a2c2f7e87)

**Comment by seagle0128** [comment]
It seems oct fonts are installed and able to be found. Do you still have this issue during the startup with the latest version?

```
custom-initialize-reset: Unable to find icon with name ‘nf-oct-history’ in icon set ‘octicon’
```

**Comment by seagle0128** [comment]
I think you didn't update `emacs-dashboard` to the latest. The old version doesn't support nerd fonts. Please confirm.

**Comment by beast-pro** [comment]
I'm using the master branch, and then I downloaded the master branch again and compared it with my local branch. This is the diff.
Figure 1 and Figure 2 show two differences in init-dashboard, and Figure 3 indicates that Emacs did load the file.
![image](https://github.com/seagle0128/.emacs.d/assets/116860578/dd1dca5b-9ac2-415e-8253-d6401910f8cc)
![image](https://github.com/seagle0128/.emacs.d/assets/116860578/74240a6c-b412-479f-a86a-e9528252ef61)
![image](https://github.com/seagle0128/.emacs.d/assets/116860578/1b8e23b2-ecc1-4190-8609-7670841f94b5)

Additionally, if I don't comment out these lines now, I will still encounter this problem.

**Comment by seagle0128** [comment]
Check your local `dashboard` package and see if `dashboard-icon-type` exists. Please update `dashboard` to the latest.
