### ISSUE TITLE
[Bug] doom-modeline messed up in feat/modern-completion branch

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#411]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Trying to test `feat/modern-completion` with Emacs(GCC) version 28.2, 29.0.92 and 30(emacs master branch)

`debug-on-error` or `emacs --debug-init` does not give any additional information.

Please see screenshot below - 
<img width="1205" alt="image" src="https://github.com/seagle0128/.emacs.d/assets/23665525/155ac040-ef9c-4ac2-9c46-4062d3093d56">

### Steps to reproduce

Clone this repository to `~/.emacs.d`, change branch to `feat/modern-completion` and run emacs app.

### Expected behavior

`doom-mode-line` should be functional.

### OS

MacOS

### Emacs Version

gccemacs-28

**Comment by seagle0128** [comment]
Can you please check the version of `use-package`? And whether does `diminish` exist (via `find-library``)?
