### ISSUE TITLE
[Bug or Question] 

### ISSUE THREAD

**Issue by mbykov** [seagle0128/.emacs.d#413]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

CENTAUR EMACS - Enjoy Programming & Writing

[󰊤 Homepage] [󰁯 Restore] [󱁤 Settings] [󰚰 Update] [󰋖] 

What does this mean? What font am i missing?

Thank you!

### Steps to reproduce

just from scratch

### Expected behavior

apt-get install font-xxx what ?

### OS

Linux

### Emacs Version

28

**Comment by seagle0128** [comment]
Try `M-x centaur-install-fonts` and restart Emacs.
