### ISSUE TITLE
[Bug] Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#415]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.

Getting this at start up. This is from `main` branch after `feature/modern-comp` merge.

### Steps to reproduce

Check messages buffer after start up

### Expected behavior

No warnings

### OS

MacOS

### Emacs Version

gccemacs-29

**Comment by seagle0128** [comment]
See https://github.com/doomemacs/themes/issues/793.

**Comment by CsBigDataHub** [comment]
Thanks @seagle0128 .

Question if system themes.

```
(centaur-system-themes '((light . modus-operandi)
                             (dark  . modus-vivendi)))

```

Customizing this variable does not allow me to use `modus-themes`. What is the right way to configure `modus themes` in in `custom-post.el` ?
