### ISSUE TITLE
[Bug] Closing Emacs asks for saving desktop

### ISSUE THREAD

**Issue by br2soft** [seagle0128/.emacs.d#416]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

When I close Emacs it always asks to save the desktop.

### Steps to reproduce

Start Emacs with properly installed Centaur. Press the close button or hit C-x C-c to close Emacs. Then Emacs asks for saving the desktop in a path. Even after restart, Emacs asks again to save the desktop. Overwriting the desktop.el file causes another error message.

### Expected behavior

Auto save the desktop in the .emacs.d or an option to toggle not to save the desktop.

### OS

Windows

### Emacs Version

29

### Error callstack

```emacs-lisp
I use Emacs 30.
```

### Anything else

After trying out, I see that lines 342-345 of init-ui.el are responsible for this. As far as I see, this was even occuring in the feature branch that has been merged recently to the master branch.

It seems to depend on the package posframe. Maybe it is a bug of the package posframe itself.

Even when I save the desktop file, this file seems not to be loaded on the next start (like the issue https://emacs.stackexchange.com/questions/62015/closing-emacs-results-in-current-desktop-was-not-loaded-from-a-file-even-thoug). This error message appears, when I overwrite the last desktop.el file.

**Comment by seagle0128** [comment]
If you restore previous session (in Dashboard, press `R`) after startup, then close the Emacs, the prompt won't be displayed.

**Comment by seagle0128** [comment]
PS: `(setq desktop-save nil)`
