### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by phisu** [seagle0128/.emacs.d#417]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

i have installed phpstan and ph-scratch. they need php-mode. php-mode seems to have been installed automatically because of this. when i start centaur emacs, i see in the messages buffer: 

Error loading autoloads: (file-missing Cannot open load file File or directory not found /home/sutter/.emacs.d/elpa/php-mode-20230815.1051/php-mode-autoloads).

and my php-files are opened in web-mode and not with php-mode.

why was php-mode-autoloads not created during installation? how can i use centaur emacs to create this file? what do i need to do to get my php files to open automatically with php-mode?

### Steps to reproduce

install php-mode

### Expected behavior

all files with the extension php should be opened automatically in php-mode.

### OS

Linux

### Emacs Version

29

### Anything else

when i start emacs i see the following messages:

Loading /home/sutter/.emacs.d/custom.el (source)...
Loading which-func (native compiled elisp)...done
Loading /home/sutter/.emacs.d/custom.el (source)...done
Set package archives to ‘melpa’
Edebug: names-edebug-anon0
Edebug: names-edebug-anon1
Edebug: names-edebug-anon2
Edebug: names-edebug-anon3
Error loading autoloads: (file-missing Cannot open load file Datei oder Verzeichnis nicht gefunden /home/sutter/.emacs.d/elpa/epl-20180205.2049/epl-autoloads)
Error loading autoloads: (file-missing Cannot open load file Datei oder Verzeichnis nicht gefunden /home/sutter/.emacs.d/elpa/php-mode-20230815.1051/php-mode-autoloads)
Error loading autoloads: (file-missing Cannot open load file Datei oder Verzeichnis nicht gefunden /home/sutter/.emacs.d/elpa/macrostep-20230813.2123/macrostep-autoloads)
Error loading autoloads: (file-missing Cannot open load file Datei oder Verzeichnis nicht gefunden /home/sutter/.emacs.d/elpa/elisp-refs-20230419.405/elisp-refs-autoloads)
Error loading autoloads: (file-missing Cannot open load file Datei oder Verzeichnis nicht gefunden /home/sutter/.emacs.d/elpa/gotest-20230221.945/gotest-autoloads)
Error loading autoloads: (file-missing Cannot open load file Datei oder Verzeichnis nicht gefunden /home/sutter/.emacs.d/elpa/go-mode-20230624.2315/go-mode-autoloads)
Error loading autoloads: (file-missing Cannot open load file Datei oder Verzeichnis nicht gefunden /home/sutter/.emacs.d/elpa/fish-mode-20230326.1604/fish-mode-autoloads)

**Comment by seagle0128** [comment]
`php-mode` is installed by Centaur Emacs. Try `M-x package-reinstall RET php-mode RET`

**Comment by phisu** [comment]
thank you. php-autoload exists now. but when i open a file with the
extension .php web-mode is the major mode. I think, it should be
configured, that php is the major mode. Is there something, which I have to
configure?

Vincent Zhang ***@***.***> schrieb am Mi., 16. Aug. 2023,
16:57:

**Comment by phisu** [comment]
thank you
