### ISSUE TITLE
Defined hotkey has not taken effect

### ISSUE THREAD

**Issue by theRunCom** [seagle0128/.emacs.d#418]
I just used init-quickrun.el to install and set some functions with the package. When I click it, the result is "<F5> is undefined"!
``` lisp
(use-package quickrun
  :custom
  (quickrun-timeout-seconds 60)
  :bind
  (([f5] . quickrun)
   ("M-<f5>" . quickrun-shell))

(provide 'init-quickrun)
```
I put `(require init-quickrun)` in init.el, restart, and the folder of /elpa had the quickrun...

**Comment by seagle0128** [comment]
`quickrun` has been in `init-prog.el`. You should add your own config to `custom-post.el`.
