### ISSUE TITLE
Emacs启动好像并没有运行 .emacs.d/site-lisp/subdirs.el ，site-lisp下的文件夹没有添加到load-path

### ISSUE THREAD

**Issue by 2215454883** [seagle0128/.emacs.d#42]
Emacs启动好像并没有运行 .emacs.d/site-lisp/subdirs.el ，site-lisp下的文件夹没有添加到load-path。
下面链接提到启动执行的操作中第一条，安装Emacs时生成的subdirs.el 确实运行了，但是自定义目录中的subdirs.el 应该没有运行。配置中这个 subdirs.el 文件是不是多余的啊
https://www.gnu.org/software/emacs/manual/html_node/elisp/Startup-Summary.html

**Comment by seagle0128** [comment]
I have no idea why `subdirs.el` doesn't work now. I worked well before.
Anyway I will use other methods to load subdirs.
