### ISSUE TITLE
[Feature Request] FYI on hl-todos

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#420]
Since `magit-todos` is not supported anymore.

* A flymake backend to hl-todo, see https://github.com/tarsius/hl-todo/pull/74. By registering this backend, your todos will appear in the `flymake` diagnostics list and also via `consult-flymake` with preview.

*  flycheck-hl-todo: This package has been added to MELPA recently, see https://github.com/alvarogonzalezsotillo/flycheck-hl-todo. It offers the same for `flycheck` and `consult-flycheck.`

Source - https://www.reddit.com/r/emacs/comments/162v446/new_package_consulttodo/

**Comment by seagle0128** [comment]
The commit 79f23bd80f0cb2b8917f93479f73feccdca262cb has supported `hl-todo-flymake` backend.

And I also added `hl-todo-rg` via c9b928cb0a7c748806f1fe2f1d8134ca68ebf5dd.

BTW, does `magit-todos` work for you? It's buggy in my env. The section disappears in magit-status.

**Comment by CsBigDataHub** [comment]
> does magit-todos work for you? It's buggy in my env.

Yes it is buggy and slow in `emacs 29.1`. `pre-hook` and `post-hook` issues from what I see in the `*Messages*` buffer.
