### ISSUE TITLE
[Bug] Blank screen on fresh install

### ISSUE THREAD

**Issue by ahopkins** [seagle0128/.emacs.d#421]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

Seems to be the same behavior reported here: #365

However, the solution does not work, and I do not see that config value, so I am thinking it is not relevant as it is older.

### Steps to reproduce

- Fresh emacs install (I did it using pacman on Arch linux)
- remove `~/.emacs.d`
- copy git command
- open emacs

### Expected behavior

I would have expected to see some information about package installation or something so that I know it is working and not just frozen. I'm not sure it is doing anythin.

### OS

Linux

### Emacs Version

28

**Comment by seagle0128** [comment]
I believe the messages will be displayed in minibuffer during the startup. It's better for troubleshootings if the recordings and screenshots are shared.

**Comment by ahopkins** [comment]
There is no minibuffer displayed.

![image](https://github.com/seagle0128/.emacs.d/assets/166269/6759bc31-0bd5-4553-b645-d92f2429f273)

I left it like this and came back several hours later, and clearly it was working. I restarted emacs and it was working. But, it does not look like it.

**Comment by seagle0128** [comment]
What happened if pressing `C-g`?

**Comment by ahopkins** [comment]
Nothing different happened. I have moved on though, so you can close if it is not something you can recreate.

**Comment by seagle0128** [comment]
@ahopkins Please check if there is `(setq inhibit-redisplay t` or something like this in `init.el`. It was removed two months ago.

**Comment by seagle0128** [comment]
@ahopkins Any update?

**Comment by ahopkins** [comment]
you can close. I'm using a different setup now.
