### ISSUE TITLE
[Bug] Find File is very slow

### ISSUE THREAD

**Issue by HashRaygoza** [seagle0128/.emacs.d#422]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

On a clean install on Emacs 28.2 the find-file function is very slow it can take up to 45 seconds to register any key press, either the keys to move on the file list or just trying to type a file name , and while the file selection screen is open all of emacs becomes irresponsible, to the point even the quit function c-g doesn't respond

### Steps to reproduce

1. Install Emacs Centaur on a clean emacs install
2. press C-x C-f to call find-file
3. try to select a file either moving the cursor with the arrow keys or typing
4. Take notice on how long it takes to respond
5. Try to close the file dialog with the Quit command (C-g)
6. Take notice on how long takes to respond

### Expected behavior

The file dialog to open and allow to quickly select a file to open

### OS

Linux

### Emacs Version

28

### Anything else

![Captura desde 2023-09-08 00-47-05](https://github.com/seagle0128/.emacs.d/assets/19654490/ad117769-1c90-4e0d-a51c-19a420718bd0)

**Comment by seagle0128** [comment]
Please follow this [guide](https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html) to find out the root cause.
This is weird. The icon of folder on the screenshot seems not right.

**Comment by HashRaygoza** [comment]
I updated to emacs 29.1 (flathub version), make a clean install but the same issue continue, and the folder icons are missing too

I tried to use the profiler but the buffer with the information doesn't show up, beside running profiler-start is there any other step necessary?

**Comment by HashRaygoza** [comment]
One curious detail, treemacs-find-file does work as expected both on speed and on showing the folder icon
![Captura desde 2023-09-11 21-55-45](https://github.com/seagle0128/.emacs.d/assets/19654490/758373a3-ec26-4418-889d-839ddd992ce3)

**Comment by HashRaygoza** [comment]
One curious thing the command M-x treemacs does work as expected, in both on speed and showing the folder icon

![Captura desde 2023-09-11 22-56-23](https://github.com/seagle0128/.emacs.d/assets/19654490/6c524b73-2ff2-4ae6-8b37-c4aef978e306)

**Comment by seagle0128** [comment]
> I tried to use the profiler but the buffer with the information doesn't show up, beside running profiler-start is there any other step necessary?

Please read the guide first. `profiler-start` , do something, then `profiler-report`.

**Comment by HashRaygoza** [comment]
Understood, I ran the profiler and call the find-file function to get an idea where the excessive CPU usage was happening and is on something called #<compiled -0x1fb0843212e08fa3> wonder if it  may be something compiled weird on emacs

fortunately I found a way to sideline the issue treemacs gets the job done

Thank you for your help

![Captura desde 2023-09-12 20-33-15](https://github.com/seagle0128/.emacs.d/assets/19654490/794c834f-a1ee-4725-a4ca-f90b61de3d27)

**Comment by seagle0128** [comment]
Expand `#<compiled -0x1fb0843212e08fa3>` and find out more details.

**Comment by HashRaygoza** [comment]
It doesn't let me to expand it, that's why I suspect is something related to how the emacs or its libraries was compiled
