### ISSUE TITLE
Nerd-icon.el  url: raw.githubusercontent [Bug] 

### ISSUE THREAD

**Issue by alphanhp** [seagle0128/.emacs.d#429]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

should be manually set to github.com for use,  
then delete nerd-icon.elc  
final restart

### Steps to reproduce

.emacs.d/elpa/nerd-icon/nerd-icon.el

### Expected behavior

should be manually set to github.com for use,  
then delete nerd-icon.elc  
final restart

### OS

Windows

### Emacs Version

29

**Comment by seagle0128** [comment]
Sorry, I didn't get your point. What's the issue here?

**Comment by alphanhp** [comment]
国内可能用不了raw.githubusercontent
也有可能是我不太会用
不过改github.com后可以使用

**Comment by alphanhp** [comment]
初次启动下载插件的时候会有问题

**Comment by seagle0128** [comment]
It seems a network issue.
