### ISSUE TITLE
[Feature Request] Maybe 'init-package' should before 'init-custom'

### ISSUE THREAD

**Issue by leslie-arch** [seagle0128/.emacs.d#431]
**Is your feature request related to a problem? Please describe.**
Some Variables or Functions could be set or called after package loads.

**Describe the solution you'd like**
For example, Input Method "pyim-wbdict"must set default scheme when package is loaded.  
But the function couldn't be called in custom.el.

**Describe alternatives you've considered**
Just set 'init-custom' after 'init-package'.

**Additional context**

**Comment by seagle0128** [comment]
Not sure if I understand completely. I think you need `custom-post.el` file, or `with-eval-after-load` in `custom.el`.
