### ISSUE TITLE
[Feature Request] How could I config PYIM input method with pyim-wbdict?

### ISSUE THREAD

**Issue by leslie-arch** [seagle0128/.emacs.d#432]
**Is your feature request related to a problem? Please describe.**

When "(require 'pyim) (require 'pyim-wbdict)" added in 'custom.el'
There is an error : "couldn't find "pyim(-wbdict)"

I installed pyim(-wbdict) with package-install, it's autoloaded.
but ,the call of  (pyim-wbdict-v86-enabled) in custom.el caused another
error "the symbol is ....void" 

where should I put the config code ? custom.el or init.el?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by seagle0128** [comment]
Please use `with-eval-after-load`, or put the configurations into `custom-post.el`.
