### ISSUE TITLE
[Feature Request] How to install package from git, when package is not in melpa 

### ISSUE THREAD

**Issue by mcg-cyber** [seagle0128/.emacs.d#434]
Hi,
Could you please help about that how I can install any package from git because the package is not in melpa repo. I would like to install codeium for instance. Thank you so much!

**Comment by CsBigDataHub** [comment]
Multiple options.

https://github.com/radian-software/straight.el
https://github.com/quelpa/quelpa
https://github.com/progfolio/elpaca

or if you are using emacs-29.1 or 29.2 you can use `package-vc`

See - 

https://tony-zorman.com/posts/package-vc-install.html
https://tony-zorman.com/posts/use-package-vc.html
https://emacsredux.com/blog/2023/03/12/install-a-package-from-a-vcs-repository/

**Comment by seagle0128** [comment]
You've had the answer.

**Comment by mcg-cyber** [comment]
I will choose probably the simplest one. Thank you so much!
