### ISSUE TITLE
Buffer visualization

### ISSUE THREAD

**Issue by rromoli** [seagle0128/.emacs.d#435]
Thanks for the work with Centaur Emacs, I discovered it recently but it has already become a fixed point. I'm writing because I wanted to know how to display all the available buffers. If I use `C-x b` I can only see some buffers, while others, like `*Messages*` or `*lsp-log*` are not visible.

**Comment by seagle0128** [comment]
It's by design. [tabspaces](https://github.com/mclear-tools/tabspaces) displays the buffers by group/project. Following the tips below you can see all buffers, 

1. `C-x C-b`.
2. `C-x b < b`,

**Comment by seagle0128** [comment]
I've removed the behaviors in the latest version, since I encountered many queries recently.
