### ISSUE TITLE
请问怎么关闭透明背景 , 或者调整透明度?

### ISSUE THREAD

**Issue by happy12322** [seagle0128/.emacs.d#436]
customization 部分介绍好像没有提方法, google 了下回看了 issue 也没发现怎么调节, 切换不同的主题, 仍然是透明的,, 有什么办法关闭透明背景吗?

**Comment by seagle0128** [comment]
```elisp
(transwin-ask '100)
```

**Comment by happy12322** [comment]
谢谢回复 

> ```emacs-lisp
> (transwin-ask '100)
> ```

在 `lisp/init-base.el` 调节这个参数解决了我的问题, 谢谢您的帮助
