### ISSUE TITLE
每次打开文件都提示: Warning (emacs): ‘:events-buffer-scrollback-size’ deprecated. Use ‘events-buffer-config’.

### ISSUE THREAD

**Issue by happy12322** [seagle0128/.emacs.d#437]
在 opsuse 15 和 debian 11 上都会有这个提示.

再一个就是把项目克隆到~/.emacs.d 后,  我没有对项目文件作任何更改, 启动 emacs 后自动就选择了 ustc 源,   安完了我看项目文件夹内配置,  默认指定的是 melpa 源啊, 不知道为啥没有使用默认的源.

**Comment by seagle0128** [comment]
请按照模板提供必要的信息，否则无法准备判断问题。

> 再一个就是把项目克隆到~/.emacs.d 后, 我没有对项目文件作任何更改, 启动 emacs 后自动就选择了 ustc 源, 安完了我看项目文件夹内配置, 默认指定的是 melpa 源啊, 不知道为啥没有使用默认的源.

请检查 custom.el

**Comment by happy12322** [comment]
刚才的表达是有问题的对不起, 重新表述一下.   之所以没有提供配置模板, 是因为我没有对配置进行更改啊都保持的默认.
第一步
```
mv ~/.emacs.d ~/.emacs.d.bak
git clone --depth 1 https://github.com/seagle0128/.emacs.d.git ~/.emacs.d
```
然后不对 `~/.emacs.d` 内文件内容做任何更改, (此时不存在 custom.el 这个文件), 工切都保持 github 仓库原样.

第二步, 打开 emacs ,自动进行安装, 我发现它使用的是 ustc 源啊. 而不是官方的 melpa 源.   不知道是不是根据我的网络环境测速选择了最快的源. 

`Warning (emacs): ‘:events-buffer-scrollback-size’ deprecated. Use ‘events-buffer-config'` 这个提示, 是在 29.2 版本出现的, 无论是 opensuse 官方源中的,  还是我在 debian 11 自己编译的, 都会出现这个问题.

**Comment by happy12322** [comment]
debian 11 官方版太旧了, 用的自编译, 版本信息:
```
 $ emacs --version                                                                                                                                                                               
GNU Emacs 29.2
Development version ef01b634d219 on HEAD branch; build date 2024-02-19.
```
opensuse 用的 Tumbleweed 最新版 , 官方仓库中就是最新的 29.2 版所以直接从官方仓库中安装了.

**Comment by happy12322** [comment]
之所以会提到 " 默认源 " 是因为, 在使用 ustc 源的情况下, emacs 会给出警告 , 提示不安全, 对于我是可以复现的, 提示如下
![Screenshot from 2024-02-22 19-36-54](https://github.com/seagle0128/.emacs.d/assets/160846254/800bed21-5e3e-4e8a-9767-eb2b7b2e6700)

**Comment by happy12322** [comment]
在弹出警告后, 我不想继续安装, 于是点了右上角的 X 关闭了emacs,    这时进入 `~/.emacs.d` 目录, 发现刚才运行 emacs 产生了 `custom.el` 文件 ,打开这个文件, 取消 `(setq centaur-package-archives 'melpa)         ; Package repo: melpa, emacs-cn, bfsu, netease, sjtu, tencent, tuna or ustc` 的注释(也就是启用 melpa 源), 再次打开 emacs , 不再出现警告, 等一会就安装完成了.

**Comment by seagle0128** [comment]
第一次启动会自动生成custom.el，package-archives也会自动测速选择最快的镜像源。如果不想用镜像，手动改为melpa即可。

**Comment by rif** [comment]
Every time I open a new file I get this Warning (emacs): ‘:events-buffer-scrollback-size’ deprecated. Use ‘events-buffer-config’. 
So annoying. Is there a fix for it?

**Comment by seagle0128** [comment]
This warning is from jsonrpc. Try

1. Upgrade jsonrpc.
2. Customize warning-suppress-log-types.

**Comment by liugang** [comment]
> Every time I open a new file I get this Warning (emacs): ‘:events-buffer-scrollback-size’ deprecated. Use ‘events-buffer-config’. So annoying. Is there a fix for it?

 using the following code added to  .emacs or init.el or custom.el file:

```lisp
;; Set the warning level
(setq warning-minimum-level :error) 
```
