### ISSUE TITLE
使用默认主题时,  corfu 补全弹出框中选中的高亮行与其它行几乎无法区分

### ISSUE THREAD

**Issue by happy12322** [seagle0128/.emacs.d#438]
在**使用默认主题**的情况下 `(setq centaur-theme 'default)` ,  corfu 框看起来是这样的(当前选中的是第一行):

![Screenshot from 2024-03-07 13-52-37](https://github.com/seagle0128/.emacs.d/assets/160846254/b365cb9f-d7d9-457b-8dfd-1706b49d59aa)

选中行与其它行颜色差别太小,  看起来好费劲啊.  请问是否有选项可以修改选中行的颜色?

**Comment by seagle0128** [comment]
1. 设置 `corfu-current` face
2. 或者更换其他配色
