### ISSUE TITLE
怎么打开 flymake 的实时错误检查?

### ISSUE THREAD

**Issue by happy12322** [seagle0128/.emacs.d#439]
默认配置下, buffer 中的错误,  在执行保存之前,  flymake 是无法发现的.  直到执行保存,  才触发 flymake 的查错. 并在界面右下角显示"错误数量"

改正错误之后,  在保存之前,  flymake 不会更正"错误数量",  直到下次保存,  才更正错误数量.

请问,  要怎样配置才可以"实时"查错?

**Comment by seagle0128** [comment]
`(setq flymake-no-changes-timeout 0.15)`.

**Comment by happy12322** [comment]
问题解决了, 谢谢您的帮忙
