### ISSUE TITLE
[Bug] failed to install

### ISSUE THREAD

**Issue by romain-pastorelli** [seagle0128/.emacs.d#441]
### Thank you for the bug report

- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).
- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.

### Bug description

I recently installed debian 12. Then I downloaded Emacs 28.2 and wanted to install Centaur. So I downloaded it and ran Emacs, and I got the following error
![Screenshot_20240416_161826](https://github.com/seagle0128/.emacs.d/assets/58110617/224dd1bb-7fa1-4e73-902b-2e6044196942)
Even after removing Emacs and Centaur and re-installing both a few times, I have the same problem...

### Steps to reproduce

```bash
sudo apt install emacs
mv ~/.emacs.d ~/.emacs.d.bak
git clone --depth 1 https://github.com/seagle0128/.emacs.d.git ~/.emacs.d
emacs &
```
Then, Emacs started, with a white screen and some line saying "Contacting ..." with some URL and suddently, I was shown the error from above

### Expected behavior

I should have installed Centaur Emacs and shown the home screen.

### OS

Linux

### Emacs Version

28

**Comment by romain-pastorelli** [comment]
Well I searched and tried a lot of different options to get Emacs 29.3 but I'm unable to find/download it well even following tutorials... Where did you get it ? BTW I'm on Debian 12, KDE Plasma and even with `sudo apt update` and `sudo apt upgrade emacs`, I get a message saying Emacs is up to date, at its latest version, even though I only have v28.2...

**Comment by seagle0128** [comment]
See https://www.emacswiki.org/emacs/EmacsSnapshotAndDebian and https://www.gnu.org/software/emacs/download.html.
