### ISSUE TITLE
[Bug] 某些情况下，headline 收起来后，最后的箭头符号显示异常

### ISSUE THREAD

**Issue by re-f** [seagle0128/.emacs.d#442]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

如图所示：
<img width="402" alt="centaur-ques" src="https://github.com/seagle0128/.emacs.d/assets/8351089/03f578ca-701f-4f39-ab63-d4a7c462a93f">
<img width="526" alt="centaur-ques-expand" src="https://github.com/seagle0128/.emacs.d/assets/8351089/4b48ef1a-d2d5-483a-ba04-992ca0815152">

### Steps to reproduce

没有找到稳定的复现场景，同样的文字甚至在不同的文件中打开的效果都不一样，确定的点是，当少于2 个空行时，能正常显示

我使用的文字

```

**  测试效果好的
1.  为什么呢?
   
**  测试效果不好的
1. asdlfjaldsjf



* Next
111



```

版本(重新 clone 的，没有加上个人人配置）:
b61336b8284008c3c5726aef7f15df50f20f9021

### Expected behavior

正常显示

### OS

MacOS

### Emacs Version

29

**Comment by seagle0128** [comment]
I couldn't reproduce this issue without further information. Please check the fonts on your macOS.

<img width="258" alt="image" src="https://github.com/seagle0128/.emacs.d/assets/140797/bfb57648-f1b6-4eee-9fc8-26cb7f1b8a8d">

<img width="226" alt="image" src="https://github.com/seagle0128/.emacs.d/assets/140797/aeb12b85-32c5-443c-9926-96ed9504ba55">

**Comment by re-f** [comment]
I am also unable to reproduce this issue again. Consequently, I will temporarily close this issue and will provide feedback should it reoccur.
