### ISSUE TITLE
[Bug] lsp-mode doesnt work

### ISSUE THREAD

**Issue by andrewdoh** [seagle0128/.emacs.d#443]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

using lsp-mode does not work with a fresh centaur emacs install but lsp-start-plain does work.

### Steps to reproduce

go into a project start lsp. e.g. python project. after starting lsp servers it never progresses beyond the starting phase. running lsp-start-plain works after a couple seconds.

### Expected behavior

lsp successfully starts after a couple seconds and does not hang at starting phase and i get all the features that lsp provides:
syntax error checks imports inferred upon object use and etc. see image below.

### OS

MacOS

### Emacs Version

29

### Anything else

<img width="342" alt="image" src="https://github.com/seagle0128/.emacs.d/assets/7662358/e235ae7a-02dd-4db5-beba-130d9dc752bf">
<img width="694" alt="image" src="https://github.com/seagle0128/.emacs.d/assets/7662358/b230e710-6c23-415f-99ff-73dfab817d61">

**Comment by seagle0128** [comment]
`lsp-mode` works well in my local env. No idea so far. I need more info to reproduce.

![image](https://github.com/seagle0128/.emacs.d/assets/140797/03c39041-d7bf-4f59-8acc-3880810ccd87)

**Comment by andrewdoh** [comment]
thanks i got it working. just had to delete everything and start over. also keep in mind not to set root dir as part of the scan.
<img width="1428" alt="image" src="https://github.com/seagle0128/.emacs.d/assets/7662358/f17f8807-30b0-4d14-866e-1c9e3e906efd">
