### ISSUE TITLE
[Bug] Node type error when execute consult-line in cpp file at the first time

### ISSUE THREAD

**Issue by bitristan** [seagle0128/.emacs.d#445]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

When I open an cpp file, and then use consult-line to search something, the error will occur

> Debugger entered--Lisp error: (treesit-query-error "Node type error at" 575 "[\"_Atomic\" \"break\" \"case\" \"const\" \"continue\" \"defa..." "Debug the query with `treesit-query-validate'")
  treesit-query-capture(#<treesit-node translation_unit in 1-34773> #<treesit-compiled-query> 2993 34773)
  treesit-font-lock-fontify-region(2993 34773 nil)
  font-lock-fontify-syntactically-region(2993 34773 nil)
  font-lock-default-fontify-region(3001 34773 nil)
  font-lock-fontify-region(3001 34773)
  #f(compiled-function (fun) #<bytecode -0x156ea081c0961c43>)(font-lock-fontify-region)
  jit-lock--run-functions(3001 34773)
  jit-lock-fontify-now()
  consult--fontify-all()
  consult--line-candidates(nil 1)
  #f(compiled-function () #<bytecode 0x1674d527cc22fe66>)()
  funcall-with-delayed-message(1 "Collecting lines..." #f(compiled-function () #<bytecode 0x1674d527cc22fe66>))
  consult-line(nil nil)
  funcall-interactively(consult-line nil nil)
  #<subr command-execute>(consult-line nil nil nil)
  ad-Advice-command-execute(#<subr command-execute> consult-line)
  apply(ad-Advice-command-execute #<subr command-execute> consult-line)
  command-execute(consult-line)

But when I execute consult-line the second time, everything works fine.

### Steps to reproduce

According to the error log, I use treesit-query-validate to check the error.

`
(let ((query "[\"_Atomic\" \"break\" \"case\" \"const\" \"continue\" \"default\" \"do\" \"else\" \"enum\" \"extern\" \"for\" \"goto\" \"if\" \"inline\" \"register\" \"restrict\" \"return\" \"sizeof\" \"static\" \"struct\" \"switch\" \"typedef\" \"union\" \"volatile\" \"while\" \"and\" \"and_eq\" \"bitand\" \"bitor\" \"catch\" \"class\" \"co_await\" \"co_return\" \"co_yield\" \"compl\" \"concept\" \"consteval\" \"constexpr\" \"constinit\" \"decltype\" \"delete\" \"explicit\" \"final\" \"friend\" \"mutable\" \"namespace\" \"new\" \"noexcept\" \"not\" \"not_eq\" \"operator\" \"or\" \"or_eq\" \"override\" \"private\" \"protected\" \"public\" \"requires\" \"template\" \"throw\" \"try\" \"typename\" \"using\" \"virtual\" \"xor\" \"xor_eq\"] @font-lock-keyword-face (auto) @font-lock-keyword-face (this) @font-lock-keyword-face"))
  (treesit-query-validate 'cpp query))
`
And it will report the error below, and the cursor stop at the world "virtual".
I think maybe there is something wrong with the tree-sitter-cpp library, but I don't know what to do next.
The libtree-sitter-cpp.so was automatically installed by tree-sitter-auto which just clone code from https://github.com/tree-sitter/tree-sitter-cpp and compile internally.

`
Node type error at: 575
["_Atomic" "break" "case" "const" "continue" "default" "do" "else" "enum" "extern" "for" "goto" "if" "inline" "register" "restrict" "return" "sizeof" "static" "struct" "switch" "typedef" "union" "volatile" "while" "and" "and_eq" "bitand" "bitor" "catch" "class" "co_await" "co_return" "co_yield" "compl" "concept" "consteval" "constexpr" "constinit" "decltype" "delete" "explicit" "final" "friend" "mutable" "namespace" "new" "noexcept" "not" "not_eq" "operator" "or" "or_eq" "override" "private" "protected" "public" "requires" "template" "throw" "try" "typename" "using" "virtual" "xor" "xor_eq"] @font-lock-keyword-face (auto) @font-lock-keyword-face (this) @font-lock-keyword-face
`

### Expected behavior

`
(let ((query "[\"_Atomic\" \"break\" \"case\" \"const\" \"continue\" \"default\" \"do\" \"else\" \"enum\" \"extern\" \"for\" \"goto\" \"if\" \"inline\" \"register\" \"restrict\" \"return\" \"sizeof\" \"static\" \"struct\" \"switch\" \"typedef\" \"union\" \"volatile\" \"while\" \"and\" \"and_eq\" \"bitand\" \"bitor\" \"catch\" \"class\" \"co_await\" \"co_return\" \"co_yield\" \"compl\" \"concept\" \"consteval\" \"constexpr\" \"constinit\" \"decltype\" \"delete\" \"explicit\" \"final\" \"friend\" \"mutable\" \"namespace\" \"new\" \"noexcept\" \"not\" \"not_eq\" \"operator\" \"or\" \"or_eq\" \"override\" \"private\" \"protected\" \"public\" \"requires\" \"template\" \"throw\" \"try\" \"typename\" \"using\" \"virtual\" \"xor\" \"xor_eq\"] @font-lock-keyword-face (auto) @font-lock-keyword-face (this) @font-lock-keyword-face"))
  (treesit-query-validate 'cpp query))
`
Expect this validation to be ok.

### OS

Linux

### Emacs Version

29

### Error callstack

```emacs-lisp
Debugger entered--Lisp error: (treesit-query-error "Node type error at" 575 "[\"_Atomic\" \"break\" \"case\" \"const\" \"continue\" \"defa..." "Debug the query with `treesit-query-validate'")
  treesit-query-capture(#<treesit-node translation_unit in 1-34773> #<treesit-compiled-query> 2993 34773)
  treesit-font-lock-fontify-region(2993 34773 nil)
  font-lock-fontify-syntactically-region(2993 34773 nil)
  font-lock-default-fontify-region(3001 34773 nil)
  font-lock-fontify-region(3001 34773)
  #f(compiled-function (fun) #<bytecode -0x156ea081c0961c43>)(font-lock-fontify-region)
  jit-lock--run-functions(3001 34773)
  jit-lock-fontify-now()
  consult--fontify-all()
  consult--line-candidates(nil 1)
  #f(compiled-function () #<bytecode 0x1674d527cc22fe66>)()
  funcall-with-delayed-message(1 "Collecting lines..." #f(compiled-function () #<bytecode 0x1674d527cc22fe66>))
  consult-line(nil nil)
  funcall-interactively(consult-line nil nil)
  #<subr command-execute>(consult-line nil nil nil)
  ad-Advice-command-execute(#<subr command-execute> consult-line)
  apply(ad-Advice-command-execute #<subr command-execute> consult-line)
  command-execute(consult-line)
```

### Anything else

Test with the latest version and keep the default privacy configuration.

**Comment by seagle0128** [comment]
Unfortunately I couldn't reproduce the issue on my laptop. According to the backtrace, it's related to the `treesit`. I think it's better provide the example files for the troubleshooting.

**Comment by bitristan** [comment]
Yes, I have confirmed that it's related to libtree-sitter-cpp.so.  https://github.com/tree-sitter/tree-sitter-cpp
When I use v0.22.0, everything ok, but since v0.22.1, the error occur.
Thanks @seagle0128
