### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mrheggiz** [seagle0128/.emacs.d#448]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

This is my configuration to set my frame size and position placed in custom-post.el

(when window-system (set-frame-size (selected-frame) 140 80)
                     (set-frame-position (selected-frame)0 25))

It works at first but then the frame resizes to default size and position.

### Steps to reproduce

See above

### Expected behavior

To have have my custom frame size and position at startup

### OS

MacOS

### Emacs Version

29

**Comment by seagle0128** [comment]
Set `initial-frame-alist` or set it to `nil`.
