### ISSUE TITLE
Jump to definition in JS (JavaScript) isn't working.

### ISSUE THREAD

**Issue by wildneuro** [seagle0128/.emacs.d#45]
LSP is installed, but still having this message:

`Symbol's function definition is void: inferior-moz-process`

Thanks for any help!

**Comment by wildneuro** [comment]
Thanks for the reply!

I'm using `lsp-ui-peek-find-definitions`. It's constantly keep saying: 
Not found for: {{ function name }}.

When I'm using: `C-x C-j`, I'm getting:

`Symbol's function definition is void: inferior-moz-process`.

If I'm adding this:
```
(setq lsp-clients-typescript-server "typescript-language-server"
      lsp-clients-typescript-server-args '("--stdio"))
```,

no effect.

`M-.` points to the same. All is default.

By the way, it does work for the current file (jumps around just fine). But, when trying to resolve outside of the current file, getting errors.

**Comment by seagle0128** [comment]
I think it should be related to your configurations and lsp. DId you restart the LSP with `typescript-language-server`? Seems the LSP cannot index the symbols of other files. All files should be in the project. You can inquiry to LSP developers.

**Comment by wildneuro** [comment]
Did try that. Didn't work either. Also found, that LSP consumes 40% on my Mac, can please advice?

**Comment by wildneuro** [comment]
When doing:
```
(setq lsp-clients-typescript-server "typescript-language-server"
      lsp-clients-typescript-server-args '("--stdio"))
```
Getting next errors:
```
如果中英文不能对齐，请运行‘cnfonts-edit-profile’编辑当前profile。
LSP :: Connected to [ts-ls:52150 status:starting].
Error in menu-bar-update-hook (imenu-update-menubar): (error "No workspace could handle textDocument/documentSymbol")
Error from the Language Server: Request initialize failed with message: Couldn’t find ’tsserver’ executable or ’tsserver.js’ module (Internal Error)
```

**Comment by seagle0128** [comment]
It seems LSP server is not installed correctly. Please check tsserver.

**Comment by wildneuro** [comment]
You right! I reinstalled `tsserver` and it fixed. THANKS!
```
npm install -g --save typescript
```
and then, added this to `custom.el`:
```
(setq lsp-clients-typescript-server "typescript-language-server"
      lsp-clients-typescript-server-args '("--stdio"))
```
