### ISSUE TITLE
在全新系统中lsp mode无法补全的疑惑[Bug] 

### ISSUE THREAD

**Issue by oxsardbest** [seagle0128/.emacs.d#451]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

您好，第一次使用centaur emacs, 环境是新安装的xubuntu, 新拉取的centaur emacs,其他的一切正常。

状况是：新建py文件，安装好lsp相关包以后普通补全是很好没问题的，这时候比如我发现需要一个pandas包，用apt顺利安装好，bash启动python3,里面也是能找到pandas包的。

这时候我重新启动emacs, 打开py 文件，pandas包是补全不到的，别的python自带苦是没问题的（比如sys之类）

pandas这个包是在/usr/lib/python3/dist-packages/pandas/这个位置

lsp-clients-python-library-directories这个变量我也添加了如上路径，重启lsp后好像还是没有用。。。

### Steps to reproduce

如上

### Expected behavior

正常来说应该能识别到新安装的包。。。可能吧，我对lsp不太熟悉，以前我用company的。。。

### OS

Linux

### Emacs Version

29

**Comment by seagle0128** [comment]
Are you using `lsp-mode` or `eglot`?

**Comment by oxsardbest** [comment]
sorry i have tried both of them





------------------ 原始邮件 ------------------
发件人: Vincent Zhang ***@***.***&gt;
发送时间: 2024年7月14日 01:47
抄送: oxsardbest ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [seagle0128/.emacs.d] 在全新系统中lsp mode无法补全的疑惑[Bug]  (Issue #451)





 
Are you using lsp-mode or eglot?

**Comment by oxsardbest** [comment]
After I installed anaconda3 (using the path to anaconda), everything works as it should.
I think it ended up being a problem with a certain path setting, so I closed the issue.

thank you vincent.
