### ISSUE TITLE
[Problem] 配置了 lsp-bridge 如何关闭其他补全后端？

### ISSUE THREAD

**Issue by harisonkhlil** [seagle0128/.emacs.d#452]
已经关闭了关闭了 lsp 的补全 (setq centaur-lsp 'nil)

但是还出现了这种情况：

![image](https://github.com/user-attachments/assets/68f5c405-7ad1-4d60-9dee-0953a30e511a)

我该去关闭其他什么东西呢？

**Comment by seagle0128** [comment]
你可能还需要关闭 `global-corfu-mode`。
