### ISSUE TITLE
[Bug] Line breaks are displayed with ^L on dashboard

### ISSUE THREAD

**Issue by br2soft** [seagle0128/.emacs.d#454]
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

After the last update, line breaks are always shown with "^L" sign, even on dashboard. See screenshot attached.

![screenshot](https://github.com/user-attachments/assets/9ea729e9-0cd1-47eb-a337-8959440f79bf)

### Steps to reproduce

Update to latest configuration and  start/restart emacs.

### Expected behavior

No display of "^L" on default.

### OS

Windows

### Emacs Version

gccemacs-29

### Error callstack

```emacs-lisp
I use emacs 30 on Windows 10.
```

**Comment by seagle0128** [comment]
According to the screenshot, the startup failed. Please check the `*Messages*` buffer and/or backtrace.

**Comment by br2soft** [comment]
I attach the `*Messages*` buffer. The `custom-initialize-reset: ...` raises an error. I've seen this error message some days before in connection with an update of the magit package (not with the update of Centaur enviroment itself). For me, it seemed to belong to the magit package. But it might be, that the magit bug has been fixed already and this is currently the reason for the "^L" in the dashboard.

Going back to the previous commit, where linebreak has been changed, this fixes the "^L" issue.

And yes, I confess, that I work with chemacs to hop between many emacs enviroments, but this has almost never caused any issues.

![screenshot2](https://github.com/user-attachments/assets/6a31a85e-efb4-4316-aaa6-482576fd2d39)

**Comment by seagle0128** [comment]
The mode-line seems not right on the screenshots. That's why I said the startup failed. And I tested on both Windows and macOS, the the line breaks look fine.

**Comment by br2soft** [comment]
If I put back line 78 of init-dashboard.el
```
:hook (dashboard-mode . (lambda ()
                          ;; No title
                          (setq-local frame-title-format nil)
                          ;; Enable `page-break-lines-mode'
                          (when (fboundp 'page-break-lines-mode)
                             (page-break-lines-mode 1))))
```
it works. I tested it also on another Windows machine showing the same problem.

**Comment by seagle0128** [comment]
I don't think it's the root cause. You should address the issue first: `symbol's function definition is void: static-if`.

**Comment by br2soft** [comment]
Yes, I think, you are right! This message is emitted even after the last function call `(require 'init-web)` in init.el, even if I put something like `(message "Hello world!" (buffer-name))` after `(require 'init-web)`. So, all commands in init.el run without any error/warning message.  Even though, the message `symbol's function definition is void: static-if` is returned. I've no idea why. I think after init.el there is no command running, isn't it? Just strange...

**Comment by seagle0128** [comment]
`static-if` is introduced in subr.el from Emacs 30. If you are using 29, you should update (or reinstall) `compat` to the latest, I guess.

**Comment by br2soft** [comment]
I use Emacs 30 and reinstalled all packages (even `compat`).

**Comment by seagle0128** [comment]
Then you should check if `static-if` exists in your env.

**Comment by br2soft** [comment]
Very interesting! Thanks for your help! I do have subr.el in c:\Program Files\Emacs\emacs-30.0.50\share\emacs\30.0.50\lisp\, but in my build, static-if() is not defined while the current version of subr.el (see https://github.com/emacs-mirror/emacs/blob/master/lisp/subr.el) has that function. Hopefully I'll get a newer windows build of Emacs.

**Comment by br2soft** [comment]
Dear Vincent,

the same error comes up with current build of Emacs 31.0.50 on Linux 
(current git checkout), all current packages and the current checkout of 
Centaur. Please see the attached screenshot as of today. Maybe it is 
caused by my German language settings?

Could you reopen bug #454?

With kind regards

Christian
-- 
Kanzlei Dr. Brom
Holzweg 17
61440 Oberursel
Tel. 06171 58 37 58
Fax  06171 58 37 41
Mobil 0163 1 42 60 53
E-Mail: ***@***.***
GPG Key-ID: F05BBF5BB2BB55D7


-- 
Diese E-Mail wurde von Avast-Antivirussoftware auf Viren geprüft.
www.avast.com

**Comment by seagle0128** [comment]
>  Please see the attached screenshot as of today

@br2soft I didn't see the new screenshot. Would you please remove all your own configurations and reproduce?
