### ISSUE TITLE
Misjudge window width on Windows

### ISSUE THREAD

**Issue by kuppo** [seagle0128/.emacs.d#48]
Hello again,

I have another issue on `Windows 7 enterprise`, that it seems misjudge the window size. Please see screenshot.

![image](https://user-images.githubusercontent.com/17398733/50535284-7c90da80-0b83-11e9-9da5-4cf6d93796c2.png)

As you can see that the logo is not in the middle of the screen, and the tail of modeline is covered by the edge of the window.

I customized modeline a bit in the custom-post.el file, copied some configurations in your [mode-line](https://github.com/seagle0128/doom-modeline) repo, then I can drag a bit modeline back but not all of them.

Could you please help have a look? Appreciate it.

**Comment by kuppo** [comment]
Hello 
Also a font issue. I forced the font to Sarasa Gothic, then modeline acting weirdly.

Using your font setings, become normal. Maybe it is a bug.

**Comment by seagle0128** [comment]
Hi, can you try this config in your env and check the logo issue?
```elisp
(setq dashboard-banner-logo-title "Centaur Emacs")
```

Regarding the font issue, I think it's related to `all-the-icons` and `Sarasa Gothic`. Some characters should be overridden incorrectly. Sine I am not using `Sarasa Gothic`, please inquiry to the developers of `all-the-icons`.

**Comment by kuppo** [comment]
Thanks for your reply. The logo issue I think it is triggered by the font as I forced the font to `Sarasa Gothic`. When I disabled the font, it came back normal. I think I can live with it.
