### ISSUE TITLE
MacOS 下全屏使用 lsp 时会弹出多个空白窗口

### ISSUE THREAD

**Issue by ArchCST** [seagle0128/.emacs.d#49]
![image](https://user-images.githubusercontent.com/41679407/50721096-81f6a380-10f4-11e9-88a9-d8dc7e6ce21c.png)

全新 clone 的你的配置，在 MacOS 下使用全屏模式会在弹出候选框时自动新建出几个窗口，而且都是全屏的，于是屏幕界面就会在几个窗口跳转……

上图是在编辑 .py 和 .el 时自动弹出来的多个窗口，每次编辑一个新的语言就会弹出一个或两个全屏窗口。

![image](https://user-images.githubusercontent.com/41679407/50721140-427c8700-10f5-11e9-9a1a-15f3d63bf8ca.png)

看窗口的名称应该和 lsp-ui 有关

----

`(setq centaur-lsp 'eglot)` 之后 python company 能正常点出来，但问题依旧，全屏模式下会弹出多个窗口。

**Comment by seagle0128** [comment]
This is an issue of `company-box` https://github.com/sebastiencs/company-box/issues/59.

Workaround: `(company-box-mode -1)` or not using fullscreen.
Need upstream fixing.

**Comment by seagle0128** [comment]
Actually it's an issue of `child-frame` on macOS. The workaround is not using native fullscreen mode.
I will commit the workaround soon.
