### ISSUE TITLE
go 的 lsp 补全会多出字符，后端是 bingo，你有没有这种情况？

### ISSUE THREAD

**Issue by Jackson-soft** [seagle0128/.emacs.d#50]
<img width="617" alt="default" src="https://user-images.githubusercontent.com/3928114/50721350-09461600-10f9-11e9-9a26-f0e52bc7b167.png">

我不是用你的配置，只是讨论一个 lsp 的问题。
在用 lsp 补全的 go 的时候，使用 bingo 后端会出现多出自已输入的字符，就像图片里一样，不知道你有这种情况吗？而用 go 官方的后端 golsp 的时候又会出现吃掉自己输入的字符的情况，目前只有 go-langserver 是正确的，但又不支持 module。。。

**Comment by seagle0128** [comment]
这个恐怕是`bingo`本身的 issue 了。我暂时没碰到，但有其他问题。另外性能也有问题，启动和补全很卡。等 `golsp` 出来试试吧。你可以到`bingo`提个 issue， 也是国人。
