### ISSUE TITLE
Error in post-command-hook in .emacs.d

### ISSUE THREAD

**Issue by ArchCST** [seagle0128/.emacs.d#51]
When modify any .el files in .emacs.d will prompt this error:

![image](https://user-images.githubusercontent.com/41679407/50732322-8cc43d80-11b3-11e9-8006-2cf5a93852a8.png)

```
Error in post-command-hook (#[0 "\303\304\301\242\305#\210\300\306!\205r\211q\210
?\205\307\310\311 \")\207" [#<buffer init-company.el> (#0) eglot--managed-mode remove-hook post-command-hook nil buffer-live-p apply eglot--connect eglot--guess-contact] 4]): (error "[eglot] Couldn't guess for `emacs-lisp-mode'!")
```

**Comment by seagle0128** [comment]
It seems an issue about `eglot`.  I don't understand why `eglot` is enabled in `emacs-lisp-mode`. I am afraid I cannot help you here.
