### ISSUE TITLE
Can I customize source mirror in init.el?

### ISSUE THREAD

**Issue by lrvy** [seagle0128/.emacs.d#52]
because i have a mirror in my localhost😄️...

**Comment by seagle0128** [comment]
You can override `set-package-archives`. I don't know the exact url for your local mirror.

**Comment by lrvy** [comment]
Understand, thx.

**Comment by seagle0128** [comment]
Welcome. I am closing it. Please feel free to open if you have new issues.

**Comment by zwz** [comment]
@seagle0128 @lrvy 
I got the same problem.
There is a build-in variable `package-archives`.
I tried setting `package-archives`, but it did not work.
And I cannot find the help description for `set-package-archives`.
I don't know what data format for `set-package-archives`.

**Comment by seagle0128** [comment]
Did you take a look at README?

```elisp
 (setq centaur-package-archives 'emacs-china)   ; Package repo: melpa, melpa-mirror, emacs-china netease, tencent or tuna
```

**Comment by zwz** [comment]
Just miss it. 
Thank you.

**Comment by seagle0128** [comment]
Np.
