### ISSUE TITLE
THERE'S A NAKED MANHORSE ON MY SPLASH SCREEN

### ISSUE THREAD

**Issue by chrisvacc** [seagle0128/.emacs.d#54]
HOW MAKE CLOTHES

**Comment by CodyWilson** [comment]
Honestly, I'm just upset that it's not even anatomically correct.

**Comment by chrisvacc** [comment]
> Honestly, I'm just upset that it's not even anatomically correct.

CAN OYU MAKE A PULL REQUEST

**Comment by chrisvacc** [comment]
> Honestly, I'm just upset that it's not even anatomically correct.

HI CODYWILSON I FIXED THE ISSUE I HOPE DEV WILL CONSIDER PULLING THE IMPROVMENTS TO THE MAIN REPO

https://github.com/chrisvacc/.emacs.d

**Comment by seagle0128** [comment]
```elisp
(setq centaur-logo nil)
```

**Comment by seagle0128** [comment]
A new logo is available. The classic logo is reserved as `logo-classic.png`.
