### ISSUE TITLE
Slow Mouse Scrolling

### ISSUE THREAD

**Issue by EnzoKronus** [seagle0128/.emacs.d#57]
A query, when scrolling with the mouse, emacs freezes for 1 sec. or 2. It happens to me in almost all modes except the fundamental mode.

**Comment by seagle0128** [comment]
Please provide more details for troubleshooting, e.g. OS, Emacs version, packages, steps, errors, warnings, messages etc.

It's hard to analyze according to the current information.

**Comment by EnzoKronus** [comment]
> Please provide more details for troubleshooting, e.g. OS, Emacs version, packages, steps, errors, warnings, messages etc.
> 
> It's hard to analyze according to the current information.

My apologies, I understand.
-OS = KDE Neon 5.15.3
-Emacs version = 26.1
-Packages = All packages that come by default in centaur emacs
-Steps / Description = Opening a file, for example .js or o .html, of less than 200 lines (with active lsp or without lsp), the same generates a lag of approximately 2sg. when scrolling with the mouse of both the notebook and a mouse usb

-There are no warnings or messages, so,
I thought it was a problem with my notebook, a dell latitude (2015) with
8Gb of ram and Intel i5, but for example in vscode and sublime, the scroll works without problems, I know that in emacs one can navigate the code with C + arrow keys, = but sometimes I also use the scrolling mouse

**Comment by seagle0128** [comment]
Please do profiling while scrolling mouse. Refer to https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html. That will help to find out the bottleneck in your env.

**Comment by EnzoKronus** [comment]
> Please do profiling while scrolling mouse. Refer to https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html. That will help to find out the bottleneck in your env.

Ok Thank you very much, I'll be doing the tests to find it

**Comment by EnzoKronus** [comment]
- command-execute                                               16287  75%
 - apply                                                                   16287  75%
  - ad-Advice-command-execute                            16287  75%
   - #<compiled 0x24e123>                                     16279  75%
    - call-interactively                                                16275  75%
     - funcall-interactively                                          16275  75%
      - mwheel-scroll                                                  15963  73%
       + scroll-up                                                         196   0%
       + scroll-down                                                     160   0%
       + run-with-timer                                                  20   0%
         event-modifiers                                                 4   0%
         cancel-timer                                                      4   0%
      + counsel-M-x                                                      213   0%
      + treemacs-single-click-expand-action                 99   0%
+ redisplay_internal (C function)                                 2295  10%
+ timer-event-handler                                                 1172   5%
+ flyspell-post-command-hook                                    861   3%
+ ...                                                                              785   3%
+ which-key--hide-popup                                            63   0%
+ symbol-overlay-post-command                                      36   0%
+ winner-save-old-configurations                                   36   0%
+ jit-lock-function                                                32   0%
  yas--post-command-handler                                         8   0%
+ global-hl-line-highlight                                          8   0%
+ internal-timer-start-idle                                         8   0%
+ flycheck-hide-error-buffer                                        4   0%
+ delete-selection-pre-hook                                         4   0%
+ flycheck-display-error-at-point-soon                              4   0%
  whitespace-post-command-hook                                      4   0%
  company-pre-command                                               4   0%
  company-post-command                                              4   0%

**Comment by seagle0128** [comment]
It seems related to Emacs and DE themselves. I think the vanilla Emacs also has bad performance while scrolling. You can do profiling.

All related codes in Centaur is at https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-ui.el#L184. You can change them to check if it's better.

**Comment by EnzoKronus** [comment]
> It seems related to Emacs and DE themselves. I think the vanilla Emacs also has bad performance while scrolling. You can do profiling.
> 
> All related codes in Centaur is at https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-ui.el#L184. You can change them to check if it's better.

Yes, I was reading about it a few moments ago, at the moment it seems to consume less cpu changing (setq mouse-wheel-progressive-speed nil) to t, that solves it to work,
again thank you very much friend, the settings are great, especially the lsp

**Comment by seagle0128** [comment]
Glad to know the issue was addressed. I am closing it.
