### ISSUE TITLE
python模式下格式化太怪异了

### ISSUE THREAD

**Issue by cppddz** [seagle0128/.emacs.d#6]
比如下面这个
`class cla():
    
    def fun():
        pass
    def fun2():

        def fun1():
        pass

`
先写了class，然后写fun 和fun1,在fun1上插入fun2, fun1函数居然自动ＴＡＢ过去了。

**Comment by seagle0128** [comment]
这是因为 fun2 中没有任何内容，如果有会自动格式化回去。如果不喜欢可以 `M-x aggressive-indent-mode`. 我会尝试在代码中配置。

**Comment by seagle0128** [comment]
已经提交了代码，请测试。Python文件里会默认禁止indent。Close it.

**Comment by xhh** [comment]
@seagle0128 请问怎样全局禁用 aggressive-indent-mode 或者添加在哪些 major mode 下禁用?  
在 custom.el 里需要如何设置?

**Comment by seagle0128** [comment]
@xhh

```elisp
(with-eval-after-load 'aggressive-indent
  (global-aggressive-indent-mode -1))
```

```elisp
(push 'xxx-mode aggressive-indent-excluded-modes)
```

**Comment by xhh** [comment]
@seagle0128 我将第一种配置放到 custom.el 的最开始, 重启 Emacs 后仍然是默认开启的.  
第二种配置会报错 `Symbol's value as variable is void: aggressive-indent-excluded-modes`.

搜了好久 Google, 对 Emacs 不熟悉, 请见谅.

**Comment by seagle0128** [comment]
放到`custom-post.el`。请阅读 README。

```elisp
(with-eval-after-load 'aggressive-indent
  (global-aggressive-indent-mode -1)
  (push 'xxx-mode aggressive-indent-excluded-modes))
```
