### ISSUE TITLE
Misaligned icons

### ISSUE THREAD

**Issue by aagon** [seagle0128/.emacs.d#62]
Hello, Mr. Zhang, and thank you for your config that was (and still is) a huge help in the setting up of my own.

Your recent reddit post (https://www.reddit.com/r/emacs/comments/bc2z7n/centaur_emacs_integrates_colorful_icons/) prompted me to implement your various aesthetic improvements around icons, particularly in the treemacs, ibuffer, and ivy-rich buffers.

You might have noticed the slight misalignment stemming from the fact that the icons in the all-the-icons fonts are not of the same width, it is actually quite visible in the screenshot you posted on reddit.

You seem to have gone to great lengths to get rid of that problem, by methodically tweaking the heights and v-adjust, and trying to avoid particularly slim icons (the "i" of the help buffer, particularly visible in your example, that you chose to replace with the info-circle icon). But then I might be wrong to interpret your efforts that way.

If this misalignment bothers you, I might have found a solution that, I must admit, feels a bit like a hack.
I have systematically included a literal tab character ("\t") between the icon column and the next one in the ibuffer-format and ivy-rich-display-transformers-list variables, and set up tab-width to be 1 only in those buffers (the ibuffer buffer and minibuffer respectively).

I must say I'm quite happy with the result. See for yourself :

![2019-04-14-082724_1912x1054_scrot](https://user-images.githubusercontent.com/10883752/56089164-4ad02500-5e8f-11e9-8113-647fae5782f6.png)

I thought that it might interest you, despite it being a dirty way of avoiding the problem. I can open a PR to push my changes upstream if you're interested. Tell me !

**Comment by seagle0128** [comment]
Thanks for the update, @aagon ! I'm pleased the post is helpful for you.

The screenshots looks really cool, and I am interested in the method indeed. I spent some efforts on align the icons to make them beautiful, but seems difficult for some icons (e.g. change `info` to `info-circle`, modify `v-adjust` and/or `height`, etc.)
So, your PRs are welcome, definitely! We can make it better, I think. I'd like review it and make the decision. Thank you in advance!

**Comment by aagon** [comment]
Added PR #63 for review.

**Comment by seagle0128** [comment]
Closed by #63 .

**Comment by seagle0128** [comment]
Closed by #63.
