### ISSUE TITLE
使用evil插件后分词问题

### ISSUE THREAD

**Issue by wow-yorick** [seagle0128/.emacs.d#68]
您好，请教下 现在使用evil插件后用vim模式查询和修改词 都是按实际词来了，比如说 addSometing 这个字符串， 拆分成了 add  和Someting 两个词， 而不是原始的按空格拆分，请问下evil-mode下怎没关闭这个特性呀

**Comment by seagle0128** [comment]
你好，我个人并不使用 evil，所以关于 evil 的问题我都无法回答。你可以到 evil 社区或者 emacs-china 问问。谢谢！
