### ISSUE TITLE
Support for python virtual environments

### ISSUE THREAD

**Issue by KarthikNayak** [seagle0128/.emacs.d#69]
Hey,

Thanks for this awesome project. Really love it. 
How do I set/select a python virtual environment? How does it integrate with lsp-mode?

Thanks.

**Comment by seagle0128** [comment]
Hi,

I am not using python virtual environment personally, but I don't think it's much different. You may need https://github.com/porterjamesj/virtualenvwrapper.el or https://github.com/jorgenschaefer/pyvenv to setup pyenv in Emacs. Of course, you can just import env vars ($PATH, $PYTHONPATH) into Emacs. If you are using macOS, just leverage `exec-path-from-shell` package. 

To use lsp-mode, you need to install `python-language-server` (pyls) with specified Python version. If Emacs is able to find Python binary and libraries, all should work well, including lsp-mode. Good luck!

**Comment by KarthikNayak** [comment]
@seagle0128 Thanks a bunch! Really useful! :)
