### ISSUE TITLE
spaceline符号怪异

### ISSUE THREAD

**Issue by hidaris** [seagle0128/.emacs.d#7]
你好，我在安装后发现modeline的符号和readme里的截图不一致，似乎是有什么依赖没有装？
OS：MacOS12.13.1 
Emacs：emacs-mac25.3.3
![image](https://user-images.githubusercontent.com/8336146/32317518-fe138c56-bfee-11e7-83d5-4d6b523265d7.png)

**Comment by hidaris** [comment]
emm...发现cnfonts文件夹是空的，可能字体安装失败了，有什么重新安装的方法吗？

**Comment by seagle0128** [comment]
@hidaris 请安装powerline-fonts (https://github.com/powerline/fonts).

**Comment by hidaris** [comment]
@seagle0128 谢谢～
