### ISSUE TITLE
Active processes exist when exiting

### ISSUE THREAD

**Issue by waylandc** [seagle0128/.emacs.d#70]
Even if I open emacs without a file, do nothing and then exit C-x C-x, it always has at least one of the following processes running:

`Emacs -Q -l ~/.emacs.d/elpa/async-20181224.454/async.elc -batch -f async-batch-invoke <none>`

Sometimes, if I open a file and just browse around before closing, I'll get same warning but with many instances of the above processes running in background.

**Comment by seagle0128** [comment]
It's not a bug. `Flycheck` produces processes to check the files. If you don't like it, just disable it `(global-flycheck-mode -1)`. Meanwhile, other packages like `flyspell`, `lsp-mode` also make background processes.
