### ISSUE TITLE
清缓存恢复初始状态的方法

### ISSUE THREAD

**Issue by wow-yorick** [seagle0128/.emacs.d#71]
在使用lsp-mode 写golang时 也没改配置 就不能用了。今天更新过配置。
 是否可以提供个一键清缓存还原的功能

**Comment by wow-yorick** [comment]
使用goto definitation   godef 查找的路径不对
![image](https://user-images.githubusercontent.com/3367220/56793923-b32fe680-683f-11e9-99ec-33c087487268.png)

**Comment by seagle0128** [comment]
说实话，我没有看懂你的意思。Centuar中如果使用`lsp-mode`不会使用go-def。你需要更新和检查下你的本地配置，如果还有问题，请咨询`lsp-mode`或者相应的go-language-server项目。

**Comment by wow-yorick** [comment]
谢谢你的耐心回答
