### ISSUE TITLE
emacsclient 不能正常启动

### ISSUE THREAD

**Issue by awerdx520** [seagle0128/.emacs.d#73]
1. 你好我是一个emacs新手, 我使用您的配置,然后在`custom-post.el`中添加自己的配置.我在使用`cnfonts`包来改变`org`的中英文对齐表格时,加入如下配置: 
``` lisp
  1  ;; Auto generated by cnfonts
  2 ;; <https://github.com/tumashu/cnfonts>
  3   (set-face-attribute                 
  4    'default nil
  5    :font (font-spec :name "-PfEd-DejaVu Sans Mono-bold-oblique-normal-*-*-*-*-*-m-0-iso10646-1"
  6                     :weight 'normal
  7                     :slant 'normal
  8                     :size 10.0))
  9   (dolist (charset '(kana han symbol cjk-misc bopomofo))
 10     (set-fontset-font
 11      (frame-parameter nil 'font)
 12      charset
 13      (font-spec :name "-WQYF-文泉驿等宽微米黑-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"
 14                 :weight 'normal
 15                 :slant 'normal
 16                 :size 12.0)))
``` 
出现`emacsclient -a '' -nqc` 一直卡在`Loading /home/xxx/.emacs.d/custom-post.el (source)...`上,但是`emacs`是能正常启动,`server`模式不可以. `emacs`版本是26.2
2. 我在安装`pyim`包时,也是在`custom-post.el`文件中设置, 没有使用`(require 'pyim)`,会报错`can't active input method 'pyim`, 请问这是必须的吗.

**Comment by seagle0128** [comment]
1. `cnfonts` 不支持terminal模式。具体可咨询`cnfonts`项目。
1. 根据`pyim`的文档，必须`(require 'pyim)`.

**Comment by awerdx520** [comment]
我使用的GUI啊, 直接启动emacs没有问题, 配置都能加载,但是使用server 模式一直卡在loading,我去掉这个配置项,server模式就又能启动了, 之前我使用 直接配置emacs时都能使用.我这个加入的配置是emacs的原生属性.

**Comment by seagle0128** [comment]
由于兼容性问题比较多，并不建议使用cnfonts。
字体配置建议直接放到`custom.el`。
