### ISSUE TITLE
Editing is laggy for git repositories in Mac

### ISSUE THREAD

**Issue by karthikmuralidharan** [seagle0128/.emacs.d#74]
Hi, 

Thanks for the great configuration. I'm relatively new to emacs and it really helps.

One problem I have is that editing files in a git project result in consistent lags when editing. Profiling didn't seem to be helpful as well.  

Simply removing the `.git` folder resolves the laggy behavior.  Do you think magit has something to do with it?

I'm on a Macbook Pro 2015 model with `emacs-mac` 26.2 distribution if that helps.

Please let m know if you need the profiling info as well.

**Comment by karthikmuralidharan** [comment]
FYI, `(setq vc-handled-backends nil)` also resolves the lag during text editing.

**Comment by seagle0128** [comment]
Does it helpful to disable `diff-hl`?

```elisp
(diff-hl-flydiff-mode -1)
;; or 
(diff-hl-mode -1)
```

**Comment by karthikmuralidharan** [comment]
Yes, `(diff-hl-flydiff-mode -1)`  is helpful. Thank you very much !!

Any theories on why the lag doesn't occur on every machine?

**Comment by seagle0128** [comment]
It's related to the buffer numbers in git projects.
