### ISSUE TITLE
spacemacs

### ISSUE THREAD

**Issue by luixiao1223** [seagle0128/.emacs.d#8]
Why don't you change your configuration to spacemacs?

**Comment by seagle0128** [comment]
Thanks for your inquiry.

I tried, but `spacemacs` is too heavy and slow, and it's not the vanilla Emacs style for me. I just wanna a pure clean, simple and quick configuration for vanilla Emacs. I used the configuration for a several years, so it's stable. Honestly it will take long time to switch to `spacemacs`.

**Comment by danielcnorris** [comment]
@seagle0128 I'm just discovering this repo now, but I felt exactly the same -- I want a clean, fast emacs config that comes with modern tools included and conforms to best practices. Thanks for putting together! I look forward to checking it out.
