### ISSUE TITLE
每次启动会自动打开git帮助文档

### ISSUE THREAD

**Issue by chekore** [seagle0128/.emacs.d#84]
os：windows 7
emacs 26.2
每次启动emacs会自动在浏览器中打开git帮助文档
file:///D:/Git/mingw64/share/doc/git-doc/git-grep.html

**Comment by seagle0128** [comment]
怎么会，你打开过这个文件么？custom.el中是这个 配置吗？(setq centaur-dashboard t)`

**Comment by seagle0128** [comment]
怎么会？你在init.el中注释下`init-vcs.el`试试呢？

**Comment by chekore** [comment]
注释掉 init-vcs.el后不会出现上述问题，感觉是magit-auto-revert-mode默认是on造成的，怎么在配置文件里友好的关闭magit-auto-revert-mode呢？

**Comment by seagle0128** [comment]
在`~/.emacs.d/custom-post.el`中加上`(magit-auto-revert-mode -1)`.
如果你确信是这个问题，最好给magit报个issue。我没有使用windows，所以没有遇到该问题，不清楚是不是平台相关。也许已经有issue了。

**Comment by chekore** [comment]
> 在`~/.emacs.d/custom-post.el`中加上`(magit-auto-revert-mode -1)`.
> 如果你确信是这个问题，最好给magit报个issue。我没有使用windows，所以没有遇到该问题，不清楚是不是平台相关。也许已经有issue了。

在custom-post.el中加(magit-auto-revert-mode -1)不起作用，还是会自动打开

**Comment by seagle0128** [comment]
```elisp
(with-eval-after-load 'magit
  (magit-auto-revert-mode -1))
```

**Comment by seagle0128** [comment]
Update: 根因是`magit-todos-mode`造成的。
