### ISSUE TITLE
icons (fonts) not rendering on Windows

### ISSUE THREAD

**Issue by willwillis** [seagle0128/.emacs.d#85]
I'm new to CENTAUR. I cloned the repo, downloaded the fonts as the FAQ suggested, however after relaunching I still have "boxes" where fonts/icons should be. Is there a specific location I should be downloading the fonts to? I'm on windows, and "installed" all the fonts that were downloaded by M-x all-the-icons-install-fonts. After executing M-x all-the-icons-insert I'm presented with a list of icons, only those associated with faicon show correctly. I have confirmed that each font is installed - what else do I need to do to have the icons displayed correctly?

I'm running 26.1 x86_64-w64-mingw32

Thanks.

**Comment by seagle0128** [comment]
Hi, On Windows, you need to install the fonts manually after downloading. Please refer to https://github.com/domtronn/all-the-icons.el#installing-fonts for details.

**Comment by seagle0128** [comment]
Already updated FAQ.

**Comment by willwillis** [comment]
I commented out these blocks from custom.el and everything is working fine now.

- Specify font for all unicode characters
- Specify font for Chinese characters

![2019-06-03 14_54_47-Centaur Emacs - custom el](https://user-images.githubusercontent.com/46991/58830369-ca68ad80-860f-11e9-81e5-41e43cb3acb0.png)
