### ISSUE TITLE
Ivy's upstream changes break variable `ivy-format-function`

### ISSUE THREAD

**Issue by cireu** [seagle0128/.emacs.d#87]
Since this commit https://github.com/abo-abo/swiper/commit/7feb14f476e108dc10fe5380ee7c33de3b5fe3f1, Ivy mark `ivy-format-function` as obsolete, now Ivy use `ivy-format-functions-alist`.

This change may break the settings in `init-ivy.el`

https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-ivy.el#L130

Following code snippet may be a quick fix

```elisp
(setq ivy-format-functions-alist '(t . my-ivy-format-function-arrow))
```

But it seems that it's hard to keep UI consistency in Emacs because counsel/swiper add some customize format function ([exmaple](https://github.com/abo-abo/swiper/blob/master/counsel.el#L3905)) for special commands :(

**Comment by seagle0128** [comment]
Thank you for the reporting! I am investigating.
