### ISSUE TITLE
text moving around whenever using brackets in org-mode 

### ISSUE THREAD

**Issue by GeneKao** [seagle0128/.emacs.d#88]
Hi Vincent, 

Whenever I use org-mode, the text is always moving around if I have brackets like ( ) or { }. It would be great if this can be fixed. Thanks! 

Best, 
Gene 

![bug](https://user-images.githubusercontent.com/1162842/59609346-83061500-9117-11e9-9dbd-827e0a03fa3b.gif)

**Comment by seagle0128** [comment]
Are you using `Centaur`? It seems not, and I couldn't reproduce this issue locally.

**Comment by seagle0128** [comment]
It's a compatibility issue of `org-indent-mode` and `show-paren-mode`. Disabling `show-paren-mode` in org-mode should address this issue.

**Comment by GeneKao** [comment]
Thanks! It works perfectly now.
