### ISSUE TITLE
async.elc 开启了多个

### ISSUE THREAD

**Issue by wow-yorick** [seagle0128/.emacs.d#91]
![image](https://user-images.githubusercontent.com/3367220/60010544-94689780-96aa-11e9-9db7-cff09dc7131a.png)
请问下这个可以解决吗？ 软件很容易卡死 不晓得与这个有关不

**Comment by seagle0128** [comment]
请按照模版提供更多信息。比如详细办不好，这个是在什么情况下出现的进程，重现步骤等等。

**Comment by wow-yorick** [comment]
谢谢指教

**Comment by seagle0128** [comment]
最新的更新已经默认禁用`doom-modeline-github`。
