### ISSUE TITLE
关于lsp和dap-mode的问题

### ISSUE THREAD

**Issue by kuxiade** [seagle0128/.emacs.d#94]
@seagle0128 你好，很喜欢Centaur Emacs，我使用的是master分支。使用中发现 `dap-mode` 这里的逻辑似乎有些问题，主要是在运行 `after-init-hook`  后， `dap-mode`并没有随之启用 ，还是需要 `M-x` `dap-mode`。（这里如果是有特殊考虑的话，还请告知下）`
https://github.com/seagle0128/.emacs.d/blob/bc01c30a74a4a410f3a5645d99b8e5c926874389/lisp/init-lsp.el#L96-L100

针对上述情况，做了稍许修改：
```
;; Debug
(use-package dap-mode
  :after lsp-mode
  :diminish
  :config (dap-mode t)
  :hook ((dap-mode . dap-ui-mode)
  ...
```
不知朋友是否有别的更好的设置，再次谢谢你分享的配置，祝好运。

**Comment by seagle0128** [comment]
You are right! Thank you.

`dap-mode`最近更新了不少，没有及时更新配置。
