### ISSUE TITLE
全新安装，一些包装不上。

### ISSUE THREAD

**Issue by flyingns** [seagle0128/.emacs.d#95]
![Screen Shot 2019-07-19 at 21 37 26 ](https://user-images.githubusercontent.com/16456728/61539330-df898680-aa6d-11e9-8004-e9218e0f16af.png)

```
Mac mojave
Emacs-plus 26.2
```

**Comment by seagle0128** [comment]
网络问题，`package-refresh-contents`在重新启动。

**Comment by flyingns** [comment]
测试网络连接没有问题，就是安装不上，没办法只能从别的配置里cp过来解决下。但是还有一个始终没法解决。

Error (use-package): Failed to install lsp-python-ms: https://elpa.gnu.org/packages/python-0.26.1.el: Bad Request

**Comment by seagle0128** [comment]
你能直接下载 https://elpa.gnu.org/packages/python-0.26.1.el 吗？

**Comment by flyingns** [comment]
可以，直接下载没问题。

**Comment by seagle0128** [comment]
你用的 Emacs25.x？从 log 看应该是网络问题，重新下载试试

**Comment by flyingns** [comment]
emacs 26.2

**Comment by seagle0128** [comment]
从 error log 上看是 `~/.emacs.d/elpa/archives/gnu/archive-contents`没有下载或者下载不完整，导致所有 gnu 的 package 都找不到。有可能是 tls 证书问题。

https://lists.gnu.org/archive/html/emacs-devel/2018-02/msg00142.html
http://elpa.gnu.org/packages/gnu-elpa-keyring-update.html

**Comment by RomeuG** [comment]
So uh, what is the fix really?

**Comment by seagle0128** [comment]
> So uh, what is the fix really?

Sorry, I can't fix the network issue.

**Comment by RomeuG** [comment]
This might help:

https://emacs.stackexchange.com/questions/51615/my-init-el-gets-stuck-on-trying-to-install-spinner-a-sub-dependency-of-cider

Add `(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")` to the beginning of `init.el`.

This is obviously just a workaround, and a bad one at that.

**Comment by flyingns** [comment]
我的解决方法有点绕，虽然最终是解决了，但是有费解的地方，处理过程是这样的：

通过网络 update package 一直不成功，始终报 `Error (use-package): Failed to install lsp-python-ms: https://elpa.gnu.org/packages/python-0.26.1.el: Bad Request`。正好试了一下 rsync 把 elpa 的包都同步到本地了，然后 update 成了，但是下载的 python 包是 20120402，开动 emacs 报了错误：

```
Eager macro-expansion failure: (invalid-function (lambda (name doc &optional &rest skel) "Define a `python-mode' auxiliary skeleton using NAME DOC and SKEL.
```
吧拉吧拉一堆看的眼晕。后来到 elpa 下了 python-0.26.1.el 改名替换了 python-20120402 里的python.el，开动 emacs 无报错。

奇怪的地方来了，我把 python-20120402 的文件夹删了，开动 emacs 也不报错了，重新 update 也没有报错信息出来。

是 lsp-python-ms 解决依赖有问题吗？

**Comment by seagle0128** [comment]
`lsp-python-ms`依赖包：
 `cl-lib-0.6.1, lsp-mode-6.0, python-0.26.1, json-1.4, emacs-24.4`

**Comment by penn201500** [comment]
@RomeuG works for me,tks!
