### ISSUE TITLE
org文件的下划线如何正常展示？

### ISSUE THREAD

**Issue by penn201500** [seagle0128/.emacs.d#96]
操作系统：macos 10.13
版本：emacs 26.2
配置文件：当前最新.emacs.d版本
问题描述：test.org文件在展示 test_something时，下划线无法正常展示
![image](https://user-images.githubusercontent.com/16840448/61712675-6b125880-ad89-11e9-94fd-61097ec0f743.png)

**Comment by seagle0128** [comment]
`M-x org-toggle-pretty-entities` or `C-c C-x \`.

**Comment by penn201500** [comment]
@seagle0128  tks! 
手工执行可以解决该问题，但lisp/init_org.el中的配置为啥不生效呢？
118行： 
![image](https://user-images.githubusercontent.com/16840448/61852887-2273b000-aeed-11e9-9076-537bb06f1f72.png)

**Comment by penn201500** [comment]
init.el 中添加 (add-hook 'org-mode-hook 'org-toggle-pretty-entities) 也不生效

**Comment by seagle0128** [comment]
`(setq org-pretty-entities nil)`.

**Comment by penn201500** [comment]
多谢！问题解决：
