### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by RichWellum** [seagle0128/.emacs.d#98]
Emacs Version 26.2 (9.0)

New installation seeing:

Error (use-package): Failed to install gnu-elpa-keyring-update: Package ‘gnu-elpa-keyring-update-’ is unavailable
Error (use-package): Failed to install paradox: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install undo-tree: Package ‘undo-tree-’ is unavailable
Error (use-package): Failed to install goto-chg: Package ‘undo-tree-0.1.3’ is unavailable
Error (use-package): Failed to install lsp-origami: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install rainbow-mode: Package ‘rainbow-mode-’ is unavailable
Error (use-package): Failed to install memory-usage: Package ‘memory-usage-’ is unavailable
Error (use-package): Failed to install lsp-mode: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install lsp-ui: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install company-lsp: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install dap-mode: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install lsp-treemacs: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install lsp-python-ms: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install ccls: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Failed to install lsp-java: Package ‘spinner-1.7.3’ is unavailable

**Comment by seagle0128** [comment]
I believe it's a network issue while visiting gnu-elpa site. Please `M-x package-refresh-contents` and try again. Or change another network to retry.

**Comment by seagle0128** [comment]
Similar issue and workarounds on https://github.com/hlissner/doom-emacs/issues/444.

**Comment by RichWellum** [comment]
Thanks '2' worked for me.

**Comment by davidpgil** [comment]
Hi, i'm new to Emacs and want to use Centaur Emacs but I am getting this same issue. Where exactly do I put "(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")" to make this work? I put it in init.el and .emacs and both don't seem to fix the issue for me. I am using emacs 26.

**Comment by seagle0128** [comment]
@davidpgil If you are using Emacs 26.3, it should work well, otherwise put the configuration into `~/.emacs.d/custom.el`.

**Comment by davidpgil** [comment]
Im using Emacs 26.2 ... Lets see if Emacs 26.3 hs this issue fixed...
